package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/rkrimper1/jarvis/gateway/internal/config"
	"github.com/rkrimper1/jarvis/gateway/internal/middleware"
	"github.com/rkrimper1/jarvis/gateway/internal/proxy"
)

func main() {
	log := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(log)

	cfg, err := config.Load()
	if err != nil {
		log.Error("config load failed", slog.Any("err", err))
		os.Exit(1)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Dial all upstream gRPC services and build the gateway mux.
	p, err := proxy.New(ctx, cfg, log)
	if err != nil {
		log.Error("proxy init failed", slog.Any("err", err))
		os.Exit(1)
	}
	defer p.Close()

	// Build the middleware chain:
	//   Recovery → RequestID → Logger → CORS → Auth → GatewayMux
	//
	// Note the ordering: Recovery must be outermost so it can catch panics
	// from any layer. RequestID must come before Logger so the log line
	// always includes the ID. Auth is innermost so all infrastructure
	// middleware (logging, CORS, etc.) always runs even for rejected requests.
	handler := middleware.Recovery(log)(
		middleware.RequestID(
			middleware.Logger(log)(
				middleware.CORS(cfg.HTTP.CORSOrigins)(
					middleware.Auth(cfg.Auth.TokenSecret, cfg.Auth.PublicPaths)(
						p.Handler(),
					),
				),
			),
		),
	)

	addr := fmt.Sprintf(":%d", cfg.HTTP.Port)
	srv := &http.Server{
		Addr:         addr,
		Handler:      handler,
		ReadTimeout:  cfg.HTTP.ReadTimeout,
		WriteTimeout: cfg.HTTP.WriteTimeout,
	}

	log.Info("JARVIS API Gateway starting",
		slog.String("addr", addr),
		slog.String("service", "gateway"),
	)

	// Log the full REST API surface on startup so developers know what's available.
	logRoutes(log)

	errCh := make(chan error, 1)
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			errCh <- err
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		log.Info("shutdown signal received", slog.String("signal", sig.String()))
	case err := <-errCh:
		log.Error("server error", slog.Any("err", err))
	}

	log.Info("draining active connections...")
	shutCtx, shutCancel := context.WithTimeout(context.Background(), cfg.HTTP.ShutdownTimeout)
	defer shutCancel()

	if err := srv.Shutdown(shutCtx); err != nil {
		log.Warn("graceful shutdown timed out — forcing close", slog.Any("err", err))
		srv.Close()
	} else {
		log.Info("gateway stopped cleanly")
	}
}

// logRoutes prints the complete REST API surface to stdout on startup.
// This is a teaching-friendly summary — in production you'd serve this
// from the OpenAPI spec generated by buf.
func logRoutes(log *slog.Logger) {
	routes := []struct{ method, path, service string }{
		// NLP
		{"POST", "/v1/nlp/parse", "nlp-service"},
		{"POST", "/v1/nlp/dialogue", "nlp-service"},
		// Security
		{"POST", "/v1/security/authenticate", "security-service"},
		{"POST", "/v1/security/threat", "security-service"},
		{"POST", "/v1/security/protocol", "security-service"},
		{"GET", "/v1/security/audit", "security-service"},
		// Agents
		{"POST", "/v1/agents/dispatch", "agent-coordinator"},
		{"GET", "/v1/agents/status", "agent-coordinator"},
		{"POST", "/v1/agents/broadcast", "agent-coordinator"},
		// Hardware
		{"POST", "/v1/hardware/{device_id}/command", "hardware-service"},
		{"GET", "/v1/hardware/{device_id}/diagnostics", "hardware-service"},
		{"GET", "/v1/hardware/energy/scan", "hardware-service"},
		// Facility
		{"POST", "/v1/facility/zones/{zone_id}/system", "facility-service"},
		{"POST", "/v1/facility/zones/{zone_id}/access", "facility-service"},
		{"GET", "/v1/facility/zones/{zone_id}/environment", "facility-service"},
		// Intelligence
		{"POST", "/v1/intel/query", "intelligence-service"},
		{"POST", "/v1/intel/artifact", "intelligence-service"},
		{"POST", "/v1/intel/crossref", "intelligence-service"},
		// Business Ops
		{"POST", "/v1/business/schedule", "business-ops-service"},
		{"GET", "/v1/business/schedule/{subject_id}", "business-ops-service"},
		{"POST", "/v1/business/tasks", "business-ops-service"},
		{"POST", "/v1/business/messages", "business-ops-service"},
		{"POST", "/v1/business/reports", "business-ops-service"},
		// Learning
		{"POST", "/v1/learning/feedback", "learning-service"},
		{"GET", "/v1/learning/profile/{subject_id}", "learning-service"},
		{"GET", "/v1/learning/performance", "learning-service"},
		// Gateway
		{"GET", "/healthz", "gateway"},
	}

	for _, r := range routes {
		log.Info("route registered",
			slog.String("method", r.method),
			slog.String("path", r.path),
			slog.String("upstream", r.service),
		)
	}
}
