// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pb/task/task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_CreateTask_FullMethodName                = "/jarvis.task.TaskService/CreateTask"
	TaskService_GetTask_FullMethodName                   = "/jarvis.task.TaskService/GetTask"
	TaskService_UpdateTask_FullMethodName                = "/jarvis.task.TaskService/UpdateTask"
	TaskService_DeleteTask_FullMethodName                = "/jarvis.task.TaskService/DeleteTask"
	TaskService_ListBacklog_FullMethodName               = "/jarvis.task.TaskService/ListBacklog"
	TaskService_ListAllTasks_FullMethodName              = "/jarvis.task.TaskService/ListAllTasks"
	TaskService_ListSprintTasks_FullMethodName           = "/jarvis.task.TaskService/ListSprintTasks"
	TaskService_AssignTaskToSprint_FullMethodName        = "/jarvis.task.TaskService/AssignTaskToSprint"
	TaskService_MoveTaskStatus_FullMethodName            = "/jarvis.task.TaskService/MoveTaskStatus"
	TaskService_CreateSprint_FullMethodName              = "/jarvis.task.TaskService/CreateSprint"
	TaskService_UpdateSprint_FullMethodName              = "/jarvis.task.TaskService/UpdateSprint"
	TaskService_DeleteSprint_FullMethodName              = "/jarvis.task.TaskService/DeleteSprint"
	TaskService_CloseSprint_FullMethodName               = "/jarvis.task.TaskService/CloseSprint"
	TaskService_ListSprints_FullMethodName               = "/jarvis.task.TaskService/ListSprints"
	TaskService_GetSprintVelocity_FullMethodName         = "/jarvis.task.TaskService/GetSprintVelocity"
	TaskService_GetTaskStatusLog_FullMethodName          = "/jarvis.task.TaskService/GetTaskStatusLog"
	TaskService_GetTransitionReport_FullMethodName       = "/jarvis.task.TaskService/GetTransitionReport"
	TaskService_GetThroughputReport_FullMethodName       = "/jarvis.task.TaskService/GetThroughputReport"
	TaskService_GetAssigneeVelocityReport_FullMethodName = "/jarvis.task.TaskService/GetAssigneeVelocityReport"
	TaskService_GetSprintStatusReport_FullMethodName     = "/jarvis.task.TaskService/GetSprintStatusReport"
	TaskService_GetEndOfDayReport_FullMethodName         = "/jarvis.task.TaskService/GetEndOfDayReport"
	TaskService_GetReporterUsageReport_FullMethodName    = "/jarvis.task.TaskService/GetReporterUsageReport"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	ListBacklog(ctx context.Context, in *ListBacklogRequest, opts ...grpc.CallOption) (*ListBacklogResponse, error)
	ListAllTasks(ctx context.Context, in *ListAllTasksRequest, opts ...grpc.CallOption) (*ListAllTasksResponse, error)
	ListSprintTasks(ctx context.Context, in *ListSprintTasksRequest, opts ...grpc.CallOption) (*ListSprintTasksResponse, error)
	AssignTaskToSprint(ctx context.Context, in *AssignTaskToSprintRequest, opts ...grpc.CallOption) (*AssignTaskToSprintResponse, error)
	MoveTaskStatus(ctx context.Context, in *MoveTaskStatusRequest, opts ...grpc.CallOption) (*MoveTaskStatusResponse, error)
	CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error)
	UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error)
	DeleteSprint(ctx context.Context, in *DeleteSprintRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error)
	CloseSprint(ctx context.Context, in *CloseSprintRequest, opts ...grpc.CallOption) (*CloseSprintResponse, error)
	ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error)
	GetSprintVelocity(ctx context.Context, in *GetSprintVelocityRequest, opts ...grpc.CallOption) (*GetSprintVelocityResponse, error)
	GetTaskStatusLog(ctx context.Context, in *GetTaskStatusLogRequest, opts ...grpc.CallOption) (*GetTaskStatusLogResponse, error)
	GetTransitionReport(ctx context.Context, in *GetTransitionReportRequest, opts ...grpc.CallOption) (*GetTransitionReportResponse, error)
	GetThroughputReport(ctx context.Context, in *GetThroughputReportRequest, opts ...grpc.CallOption) (*GetThroughputReportResponse, error)
	GetAssigneeVelocityReport(ctx context.Context, in *GetAssigneeVelocityReportRequest, opts ...grpc.CallOption) (*GetAssigneeVelocityReportResponse, error)
	GetSprintStatusReport(ctx context.Context, in *GetSprintStatusReportRequest, opts ...grpc.CallOption) (*GetSprintStatusReportResponse, error)
	GetEndOfDayReport(ctx context.Context, in *GetEndOfDayReportRequest, opts ...grpc.CallOption) (*GetEndOfDayReportResponse, error)
	GetReporterUsageReport(ctx context.Context, in *GetReporterUsageReportRequest, opts ...grpc.CallOption) (*GetReporterUsageReportResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListBacklog(ctx context.Context, in *ListBacklogRequest, opts ...grpc.CallOption) (*ListBacklogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBacklogResponse)
	err := c.cc.Invoke(ctx, TaskService_ListBacklog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListAllTasks(ctx context.Context, in *ListAllTasksRequest, opts ...grpc.CallOption) (*ListAllTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListAllTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListSprintTasks(ctx context.Context, in *ListSprintTasksRequest, opts ...grpc.CallOption) (*ListSprintTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSprintTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListSprintTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AssignTaskToSprint(ctx context.Context, in *AssignTaskToSprintRequest, opts ...grpc.CallOption) (*AssignTaskToSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignTaskToSprintResponse)
	err := c.cc.Invoke(ctx, TaskService_AssignTaskToSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MoveTaskStatus(ctx context.Context, in *MoveTaskStatusRequest, opts ...grpc.CallOption) (*MoveTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveTaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskService_MoveTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSprintResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSprintResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteSprint(ctx context.Context, in *DeleteSprintRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSprintResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CloseSprint(ctx context.Context, in *CloseSprintRequest, opts ...grpc.CallOption) (*CloseSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSprintResponse)
	err := c.cc.Invoke(ctx, TaskService_CloseSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSprintsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListSprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetSprintVelocity(ctx context.Context, in *GetSprintVelocityRequest, opts ...grpc.CallOption) (*GetSprintVelocityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintVelocityResponse)
	err := c.cc.Invoke(ctx, TaskService_GetSprintVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskStatusLog(ctx context.Context, in *GetTaskStatusLogRequest, opts ...grpc.CallOption) (*GetTaskStatusLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusLogResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTaskStatusLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTransitionReport(ctx context.Context, in *GetTransitionReportRequest, opts ...grpc.CallOption) (*GetTransitionReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransitionReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTransitionReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetThroughputReport(ctx context.Context, in *GetThroughputReportRequest, opts ...grpc.CallOption) (*GetThroughputReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThroughputReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetThroughputReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetAssigneeVelocityReport(ctx context.Context, in *GetAssigneeVelocityReportRequest, opts ...grpc.CallOption) (*GetAssigneeVelocityReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssigneeVelocityReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetAssigneeVelocityReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetSprintStatusReport(ctx context.Context, in *GetSprintStatusReportRequest, opts ...grpc.CallOption) (*GetSprintStatusReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintStatusReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetSprintStatusReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetEndOfDayReport(ctx context.Context, in *GetEndOfDayReportRequest, opts ...grpc.CallOption) (*GetEndOfDayReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEndOfDayReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetEndOfDayReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetReporterUsageReport(ctx context.Context, in *GetReporterUsageReportRequest, opts ...grpc.CallOption) (*GetReporterUsageReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReporterUsageReportResponse)
	err := c.cc.Invoke(ctx, TaskService_GetReporterUsageReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	ListBacklog(context.Context, *ListBacklogRequest) (*ListBacklogResponse, error)
	ListAllTasks(context.Context, *ListAllTasksRequest) (*ListAllTasksResponse, error)
	ListSprintTasks(context.Context, *ListSprintTasksRequest) (*ListSprintTasksResponse, error)
	AssignTaskToSprint(context.Context, *AssignTaskToSprintRequest) (*AssignTaskToSprintResponse, error)
	MoveTaskStatus(context.Context, *MoveTaskStatusRequest) (*MoveTaskStatusResponse, error)
	CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error)
	UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error)
	DeleteSprint(context.Context, *DeleteSprintRequest) (*DeleteSprintResponse, error)
	CloseSprint(context.Context, *CloseSprintRequest) (*CloseSprintResponse, error)
	ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error)
	GetSprintVelocity(context.Context, *GetSprintVelocityRequest) (*GetSprintVelocityResponse, error)
	GetTaskStatusLog(context.Context, *GetTaskStatusLogRequest) (*GetTaskStatusLogResponse, error)
	GetTransitionReport(context.Context, *GetTransitionReportRequest) (*GetTransitionReportResponse, error)
	GetThroughputReport(context.Context, *GetThroughputReportRequest) (*GetThroughputReportResponse, error)
	GetAssigneeVelocityReport(context.Context, *GetAssigneeVelocityReportRequest) (*GetAssigneeVelocityReportResponse, error)
	GetSprintStatusReport(context.Context, *GetSprintStatusReportRequest) (*GetSprintStatusReportResponse, error)
	GetEndOfDayReport(context.Context, *GetEndOfDayReportRequest) (*GetEndOfDayReportResponse, error)
	GetReporterUsageReport(context.Context, *GetReporterUsageReportRequest) (*GetReporterUsageReportResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskServiceServer) ListBacklog(context.Context, *ListBacklogRequest) (*ListBacklogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBacklog not implemented")
}
func (UnimplementedTaskServiceServer) ListAllTasks(context.Context, *ListAllTasksRequest) (*ListAllTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllTasks not implemented")
}
func (UnimplementedTaskServiceServer) ListSprintTasks(context.Context, *ListSprintTasksRequest) (*ListSprintTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSprintTasks not implemented")
}
func (UnimplementedTaskServiceServer) AssignTaskToSprint(context.Context, *AssignTaskToSprintRequest) (*AssignTaskToSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTaskToSprint not implemented")
}
func (UnimplementedTaskServiceServer) MoveTaskStatus(context.Context, *MoveTaskStatusRequest) (*MoveTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveTaskStatus not implemented")
}
func (UnimplementedTaskServiceServer) CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSprint not implemented")
}
func (UnimplementedTaskServiceServer) UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSprint not implemented")
}
func (UnimplementedTaskServiceServer) DeleteSprint(context.Context, *DeleteSprintRequest) (*DeleteSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSprint not implemented")
}
func (UnimplementedTaskServiceServer) CloseSprint(context.Context, *CloseSprintRequest) (*CloseSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSprint not implemented")
}
func (UnimplementedTaskServiceServer) ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSprints not implemented")
}
func (UnimplementedTaskServiceServer) GetSprintVelocity(context.Context, *GetSprintVelocityRequest) (*GetSprintVelocityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSprintVelocity not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskStatusLog(context.Context, *GetTaskStatusLogRequest) (*GetTaskStatusLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatusLog not implemented")
}
func (UnimplementedTaskServiceServer) GetTransitionReport(context.Context, *GetTransitionReportRequest) (*GetTransitionReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransitionReport not implemented")
}
func (UnimplementedTaskServiceServer) GetThroughputReport(context.Context, *GetThroughputReportRequest) (*GetThroughputReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThroughputReport not implemented")
}
func (UnimplementedTaskServiceServer) GetAssigneeVelocityReport(context.Context, *GetAssigneeVelocityReportRequest) (*GetAssigneeVelocityReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssigneeVelocityReport not implemented")
}
func (UnimplementedTaskServiceServer) GetSprintStatusReport(context.Context, *GetSprintStatusReportRequest) (*GetSprintStatusReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSprintStatusReport not implemented")
}
func (UnimplementedTaskServiceServer) GetEndOfDayReport(context.Context, *GetEndOfDayReportRequest) (*GetEndOfDayReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEndOfDayReport not implemented")
}
func (UnimplementedTaskServiceServer) GetReporterUsageReport(context.Context, *GetReporterUsageReportRequest) (*GetReporterUsageReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReporterUsageReport not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListBacklog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBacklogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListBacklog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListBacklog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListBacklog(ctx, req.(*ListBacklogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListAllTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListAllTasks(ctx, req.(*ListAllTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListSprintTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSprintTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListSprintTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListSprintTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListSprintTasks(ctx, req.(*ListSprintTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AssignTaskToSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskToSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AssignTaskToSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AssignTaskToSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AssignTaskToSprint(ctx, req.(*AssignTaskToSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MoveTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MoveTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MoveTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MoveTaskStatus(ctx, req.(*MoveTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateSprint(ctx, req.(*CreateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateSprint(ctx, req.(*UpdateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteSprint(ctx, req.(*DeleteSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CloseSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CloseSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CloseSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CloseSprint(ctx, req.(*CloseSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListSprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListSprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListSprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListSprints(ctx, req.(*ListSprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetSprintVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetSprintVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetSprintVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetSprintVelocity(ctx, req.(*GetSprintVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskStatusLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskStatusLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskStatusLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskStatusLog(ctx, req.(*GetTaskStatusLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTransitionReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransitionReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTransitionReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTransitionReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTransitionReport(ctx, req.(*GetTransitionReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetThroughputReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThroughputReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetThroughputReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetThroughputReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetThroughputReport(ctx, req.(*GetThroughputReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetAssigneeVelocityReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssigneeVelocityReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetAssigneeVelocityReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetAssigneeVelocityReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetAssigneeVelocityReport(ctx, req.(*GetAssigneeVelocityReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetSprintStatusReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintStatusReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetSprintStatusReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetSprintStatusReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetSprintStatusReport(ctx, req.(*GetSprintStatusReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetEndOfDayReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndOfDayReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetEndOfDayReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetEndOfDayReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetEndOfDayReport(ctx, req.(*GetEndOfDayReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetReporterUsageReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReporterUsageReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetReporterUsageReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetReporterUsageReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetReporterUsageReport(ctx, req.(*GetReporterUsageReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
		{
			MethodName: "ListBacklog",
			Handler:    _TaskService_ListBacklog_Handler,
		},
		{
			MethodName: "ListAllTasks",
			Handler:    _TaskService_ListAllTasks_Handler,
		},
		{
			MethodName: "ListSprintTasks",
			Handler:    _TaskService_ListSprintTasks_Handler,
		},
		{
			MethodName: "AssignTaskToSprint",
			Handler:    _TaskService_AssignTaskToSprint_Handler,
		},
		{
			MethodName: "MoveTaskStatus",
			Handler:    _TaskService_MoveTaskStatus_Handler,
		},
		{
			MethodName: "CreateSprint",
			Handler:    _TaskService_CreateSprint_Handler,
		},
		{
			MethodName: "UpdateSprint",
			Handler:    _TaskService_UpdateSprint_Handler,
		},
		{
			MethodName: "DeleteSprint",
			Handler:    _TaskService_DeleteSprint_Handler,
		},
		{
			MethodName: "CloseSprint",
			Handler:    _TaskService_CloseSprint_Handler,
		},
		{
			MethodName: "ListSprints",
			Handler:    _TaskService_ListSprints_Handler,
		},
		{
			MethodName: "GetSprintVelocity",
			Handler:    _TaskService_GetSprintVelocity_Handler,
		},
		{
			MethodName: "GetTaskStatusLog",
			Handler:    _TaskService_GetTaskStatusLog_Handler,
		},
		{
			MethodName: "GetTransitionReport",
			Handler:    _TaskService_GetTransitionReport_Handler,
		},
		{
			MethodName: "GetThroughputReport",
			Handler:    _TaskService_GetThroughputReport_Handler,
		},
		{
			MethodName: "GetAssigneeVelocityReport",
			Handler:    _TaskService_GetAssigneeVelocityReport_Handler,
		},
		{
			MethodName: "GetSprintStatusReport",
			Handler:    _TaskService_GetSprintStatusReport_Handler,
		},
		{
			MethodName: "GetEndOfDayReport",
			Handler:    _TaskService_GetEndOfDayReport_Handler,
		},
		{
			MethodName: "GetReporterUsageReport",
			Handler:    _TaskService_GetReporterUsageReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/task/task.proto",
}
