// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/command/command.proto

package command

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMemoryProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMemoryProfileRequest) Reset() {
	*x = RequestMemoryProfileRequest{}
	mi := &file_pb_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMemoryProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMemoryProfileRequest) ProtoMessage() {}

func (x *RequestMemoryProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMemoryProfileRequest.ProtoReflect.Descriptor instead.
func (*RequestMemoryProfileRequest) Descriptor() ([]byte, []int) {
	return file_pb_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMemoryProfileRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RequestMemoryProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ProfPath      string                 `protobuf:"bytes,2,opt,name=prof_path,json=profPath,proto3" json:"prof_path,omitempty"` // path to the raw .prof file
	GifPath       string                 `protobuf:"bytes,3,opt,name=gif_path,json=gifPath,proto3" json:"gif_path,omitempty"`    // path to the rendered .gif (empty if graphviz unavailable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMemoryProfileResponse) Reset() {
	*x = RequestMemoryProfileResponse{}
	mi := &file_pb_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMemoryProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMemoryProfileResponse) ProtoMessage() {}

func (x *RequestMemoryProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMemoryProfileResponse.ProtoReflect.Descriptor instead.
func (*RequestMemoryProfileResponse) Descriptor() ([]byte, []int) {
	return file_pb_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMemoryProfileResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RequestMemoryProfileResponse) GetProfPath() string {
	if x != nil {
		return x.ProfPath
	}
	return ""
}

func (x *RequestMemoryProfileResponse) GetGifPath() string {
	if x != nil {
		return x.GifPath
	}
	return ""
}

var File_pb_command_command_proto protoreflect.FileDescriptor

const file_pb_command_command_proto_rawDesc = "" +
	"\n" +
	"\x18pb/command/command.proto\x12\x0ejarvis.command\x1a\x16pb/common/common.proto\x1a\x1cgoogle/api/annotations.proto\"M\n" +
	"\x1bRequestMemoryProfileRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\"\x87\x01\n" +
	"\x1cRequestMemoryProfileResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1b\n" +
	"\tprof_path\x18\x02 \x01(\tR\bprofPath\x12\x19\n" +
	"\bgif_path\x18\x03 \x01(\tR\agifPath2\xab\x01\n" +
	"\x0eCommandService\x12\x98\x01\n" +
	"\x14RequestMemoryProfile\x12+.jarvis.command.RequestMemoryProfileRequest\x1a,.jarvis.command.RequestMemoryProfileResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/command/memory-profileB\xa7\x01\n" +
	"\x12com.jarvis.commandB\fCommandProtoP\x01Z*github.com/rkrimper1/jarvis/api/pb/command\xa2\x02\x03JCX\xaa\x02\x0eJarvis.Command\xca\x02\x0eJarvis\\Command\xe2\x02\x1aJarvis\\Command\\GPBMetadata\xea\x02\x0fJarvis::Commandb\x06proto3"

var (
	file_pb_command_command_proto_rawDescOnce sync.Once
	file_pb_command_command_proto_rawDescData []byte
)

func file_pb_command_command_proto_rawDescGZIP() []byte {
	file_pb_command_command_proto_rawDescOnce.Do(func() {
		file_pb_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_command_command_proto_rawDesc), len(file_pb_command_command_proto_rawDesc)))
	})
	return file_pb_command_command_proto_rawDescData
}

var file_pb_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_command_command_proto_goTypes = []any{
	(*RequestMemoryProfileRequest)(nil),  // 0: jarvis.command.RequestMemoryProfileRequest
	(*RequestMemoryProfileResponse)(nil), // 1: jarvis.command.RequestMemoryProfileResponse
	(*common.RequestMeta)(nil),           // 2: jarvis.common.RequestMeta
	(*common.ResponseMeta)(nil),          // 3: jarvis.common.ResponseMeta
}
var file_pb_command_command_proto_depIdxs = []int32{
	2, // 0: jarvis.command.RequestMemoryProfileRequest.meta:type_name -> jarvis.common.RequestMeta
	3, // 1: jarvis.command.RequestMemoryProfileResponse.meta:type_name -> jarvis.common.ResponseMeta
	0, // 2: jarvis.command.CommandService.RequestMemoryProfile:input_type -> jarvis.command.RequestMemoryProfileRequest
	1, // 3: jarvis.command.CommandService.RequestMemoryProfile:output_type -> jarvis.command.RequestMemoryProfileResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_command_command_proto_init() }
func file_pb_command_command_proto_init() {
	if File_pb_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_command_command_proto_rawDesc), len(file_pb_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_command_command_proto_goTypes,
		DependencyIndexes: file_pb_command_command_proto_depIdxs,
		MessageInfos:      file_pb_command_command_proto_msgTypes,
	}.Build()
	File_pb_command_command_proto = out.File
	file_pb_command_command_proto_goTypes = nil
	file_pb_command_command_proto_depIdxs = nil
}
