// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/learning/learning.proto

package learning

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackType int32

const (
	FeedbackType_FEEDBACK_TYPE_UNSPECIFIED FeedbackType = 0
	FeedbackType_FEEDBACK_TYPE_POSITIVE    FeedbackType = 1
	FeedbackType_FEEDBACK_TYPE_NEGATIVE    FeedbackType = 2
	FeedbackType_FEEDBACK_TYPE_CORRECTION  FeedbackType = 3
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_TYPE_UNSPECIFIED",
		1: "FEEDBACK_TYPE_POSITIVE",
		2: "FEEDBACK_TYPE_NEGATIVE",
		3: "FEEDBACK_TYPE_CORRECTION",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_TYPE_UNSPECIFIED": 0,
		"FEEDBACK_TYPE_POSITIVE":    1,
		"FEEDBACK_TYPE_NEGATIVE":    2,
		"FEEDBACK_TYPE_CORRECTION":  3,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_learning_learning_proto_enumTypes[0].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_pb_learning_learning_proto_enumTypes[0]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{0}
}

type ModelDomain int32

const (
	ModelDomain_MODEL_DOMAIN_UNSPECIFIED ModelDomain = 0
	ModelDomain_MODEL_DOMAIN_NLP         ModelDomain = 1
	ModelDomain_MODEL_DOMAIN_THREAT      ModelDomain = 2
	ModelDomain_MODEL_DOMAIN_HARDWARE    ModelDomain = 3
	ModelDomain_MODEL_DOMAIN_BEHAVIOR    ModelDomain = 4
)

// Enum value maps for ModelDomain.
var (
	ModelDomain_name = map[int32]string{
		0: "MODEL_DOMAIN_UNSPECIFIED",
		1: "MODEL_DOMAIN_NLP",
		2: "MODEL_DOMAIN_THREAT",
		3: "MODEL_DOMAIN_HARDWARE",
		4: "MODEL_DOMAIN_BEHAVIOR",
	}
	ModelDomain_value = map[string]int32{
		"MODEL_DOMAIN_UNSPECIFIED": 0,
		"MODEL_DOMAIN_NLP":         1,
		"MODEL_DOMAIN_THREAT":      2,
		"MODEL_DOMAIN_HARDWARE":    3,
		"MODEL_DOMAIN_BEHAVIOR":    4,
	}
)

func (x ModelDomain) Enum() *ModelDomain {
	p := new(ModelDomain)
	*p = x
	return p
}

func (x ModelDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_learning_learning_proto_enumTypes[1].Descriptor()
}

func (ModelDomain) Type() protoreflect.EnumType {
	return &file_pb_learning_learning_proto_enumTypes[1]
}

func (x ModelDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelDomain.Descriptor instead.
func (ModelDomain) EnumDescriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{1}
}

type KnowledgeSource int32

const (
	KnowledgeSource_KNOWLEDGE_SOURCE_UNSPECIFIED KnowledgeSource = 0
	KnowledgeSource_KNOWLEDGE_SOURCE_WEB_SEARCH  KnowledgeSource = 1
	KnowledgeSource_KNOWLEDGE_SOURCE_CLAUDE_API  KnowledgeSource = 2
	KnowledgeSource_KNOWLEDGE_SOURCE_MANUAL      KnowledgeSource = 3
)

// Enum value maps for KnowledgeSource.
var (
	KnowledgeSource_name = map[int32]string{
		0: "KNOWLEDGE_SOURCE_UNSPECIFIED",
		1: "KNOWLEDGE_SOURCE_WEB_SEARCH",
		2: "KNOWLEDGE_SOURCE_CLAUDE_API",
		3: "KNOWLEDGE_SOURCE_MANUAL",
	}
	KnowledgeSource_value = map[string]int32{
		"KNOWLEDGE_SOURCE_UNSPECIFIED": 0,
		"KNOWLEDGE_SOURCE_WEB_SEARCH":  1,
		"KNOWLEDGE_SOURCE_CLAUDE_API":  2,
		"KNOWLEDGE_SOURCE_MANUAL":      3,
	}
)

func (x KnowledgeSource) Enum() *KnowledgeSource {
	p := new(KnowledgeSource)
	*p = x
	return p
}

func (x KnowledgeSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KnowledgeSource) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_learning_learning_proto_enumTypes[2].Descriptor()
}

func (KnowledgeSource) Type() protoreflect.EnumType {
	return &file_pb_learning_learning_proto_enumTypes[2]
}

func (x KnowledgeSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KnowledgeSource.Descriptor instead.
func (KnowledgeSource) EnumDescriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{2}
}

type SubmitFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	InteractionId string                 `protobuf:"bytes,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	FeedbackType  FeedbackType           `protobuf:"varint,3,opt,name=feedback_type,json=feedbackType,proto3,enum=jarvis.learning.FeedbackType" json:"feedback_type,omitempty"`
	Correction    string                 `protobuf:"bytes,4,opt,name=correction,proto3" json:"correction,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackRequest) Reset() {
	*x = SubmitFeedbackRequest{}
	mi := &file_pb_learning_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackRequest) ProtoMessage() {}

func (x *SubmitFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitFeedbackRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SubmitFeedbackRequest) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetFeedbackType() FeedbackType {
	if x != nil {
		return x.FeedbackType
	}
	return FeedbackType_FEEDBACK_TYPE_UNSPECIFIED
}

func (x *SubmitFeedbackRequest) GetCorrection() string {
	if x != nil {
		return x.Correction
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SubmitFeedbackRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type SubmitFeedbackResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Meta              *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	QueuedForTraining bool                   `protobuf:"varint,2,opt,name=queued_for_training,json=queuedForTraining,proto3" json:"queued_for_training,omitempty"`
	FeedbackId        string                 `protobuf:"bytes,3,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitFeedbackResponse) Reset() {
	*x = SubmitFeedbackResponse{}
	mi := &file_pb_learning_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResponse) ProtoMessage() {}

func (x *SubmitFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitFeedbackResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SubmitFeedbackResponse) GetQueuedForTraining() bool {
	if x != nil {
		return x.QueuedForTraining
	}
	return false
}

func (x *SubmitFeedbackResponse) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

type GetBehaviorProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBehaviorProfileRequest) Reset() {
	*x = GetBehaviorProfileRequest{}
	mi := &file_pb_learning_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBehaviorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBehaviorProfileRequest) ProtoMessage() {}

func (x *GetBehaviorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBehaviorProfileRequest.ProtoReflect.Descriptor instead.
func (*GetBehaviorProfileRequest) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{2}
}

func (x *GetBehaviorProfileRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetBehaviorProfileRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type GetBehaviorProfileResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Meta                         *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId                    string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TraitScores                  map[string]float32     `protobuf:"bytes,3,rep,name=trait_scores,json=traitScores,proto3" json:"trait_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	PreferredInteractionPatterns []string               `protobuf:"bytes,4,rep,name=preferred_interaction_patterns,json=preferredInteractionPatterns,proto3" json:"preferred_interaction_patterns,omitempty"`
	ProfileUpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=profile_updated_at,json=profileUpdatedAt,proto3" json:"profile_updated_at,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GetBehaviorProfileResponse) Reset() {
	*x = GetBehaviorProfileResponse{}
	mi := &file_pb_learning_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBehaviorProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBehaviorProfileResponse) ProtoMessage() {}

func (x *GetBehaviorProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBehaviorProfileResponse.ProtoReflect.Descriptor instead.
func (*GetBehaviorProfileResponse) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{3}
}

func (x *GetBehaviorProfileResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetBehaviorProfileResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetBehaviorProfileResponse) GetTraitScores() map[string]float32 {
	if x != nil {
		return x.TraitScores
	}
	return nil
}

func (x *GetBehaviorProfileResponse) GetPreferredInteractionPatterns() []string {
	if x != nil {
		return x.PreferredInteractionPatterns
	}
	return nil
}

func (x *GetBehaviorProfileResponse) GetProfileUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProfileUpdatedAt
	}
	return nil
}

type GetModelPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Domain        ModelDomain            `protobuf:"varint,2,opt,name=domain,proto3,enum=jarvis.learning.ModelDomain" json:"domain,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelPerformanceRequest) Reset() {
	*x = GetModelPerformanceRequest{}
	mi := &file_pb_learning_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelPerformanceRequest) ProtoMessage() {}

func (x *GetModelPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetModelPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelPerformanceRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetModelPerformanceRequest) GetDomain() ModelDomain {
	if x != nil {
		return x.Domain
	}
	return ModelDomain_MODEL_DOMAIN_UNSPECIFIED
}

func (x *GetModelPerformanceRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetModelPerformanceRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetModelPerformanceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Domain              ModelDomain            `protobuf:"varint,2,opt,name=domain,proto3,enum=jarvis.learning.ModelDomain" json:"domain,omitempty"`
	Accuracy            float32                `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Precision           float32                `protobuf:"fixed32,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Recall              float32                `protobuf:"fixed32,5,opt,name=recall,proto3" json:"recall,omitempty"`
	TotalInferences     int64                  `protobuf:"varint,6,opt,name=total_inferences,json=totalInferences,proto3" json:"total_inferences,omitempty"`
	DegradationWarnings []string               `protobuf:"bytes,7,rep,name=degradation_warnings,json=degradationWarnings,proto3" json:"degradation_warnings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetModelPerformanceResponse) Reset() {
	*x = GetModelPerformanceResponse{}
	mi := &file_pb_learning_learning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelPerformanceResponse) ProtoMessage() {}

func (x *GetModelPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetModelPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelPerformanceResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetModelPerformanceResponse) GetDomain() ModelDomain {
	if x != nil {
		return x.Domain
	}
	return ModelDomain_MODEL_DOMAIN_UNSPECIFIED
}

func (x *GetModelPerformanceResponse) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *GetModelPerformanceResponse) GetPrecision() float32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *GetModelPerformanceResponse) GetRecall() float32 {
	if x != nil {
		return x.Recall
	}
	return 0
}

func (x *GetModelPerformanceResponse) GetTotalInferences() int64 {
	if x != nil {
		return x.TotalInferences
	}
	return 0
}

func (x *GetModelPerformanceResponse) GetDegradationWarnings() []string {
	if x != nil {
		return x.DegradationWarnings
	}
	return nil
}

type AdaptationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Domain        ModelDomain            `protobuf:"varint,2,opt,name=domain,proto3,enum=jarvis.learning.ModelDomain" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DeltaAccuracy float32                `protobuf:"fixed32,4,opt,name=delta_accuracy,json=deltaAccuracy,proto3" json:"delta_accuracy,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptationEvent) Reset() {
	*x = AdaptationEvent{}
	mi := &file_pb_learning_learning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptationEvent) ProtoMessage() {}

func (x *AdaptationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptationEvent.ProtoReflect.Descriptor instead.
func (*AdaptationEvent) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{6}
}

func (x *AdaptationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AdaptationEvent) GetDomain() ModelDomain {
	if x != nil {
		return x.Domain
	}
	return ModelDomain_MODEL_DOMAIN_UNSPECIFIED
}

func (x *AdaptationEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdaptationEvent) GetDeltaAccuracy() float32 {
	if x != nil {
		return x.DeltaAccuracy
	}
	return 0
}

func (x *AdaptationEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamAdaptationEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAdaptationEventsRequest) Reset() {
	*x = StreamAdaptationEventsRequest{}
	mi := &file_pb_learning_learning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAdaptationEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAdaptationEventsRequest) ProtoMessage() {}

func (x *StreamAdaptationEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAdaptationEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamAdaptationEventsRequest) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{7}
}

func (x *StreamAdaptationEventsRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StreamAdaptationEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Event         *AdaptationEvent       `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAdaptationEventsResponse) Reset() {
	*x = StreamAdaptationEventsResponse{}
	mi := &file_pb_learning_learning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAdaptationEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAdaptationEventsResponse) ProtoMessage() {}

func (x *StreamAdaptationEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAdaptationEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamAdaptationEventsResponse) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{8}
}

func (x *StreamAdaptationEventsResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamAdaptationEventsResponse) GetEvent() *AdaptationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type KnowledgeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Source        KnowledgeSource        `protobuf:"varint,4,opt,name=source,proto3,enum=jarvis.learning.KnowledgeSource" json:"source,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeEntry) Reset() {
	*x = KnowledgeEntry{}
	mi := &file_pb_learning_learning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeEntry) ProtoMessage() {}

func (x *KnowledgeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeEntry.ProtoReflect.Descriptor instead.
func (*KnowledgeEntry) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{9}
}

func (x *KnowledgeEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeEntry) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *KnowledgeEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *KnowledgeEntry) GetSource() KnowledgeSource {
	if x != nil {
		return x.Source
	}
	return KnowledgeSource_KNOWLEDGE_SOURCE_UNSPECIFIED
}

func (x *KnowledgeEntry) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *KnowledgeEntry) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *KnowledgeEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SearchKnowledgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Query string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// preferred_source is used when needs_confirmation is true and the
	// user has chosen a source in the UI. Omit on the first call.
	PreferredSource KnowledgeSource `protobuf:"varint,3,opt,name=preferred_source,json=preferredSource,proto3,enum=jarvis.learning.KnowledgeSource" json:"preferred_source,omitempty"`
	// confirmed signals the user approved an external search after
	// receiving needs_confirmation = true on a prior call.
	Confirmed     bool `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKnowledgeRequest) Reset() {
	*x = SearchKnowledgeRequest{}
	mi := &file_pb_learning_learning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeRequest) ProtoMessage() {}

func (x *SearchKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{10}
}

func (x *SearchKnowledgeRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SearchKnowledgeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchKnowledgeRequest) GetPreferredSource() KnowledgeSource {
	if x != nil {
		return x.PreferredSource
	}
	return KnowledgeSource_KNOWLEDGE_SOURCE_UNSPECIFIED
}

func (x *SearchKnowledgeRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type SearchKnowledgeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Meta    *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Results []*KnowledgeEntry      `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// needs_confirmation is true when no fresh DB results exist and an
	// external search is available but has not yet been approved.
	NeedsConfirmation bool            `protobuf:"varint,3,opt,name=needs_confirmation,json=needsConfirmation,proto3" json:"needs_confirmation,omitempty"`
	SuggestedSource   KnowledgeSource `protobuf:"varint,4,opt,name=suggested_source,json=suggestedSource,proto3,enum=jarvis.learning.KnowledgeSource" json:"suggested_source,omitempty"`
	// searches_remaining is the number of external searches left in this session.
	SearchesRemaining int32 `protobuf:"varint,5,opt,name=searches_remaining,json=searchesRemaining,proto3" json:"searches_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchKnowledgeResponse) Reset() {
	*x = SearchKnowledgeResponse{}
	mi := &file_pb_learning_learning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeResponse) ProtoMessage() {}

func (x *SearchKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_learning_learning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_pb_learning_learning_proto_rawDescGZIP(), []int{11}
}

func (x *SearchKnowledgeResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetResults() []*KnowledgeEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetNeedsConfirmation() bool {
	if x != nil {
		return x.NeedsConfirmation
	}
	return false
}

func (x *SearchKnowledgeResponse) GetSuggestedSource() KnowledgeSource {
	if x != nil {
		return x.SuggestedSource
	}
	return KnowledgeSource_KNOWLEDGE_SOURCE_UNSPECIFIED
}

func (x *SearchKnowledgeResponse) GetSearchesRemaining() int32 {
	if x != nil {
		return x.SearchesRemaining
	}
	return 0
}

var File_pb_learning_learning_proto protoreflect.FileDescriptor

const file_pb_learning_learning_proto_rawDesc = "" +
	"\n" +
	"\x1apb/learning/learning.proto\x12\x0fjarvis.learning\x1a\x16pb/common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x80\x02\n" +
	"\x15SubmitFeedbackRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12%\n" +
	"\x0einteraction_id\x18\x02 \x01(\tR\rinteractionId\x12B\n" +
	"\rfeedback_type\x18\x03 \x01(\x0e2\x1d.jarvis.learning.FeedbackTypeR\ffeedbackType\x12\x1e\n" +
	"\n" +
	"correction\x18\x04 \x01(\tR\n" +
	"correction\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"\x9a\x01\n" +
	"\x16SubmitFeedbackResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12.\n" +
	"\x13queued_for_training\x18\x02 \x01(\bR\x11queuedForTraining\x12\x1f\n" +
	"\vfeedback_id\x18\x03 \x01(\tR\n" +
	"feedbackId\"j\n" +
	"\x19GetBehaviorProfileRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\"\x9d\x03\n" +
	"\x1aGetBehaviorProfileResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12_\n" +
	"\ftrait_scores\x18\x03 \x03(\v2<.jarvis.learning.GetBehaviorProfileResponse.TraitScoresEntryR\vtraitScores\x12D\n" +
	"\x1epreferred_interaction_patterns\x18\x04 \x03(\tR\x1cpreferredInteractionPatterns\x12H\n" +
	"\x12profile_updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10profileUpdatedAt\x1a>\n" +
	"\x10TraitScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xde\x01\n" +
	"\x1aGetModelPerformanceRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x124\n" +
	"\x06domain\x18\x02 \x01(\x0e2\x1c.jarvis.learning.ModelDomainR\x06domain\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xb4\x02\n" +
	"\x1bGetModelPerformanceResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x124\n" +
	"\x06domain\x18\x02 \x01(\x0e2\x1c.jarvis.learning.ModelDomainR\x06domain\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x02R\baccuracy\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x02R\tprecision\x12\x16\n" +
	"\x06recall\x18\x05 \x01(\x02R\x06recall\x12)\n" +
	"\x10total_inferences\x18\x06 \x01(\x03R\x0ftotalInferences\x121\n" +
	"\x14degradation_warnings\x18\a \x03(\tR\x13degradationWarnings\"\xe5\x01\n" +
	"\x0fAdaptationEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x124\n" +
	"\x06domain\x18\x02 \x01(\x0e2\x1c.jarvis.learning.ModelDomainR\x06domain\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0edelta_accuracy\x18\x04 \x01(\x02R\rdeltaAccuracy\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"O\n" +
	"\x1dStreamAdaptationEventsRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\"\x89\x01\n" +
	"\x1eStreamAdaptationEventsResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x126\n" +
	"\x05event\x18\x02 \x01(\v2 .jarvis.learning.AdaptationEventR\x05event\"\xb4\x02\n" +
	"\x0eKnowledgeEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x128\n" +
	"\x06source\x18\x04 \x01(\x0e2 .jarvis.learning.KnowledgeSourceR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc9\x01\n" +
	"\x16SearchKnowledgeRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12K\n" +
	"\x10preferred_source\x18\x03 \x01(\x0e2 .jarvis.learning.KnowledgeSourceR\x0fpreferredSource\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed\"\xb0\x02\n" +
	"\x17SearchKnowledgeResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.jarvis.learning.KnowledgeEntryR\aresults\x12-\n" +
	"\x12needs_confirmation\x18\x03 \x01(\bR\x11needsConfirmation\x12K\n" +
	"\x10suggested_source\x18\x04 \x01(\x0e2 .jarvis.learning.KnowledgeSourceR\x0fsuggestedSource\x12-\n" +
	"\x12searches_remaining\x18\x05 \x01(\x05R\x11searchesRemaining*\x83\x01\n" +
	"\fFeedbackType\x12\x1d\n" +
	"\x19FEEDBACK_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FEEDBACK_TYPE_POSITIVE\x10\x01\x12\x1a\n" +
	"\x16FEEDBACK_TYPE_NEGATIVE\x10\x02\x12\x1c\n" +
	"\x18FEEDBACK_TYPE_CORRECTION\x10\x03*\x90\x01\n" +
	"\vModelDomain\x12\x1c\n" +
	"\x18MODEL_DOMAIN_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MODEL_DOMAIN_NLP\x10\x01\x12\x17\n" +
	"\x13MODEL_DOMAIN_THREAT\x10\x02\x12\x19\n" +
	"\x15MODEL_DOMAIN_HARDWARE\x10\x03\x12\x19\n" +
	"\x15MODEL_DOMAIN_BEHAVIOR\x10\x04*\x92\x01\n" +
	"\x0fKnowledgeSource\x12 \n" +
	"\x1cKNOWLEDGE_SOURCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bKNOWLEDGE_SOURCE_WEB_SEARCH\x10\x01\x12\x1f\n" +
	"\x1bKNOWLEDGE_SOURCE_CLAUDE_API\x10\x02\x12\x1b\n" +
	"\x17KNOWLEDGE_SOURCE_MANUAL\x10\x032\xd5\x05\n" +
	"\x0fLearningService\x12\x83\x01\n" +
	"\x0eSubmitFeedback\x12&.jarvis.learning.SubmitFeedbackRequest\x1a'.jarvis.learning.SubmitFeedbackResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/learning/feedback\x12\x98\x01\n" +
	"\x12GetBehaviorProfile\x12*.jarvis.learning.GetBehaviorProfileRequest\x1a+.jarvis.learning.GetBehaviorProfileResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/learning/profile/{subject_id}\x12\x92\x01\n" +
	"\x13GetModelPerformance\x12+.jarvis.learning.GetModelPerformanceRequest\x1a,.jarvis.learning.GetModelPerformanceResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/learning/performance\x12{\n" +
	"\x16StreamAdaptationEvents\x12..jarvis.learning.StreamAdaptationEventsRequest\x1a/.jarvis.learning.StreamAdaptationEventsResponse0\x01\x12\x8e\x01\n" +
	"\x0fSearchKnowledge\x12'.jarvis.learning.SearchKnowledgeRequest\x1a(.jarvis.learning.SearchKnowledgeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/learning/knowledge/searchB\xae\x01\n" +
	"\x13com.jarvis.learningB\rLearningProtoP\x01Z+github.com/rkrimper1/jarvis/api/pb/learning\xa2\x02\x03JLX\xaa\x02\x0fJarvis.Learning\xca\x02\x0fJarvis\\Learning\xe2\x02\x1bJarvis\\Learning\\GPBMetadata\xea\x02\x10Jarvis::Learningb\x06proto3"

var (
	file_pb_learning_learning_proto_rawDescOnce sync.Once
	file_pb_learning_learning_proto_rawDescData []byte
)

func file_pb_learning_learning_proto_rawDescGZIP() []byte {
	file_pb_learning_learning_proto_rawDescOnce.Do(func() {
		file_pb_learning_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_learning_learning_proto_rawDesc), len(file_pb_learning_learning_proto_rawDesc)))
	})
	return file_pb_learning_learning_proto_rawDescData
}

var file_pb_learning_learning_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_learning_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_learning_learning_proto_goTypes = []any{
	(FeedbackType)(0),                      // 0: jarvis.learning.FeedbackType
	(ModelDomain)(0),                       // 1: jarvis.learning.ModelDomain
	(KnowledgeSource)(0),                   // 2: jarvis.learning.KnowledgeSource
	(*SubmitFeedbackRequest)(nil),          // 3: jarvis.learning.SubmitFeedbackRequest
	(*SubmitFeedbackResponse)(nil),         // 4: jarvis.learning.SubmitFeedbackResponse
	(*GetBehaviorProfileRequest)(nil),      // 5: jarvis.learning.GetBehaviorProfileRequest
	(*GetBehaviorProfileResponse)(nil),     // 6: jarvis.learning.GetBehaviorProfileResponse
	(*GetModelPerformanceRequest)(nil),     // 7: jarvis.learning.GetModelPerformanceRequest
	(*GetModelPerformanceResponse)(nil),    // 8: jarvis.learning.GetModelPerformanceResponse
	(*AdaptationEvent)(nil),                // 9: jarvis.learning.AdaptationEvent
	(*StreamAdaptationEventsRequest)(nil),  // 10: jarvis.learning.StreamAdaptationEventsRequest
	(*StreamAdaptationEventsResponse)(nil), // 11: jarvis.learning.StreamAdaptationEventsResponse
	(*KnowledgeEntry)(nil),                 // 12: jarvis.learning.KnowledgeEntry
	(*SearchKnowledgeRequest)(nil),         // 13: jarvis.learning.SearchKnowledgeRequest
	(*SearchKnowledgeResponse)(nil),        // 14: jarvis.learning.SearchKnowledgeResponse
	nil,                                    // 15: jarvis.learning.GetBehaviorProfileResponse.TraitScoresEntry
	(*common.RequestMeta)(nil),             // 16: jarvis.common.RequestMeta
	(*common.ResponseMeta)(nil),            // 17: jarvis.common.ResponseMeta
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
}
var file_pb_learning_learning_proto_depIdxs = []int32{
	16, // 0: jarvis.learning.SubmitFeedbackRequest.meta:type_name -> jarvis.common.RequestMeta
	0,  // 1: jarvis.learning.SubmitFeedbackRequest.feedback_type:type_name -> jarvis.learning.FeedbackType
	17, // 2: jarvis.learning.SubmitFeedbackResponse.meta:type_name -> jarvis.common.ResponseMeta
	16, // 3: jarvis.learning.GetBehaviorProfileRequest.meta:type_name -> jarvis.common.RequestMeta
	17, // 4: jarvis.learning.GetBehaviorProfileResponse.meta:type_name -> jarvis.common.ResponseMeta
	15, // 5: jarvis.learning.GetBehaviorProfileResponse.trait_scores:type_name -> jarvis.learning.GetBehaviorProfileResponse.TraitScoresEntry
	18, // 6: jarvis.learning.GetBehaviorProfileResponse.profile_updated_at:type_name -> google.protobuf.Timestamp
	16, // 7: jarvis.learning.GetModelPerformanceRequest.meta:type_name -> jarvis.common.RequestMeta
	1,  // 8: jarvis.learning.GetModelPerformanceRequest.domain:type_name -> jarvis.learning.ModelDomain
	18, // 9: jarvis.learning.GetModelPerformanceRequest.from:type_name -> google.protobuf.Timestamp
	18, // 10: jarvis.learning.GetModelPerformanceRequest.to:type_name -> google.protobuf.Timestamp
	17, // 11: jarvis.learning.GetModelPerformanceResponse.meta:type_name -> jarvis.common.ResponseMeta
	1,  // 12: jarvis.learning.GetModelPerformanceResponse.domain:type_name -> jarvis.learning.ModelDomain
	1,  // 13: jarvis.learning.AdaptationEvent.domain:type_name -> jarvis.learning.ModelDomain
	18, // 14: jarvis.learning.AdaptationEvent.timestamp:type_name -> google.protobuf.Timestamp
	16, // 15: jarvis.learning.StreamAdaptationEventsRequest.meta:type_name -> jarvis.common.RequestMeta
	17, // 16: jarvis.learning.StreamAdaptationEventsResponse.meta:type_name -> jarvis.common.ResponseMeta
	9,  // 17: jarvis.learning.StreamAdaptationEventsResponse.event:type_name -> jarvis.learning.AdaptationEvent
	2,  // 18: jarvis.learning.KnowledgeEntry.source:type_name -> jarvis.learning.KnowledgeSource
	18, // 19: jarvis.learning.KnowledgeEntry.created_at:type_name -> google.protobuf.Timestamp
	18, // 20: jarvis.learning.KnowledgeEntry.updated_at:type_name -> google.protobuf.Timestamp
	16, // 21: jarvis.learning.SearchKnowledgeRequest.meta:type_name -> jarvis.common.RequestMeta
	2,  // 22: jarvis.learning.SearchKnowledgeRequest.preferred_source:type_name -> jarvis.learning.KnowledgeSource
	17, // 23: jarvis.learning.SearchKnowledgeResponse.meta:type_name -> jarvis.common.ResponseMeta
	12, // 24: jarvis.learning.SearchKnowledgeResponse.results:type_name -> jarvis.learning.KnowledgeEntry
	2,  // 25: jarvis.learning.SearchKnowledgeResponse.suggested_source:type_name -> jarvis.learning.KnowledgeSource
	3,  // 26: jarvis.learning.LearningService.SubmitFeedback:input_type -> jarvis.learning.SubmitFeedbackRequest
	5,  // 27: jarvis.learning.LearningService.GetBehaviorProfile:input_type -> jarvis.learning.GetBehaviorProfileRequest
	7,  // 28: jarvis.learning.LearningService.GetModelPerformance:input_type -> jarvis.learning.GetModelPerformanceRequest
	10, // 29: jarvis.learning.LearningService.StreamAdaptationEvents:input_type -> jarvis.learning.StreamAdaptationEventsRequest
	13, // 30: jarvis.learning.LearningService.SearchKnowledge:input_type -> jarvis.learning.SearchKnowledgeRequest
	4,  // 31: jarvis.learning.LearningService.SubmitFeedback:output_type -> jarvis.learning.SubmitFeedbackResponse
	6,  // 32: jarvis.learning.LearningService.GetBehaviorProfile:output_type -> jarvis.learning.GetBehaviorProfileResponse
	8,  // 33: jarvis.learning.LearningService.GetModelPerformance:output_type -> jarvis.learning.GetModelPerformanceResponse
	11, // 34: jarvis.learning.LearningService.StreamAdaptationEvents:output_type -> jarvis.learning.StreamAdaptationEventsResponse
	14, // 35: jarvis.learning.LearningService.SearchKnowledge:output_type -> jarvis.learning.SearchKnowledgeResponse
	31, // [31:36] is the sub-list for method output_type
	26, // [26:31] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_pb_learning_learning_proto_init() }
func file_pb_learning_learning_proto_init() {
	if File_pb_learning_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_learning_learning_proto_rawDesc), len(file_pb_learning_learning_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_learning_learning_proto_goTypes,
		DependencyIndexes: file_pb_learning_learning_proto_depIdxs,
		EnumInfos:         file_pb_learning_learning_proto_enumTypes,
		MessageInfos:      file_pb_learning_learning_proto_msgTypes,
	}.Build()
	File_pb_learning_learning_proto = out.File
	file_pb_learning_learning_proto_goTypes = nil
	file_pb_learning_learning_proto_depIdxs = nil
}
