// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pb/learning/learning.proto

package learning

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearningService_SubmitFeedback_FullMethodName         = "/jarvis.learning.LearningService/SubmitFeedback"
	LearningService_GetBehaviorProfile_FullMethodName     = "/jarvis.learning.LearningService/GetBehaviorProfile"
	LearningService_GetModelPerformance_FullMethodName    = "/jarvis.learning.LearningService/GetModelPerformance"
	LearningService_StreamAdaptationEvents_FullMethodName = "/jarvis.learning.LearningService/StreamAdaptationEvents"
	LearningService_SearchKnowledge_FullMethodName        = "/jarvis.learning.LearningService/SearchKnowledge"
)

// LearningServiceClient is the client API for LearningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearningServiceClient interface {
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error)
	GetBehaviorProfile(ctx context.Context, in *GetBehaviorProfileRequest, opts ...grpc.CallOption) (*GetBehaviorProfileResponse, error)
	GetModelPerformance(ctx context.Context, in *GetModelPerformanceRequest, opts ...grpc.CallOption) (*GetModelPerformanceResponse, error)
	StreamAdaptationEvents(ctx context.Context, in *StreamAdaptationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAdaptationEventsResponse], error)
	SearchKnowledge(ctx context.Context, in *SearchKnowledgeRequest, opts ...grpc.CallOption) (*SearchKnowledgeResponse, error)
}

type learningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearningServiceClient(cc grpc.ClientConnInterface) LearningServiceClient {
	return &learningServiceClient{cc}
}

func (c *learningServiceClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFeedbackResponse)
	err := c.cc.Invoke(ctx, LearningService_SubmitFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) GetBehaviorProfile(ctx context.Context, in *GetBehaviorProfileRequest, opts ...grpc.CallOption) (*GetBehaviorProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBehaviorProfileResponse)
	err := c.cc.Invoke(ctx, LearningService_GetBehaviorProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) GetModelPerformance(ctx context.Context, in *GetModelPerformanceRequest, opts ...grpc.CallOption) (*GetModelPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelPerformanceResponse)
	err := c.cc.Invoke(ctx, LearningService_GetModelPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) StreamAdaptationEvents(ctx context.Context, in *StreamAdaptationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAdaptationEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[0], LearningService_StreamAdaptationEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAdaptationEventsRequest, StreamAdaptationEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LearningService_StreamAdaptationEventsClient = grpc.ServerStreamingClient[StreamAdaptationEventsResponse]

func (c *learningServiceClient) SearchKnowledge(ctx context.Context, in *SearchKnowledgeRequest, opts ...grpc.CallOption) (*SearchKnowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeResponse)
	err := c.cc.Invoke(ctx, LearningService_SearchKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearningServiceServer is the server API for LearningService service.
// All implementations must embed UnimplementedLearningServiceServer
// for forward compatibility.
type LearningServiceServer interface {
	SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error)
	GetBehaviorProfile(context.Context, *GetBehaviorProfileRequest) (*GetBehaviorProfileResponse, error)
	GetModelPerformance(context.Context, *GetModelPerformanceRequest) (*GetModelPerformanceResponse, error)
	StreamAdaptationEvents(*StreamAdaptationEventsRequest, grpc.ServerStreamingServer[StreamAdaptationEventsResponse]) error
	SearchKnowledge(context.Context, *SearchKnowledgeRequest) (*SearchKnowledgeResponse, error)
	mustEmbedUnimplementedLearningServiceServer()
}

// UnimplementedLearningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearningServiceServer struct{}

func (UnimplementedLearningServiceServer) SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFeedback not implemented")
}
func (UnimplementedLearningServiceServer) GetBehaviorProfile(context.Context, *GetBehaviorProfileRequest) (*GetBehaviorProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBehaviorProfile not implemented")
}
func (UnimplementedLearningServiceServer) GetModelPerformance(context.Context, *GetModelPerformanceRequest) (*GetModelPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelPerformance not implemented")
}
func (UnimplementedLearningServiceServer) StreamAdaptationEvents(*StreamAdaptationEventsRequest, grpc.ServerStreamingServer[StreamAdaptationEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAdaptationEvents not implemented")
}
func (UnimplementedLearningServiceServer) SearchKnowledge(context.Context, *SearchKnowledgeRequest) (*SearchKnowledgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedLearningServiceServer) mustEmbedUnimplementedLearningServiceServer() {}
func (UnimplementedLearningServiceServer) testEmbeddedByValue()                         {}

// UnsafeLearningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearningServiceServer will
// result in compilation errors.
type UnsafeLearningServiceServer interface {
	mustEmbedUnimplementedLearningServiceServer()
}

func RegisterLearningServiceServer(s grpc.ServiceRegistrar, srv LearningServiceServer) {
	// If the following call panics, it indicates UnimplementedLearningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearningService_ServiceDesc, srv)
}

func _LearningService_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_SubmitFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).SubmitFeedback(ctx, req.(*SubmitFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_GetBehaviorProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBehaviorProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetBehaviorProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetBehaviorProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetBehaviorProfile(ctx, req.(*GetBehaviorProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_GetModelPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetModelPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetModelPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetModelPerformance(ctx, req.(*GetModelPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_StreamAdaptationEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAdaptationEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearningServiceServer).StreamAdaptationEvents(m, &grpc.GenericServerStream[StreamAdaptationEventsRequest, StreamAdaptationEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LearningService_StreamAdaptationEventsServer = grpc.ServerStreamingServer[StreamAdaptationEventsResponse]

func _LearningService_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).SearchKnowledge(ctx, req.(*SearchKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LearningService_ServiceDesc is the grpc.ServiceDesc for LearningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.learning.LearningService",
	HandlerType: (*LearningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitFeedback",
			Handler:    _LearningService_SubmitFeedback_Handler,
		},
		{
			MethodName: "GetBehaviorProfile",
			Handler:    _LearningService_GetBehaviorProfile_Handler,
		},
		{
			MethodName: "GetModelPerformance",
			Handler:    _LearningService_GetModelPerformance_Handler,
		},
		{
			MethodName: "SearchKnowledge",
			Handler:    _LearningService_SearchKnowledge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAdaptationEvents",
			Handler:       _LearningService_StreamAdaptationEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/learning/learning.proto",
}
