// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: security/security.proto

package security

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED  AuthMethod = 0
	AuthMethod_AUTH_METHOD_VOICE_PRINT  AuthMethod = 1
	AuthMethod_AUTH_METHOD_RETINAL_SCAN AuthMethod = 2
	AuthMethod_AUTH_METHOD_TOKEN        AuthMethod = 3
	AuthMethod_AUTH_METHOD_BIOMETRIC    AuthMethod = 4
	AuthMethod_AUTH_METHOD_PASSCODE     AuthMethod = 5
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_VOICE_PRINT",
		2: "AUTH_METHOD_RETINAL_SCAN",
		3: "AUTH_METHOD_TOKEN",
		4: "AUTH_METHOD_BIOMETRIC",
		5: "AUTH_METHOD_PASSCODE",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED":  0,
		"AUTH_METHOD_VOICE_PRINT":  1,
		"AUTH_METHOD_RETINAL_SCAN": 2,
		"AUTH_METHOD_TOKEN":        3,
		"AUTH_METHOD_BIOMETRIC":    4,
		"AUTH_METHOD_PASSCODE":     5,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_security_security_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_security_security_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{0}
}

type ThreatLevel int32

const (
	ThreatLevel_THREAT_LEVEL_UNSPECIFIED ThreatLevel = 0
	ThreatLevel_THREAT_LEVEL_LOW         ThreatLevel = 1
	ThreatLevel_THREAT_LEVEL_MODERATE    ThreatLevel = 2
	ThreatLevel_THREAT_LEVEL_HIGH        ThreatLevel = 3
	ThreatLevel_THREAT_LEVEL_CRITICAL    ThreatLevel = 4
)

// Enum value maps for ThreatLevel.
var (
	ThreatLevel_name = map[int32]string{
		0: "THREAT_LEVEL_UNSPECIFIED",
		1: "THREAT_LEVEL_LOW",
		2: "THREAT_LEVEL_MODERATE",
		3: "THREAT_LEVEL_HIGH",
		4: "THREAT_LEVEL_CRITICAL",
	}
	ThreatLevel_value = map[string]int32{
		"THREAT_LEVEL_UNSPECIFIED": 0,
		"THREAT_LEVEL_LOW":         1,
		"THREAT_LEVEL_MODERATE":    2,
		"THREAT_LEVEL_HIGH":        3,
		"THREAT_LEVEL_CRITICAL":    4,
	}
)

func (x ThreatLevel) Enum() *ThreatLevel {
	p := new(ThreatLevel)
	*p = x
	return p
}

func (x ThreatLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_security_security_proto_enumTypes[1].Descriptor()
}

func (ThreatLevel) Type() protoreflect.EnumType {
	return &file_security_security_proto_enumTypes[1]
}

func (x ThreatLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatLevel.Descriptor instead.
func (ThreatLevel) EnumDescriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{1}
}

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_TYPE_UNSPECIFIED ProtocolType = 0
	ProtocolType_PROTOCOL_TYPE_LOCKDOWN    ProtocolType = 1
	ProtocolType_PROTOCOL_TYPE_EVACUATION  ProtocolType = 2
	ProtocolType_PROTOCOL_TYPE_CLEAN_SLATE ProtocolType = 3
	ProtocolType_PROTOCOL_TYPE_BLACKOUT    ProtocolType = 4
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_TYPE_UNSPECIFIED",
		1: "PROTOCOL_TYPE_LOCKDOWN",
		2: "PROTOCOL_TYPE_EVACUATION",
		3: "PROTOCOL_TYPE_CLEAN_SLATE",
		4: "PROTOCOL_TYPE_BLACKOUT",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_TYPE_UNSPECIFIED": 0,
		"PROTOCOL_TYPE_LOCKDOWN":    1,
		"PROTOCOL_TYPE_EVACUATION":  2,
		"PROTOCOL_TYPE_CLEAN_SLATE": 3,
		"PROTOCOL_TYPE_BLACKOUT":    4,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_security_security_proto_enumTypes[2].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_security_security_proto_enumTypes[2]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{2}
}

type AuthenticateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Meta              *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId         string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Method            AuthMethod             `protobuf:"varint,3,opt,name=method,proto3,enum=jarvis.security.AuthMethod" json:"method,omitempty"`
	CredentialPayload []byte                 `protobuf:"bytes,4,opt,name=credential_payload,json=credentialPayload,proto3" json:"credential_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_security_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuthenticateRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AuthenticateRequest) GetMethod() AuthMethod {
	if x != nil {
		return x.Method
	}
	return AuthMethod_AUTH_METHOD_UNSPECIFIED
}

func (x *AuthenticateRequest) GetCredentialPayload() []byte {
	if x != nil {
		return x.CredentialPayload
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Authenticated bool                   `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	GrantedScopes []string               `protobuf:"bytes,4,rep,name=granted_scopes,json=grantedScopes,proto3" json:"granted_scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_security_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuthenticateResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthenticateResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthenticateResponse) GetGrantedScopes() []string {
	if x != nil {
		return x.GrantedScopes
	}
	return nil
}

func (x *AuthenticateResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AssessThreatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ObservedSignals []string               `protobuf:"bytes,4,rep,name=observed_signals,json=observedSignals,proto3" json:"observed_signals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssessThreatRequest) Reset() {
	*x = AssessThreatRequest{}
	mi := &file_security_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessThreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessThreatRequest) ProtoMessage() {}

func (x *AssessThreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessThreatRequest.ProtoReflect.Descriptor instead.
func (*AssessThreatRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{2}
}

func (x *AssessThreatRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AssessThreatRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AssessThreatRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AssessThreatRequest) GetObservedSignals() []string {
	if x != nil {
		return x.ObservedSignals
	}
	return nil
}

type AssessThreatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Meta               *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Level              ThreatLevel            `protobuf:"varint,2,opt,name=level,proto3,enum=jarvis.security.ThreatLevel" json:"level,omitempty"`
	Confidence         float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ThreatSummary      string                 `protobuf:"bytes,4,opt,name=threat_summary,json=threatSummary,proto3" json:"threat_summary,omitempty"`
	RecommendedActions []string               `protobuf:"bytes,5,rep,name=recommended_actions,json=recommendedActions,proto3" json:"recommended_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssessThreatResponse) Reset() {
	*x = AssessThreatResponse{}
	mi := &file_security_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessThreatResponse) ProtoMessage() {}

func (x *AssessThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessThreatResponse.ProtoReflect.Descriptor instead.
func (*AssessThreatResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{3}
}

func (x *AssessThreatResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AssessThreatResponse) GetLevel() ThreatLevel {
	if x != nil {
		return x.Level
	}
	return ThreatLevel_THREAT_LEVEL_UNSPECIFIED
}

func (x *AssessThreatResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AssessThreatResponse) GetThreatSummary() string {
	if x != nil {
		return x.ThreatSummary
	}
	return ""
}

func (x *AssessThreatResponse) GetRecommendedActions() []string {
	if x != nil {
		return x.RecommendedActions
	}
	return nil
}

type ExecuteProtocolRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Protocol             ProtocolType           `protobuf:"varint,2,opt,name=protocol,proto3,enum=jarvis.security.ProtocolType" json:"protocol,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequiresConfirmation bool                   `protobuf:"varint,4,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExecuteProtocolRequest) Reset() {
	*x = ExecuteProtocolRequest{}
	mi := &file_security_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProtocolRequest) ProtoMessage() {}

func (x *ExecuteProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProtocolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProtocolRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteProtocolRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExecuteProtocolRequest) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *ExecuteProtocolRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExecuteProtocolRequest) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

type ExecuteProtocolResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ProtocolExecuted ProtocolType           `protobuf:"varint,2,opt,name=protocol_executed,json=protocolExecuted,proto3,enum=jarvis.security.ProtocolType" json:"protocol_executed,omitempty"`
	ActionsTaken     []string               `protobuf:"bytes,3,rep,name=actions_taken,json=actionsTaken,proto3" json:"actions_taken,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteProtocolResponse) Reset() {
	*x = ExecuteProtocolResponse{}
	mi := &file_security_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProtocolResponse) ProtoMessage() {}

func (x *ExecuteProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProtocolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProtocolResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteProtocolResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExecuteProtocolResponse) GetProtocolExecuted() ProtocolType {
	if x != nil {
		return x.ProtocolExecuted
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *ExecuteProtocolResponse) GetActionsTaken() []string {
	if x != nil {
		return x.ActionsTaken
	}
	return nil
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_security_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuditLogRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAuditLogRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetAuditLogRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetAuditLogRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetAuditLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAuditLogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_security_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{7}
}

func (x *AuditEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEntry) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEntry) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Entries       []*AuditEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_security_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuditLogResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAuditLogResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAuditLogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SecurityAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Level         ThreatLevel            `protobuf:"varint,2,opt,name=level,proto3,enum=jarvis.security.ThreatLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityAlert) Reset() {
	*x = SecurityAlert{}
	mi := &file_security_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityAlert) ProtoMessage() {}

func (x *SecurityAlert) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityAlert.ProtoReflect.Descriptor instead.
func (*SecurityAlert) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *SecurityAlert) GetLevel() ThreatLevel {
	if x != nil {
		return x.Level
	}
	return ThreatLevel_THREAT_LEVEL_UNSPECIFIED
}

func (x *SecurityAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecurityAlert) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SecurityAlert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamSecurityAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSecurityAlertsRequest) Reset() {
	*x = StreamSecurityAlertsRequest{}
	mi := &file_security_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSecurityAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSecurityAlertsRequest) ProtoMessage() {}

func (x *StreamSecurityAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSecurityAlertsRequest.ProtoReflect.Descriptor instead.
func (*StreamSecurityAlertsRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{10}
}

func (x *StreamSecurityAlertsRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StreamSecurityAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Alert         *SecurityAlert         `protobuf:"bytes,2,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSecurityAlertsResponse) Reset() {
	*x = StreamSecurityAlertsResponse{}
	mi := &file_security_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSecurityAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSecurityAlertsResponse) ProtoMessage() {}

func (x *StreamSecurityAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSecurityAlertsResponse.ProtoReflect.Descriptor instead.
func (*StreamSecurityAlertsResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{11}
}

func (x *StreamSecurityAlertsResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamSecurityAlertsResponse) GetAlert() *SecurityAlert {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_security_security_proto protoreflect.FileDescriptor

const file_security_security_proto_rawDesc = "" +
	"\n" +
	"\x17security/security.proto\x12\x0fjarvis.security\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xc8\x01\n" +
	"\x13AuthenticateRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x123\n" +
	"\x06method\x18\x03 \x01(\x0e2\x1b.jarvis.security.AuthMethodR\x06method\x12-\n" +
	"\x12credential_payload\x18\x04 \x01(\fR\x11credentialPayload\"\xf2\x01\n" +
	"\x14AuthenticateResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12$\n" +
	"\rauthenticated\x18\x02 \x01(\bR\rauthenticated\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12%\n" +
	"\x0egranted_scopes\x18\x04 \x03(\tR\rgrantedScopes\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xab\x01\n" +
	"\x13AssessThreatRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12)\n" +
	"\x10observed_signals\x18\x04 \x03(\tR\x0fobservedSignals\"\xf3\x01\n" +
	"\x14AssessThreatResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x122\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1c.jarvis.security.ThreatLevelR\x05level\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12%\n" +
	"\x0ethreat_summary\x18\x04 \x01(\tR\rthreatSummary\x12/\n" +
	"\x13recommended_actions\x18\x05 \x03(\tR\x12recommendedActions\"\xd0\x01\n" +
	"\x16ExecuteProtocolRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x129\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x1d.jarvis.security.ProtocolTypeR\bprotocol\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x123\n" +
	"\x15requires_confirmation\x18\x04 \x01(\bR\x14requiresConfirmation\"\xbb\x01\n" +
	"\x17ExecuteProtocolResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12J\n" +
	"\x11protocol_executed\x18\x02 \x01(\x0e2\x1d.jarvis.security.ProtocolTypeR\x10protocolExecuted\x12#\n" +
	"\ractions_taken\x18\x03 \x03(\tR\factionsTaken\"\xfb\x01\n" +
	"\x12GetAuditLogRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\xce\x01\n" +
	"\n" +
	"AuditEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa5\x01\n" +
	"\x13GetAuditLogResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.jarvis.security.AuditEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xca\x01\n" +
	"\rSecurityAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x122\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1c.jarvis.security.ThreatLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"M\n" +
	"\x1bStreamSecurityAlertsRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\"\x85\x01\n" +
	"\x1cStreamSecurityAlertsResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x124\n" +
	"\x05alert\x18\x02 \x01(\v2\x1e.jarvis.security.SecurityAlertR\x05alert*\xb0\x01\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AUTH_METHOD_VOICE_PRINT\x10\x01\x12\x1c\n" +
	"\x18AUTH_METHOD_RETINAL_SCAN\x10\x02\x12\x15\n" +
	"\x11AUTH_METHOD_TOKEN\x10\x03\x12\x19\n" +
	"\x15AUTH_METHOD_BIOMETRIC\x10\x04\x12\x18\n" +
	"\x14AUTH_METHOD_PASSCODE\x10\x05*\x8e\x01\n" +
	"\vThreatLevel\x12\x1c\n" +
	"\x18THREAT_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10THREAT_LEVEL_LOW\x10\x01\x12\x19\n" +
	"\x15THREAT_LEVEL_MODERATE\x10\x02\x12\x15\n" +
	"\x11THREAT_LEVEL_HIGH\x10\x03\x12\x19\n" +
	"\x15THREAT_LEVEL_CRITICAL\x10\x04*\xa2\x01\n" +
	"\fProtocolType\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROTOCOL_TYPE_LOCKDOWN\x10\x01\x12\x1c\n" +
	"\x18PROTOCOL_TYPE_EVACUATION\x10\x02\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_CLEAN_SLATE\x10\x03\x12\x1a\n" +
	"\x16PROTOCOL_TYPE_BLACKOUT\x10\x042\x88\x05\n" +
	"\x0fSecurityService\x12\x81\x01\n" +
	"\fAuthenticate\x12$.jarvis.security.AuthenticateRequest\x1a%.jarvis.security.AuthenticateResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/security/authenticate\x12{\n" +
	"\fAssessThreat\x12$.jarvis.security.AssessThreatRequest\x1a%.jarvis.security.AssessThreatResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/security/threat\x12\x86\x01\n" +
	"\x0fExecuteProtocol\x12'.jarvis.security.ExecuteProtocolRequest\x1a(.jarvis.security.ExecuteProtocolResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/security/protocol\x12t\n" +
	"\vGetAuditLog\x12#.jarvis.security.GetAuditLogRequest\x1a$.jarvis.security.GetAuditLogResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/security/audit\x12u\n" +
	"\x14StreamSecurityAlerts\x12,.jarvis.security.StreamSecurityAlertsRequest\x1a-.jarvis.security.StreamSecurityAlertsResponse0\x01B\xab\x01\n" +
	"\x13com.jarvis.securityB\rSecurityProtoP\x01Z(github.com/rkrimper1/jarvis/api/pb/security\xa2\x02\x03JSX\xaa\x02\x0fJarvis.Security\xca\x02\x0fJarvis\\Security\xe2\x02\x1bJarvis\\Security\\GPBMetadata\xea\x02\x10Jarvis::Securityb\x06proto3"

var (
	file_security_security_proto_rawDescOnce sync.Once
	file_security_security_proto_rawDescData []byte
)

func file_security_security_proto_rawDescGZIP() []byte {
	file_security_security_proto_rawDescOnce.Do(func() {
		file_security_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)))
	})
	return file_security_security_proto_rawDescData
}

var file_security_security_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_security_security_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_security_security_proto_goTypes = []any{
	(AuthMethod)(0),                      // 0: jarvis.security.AuthMethod
	(ThreatLevel)(0),                     // 1: jarvis.security.ThreatLevel
	(ProtocolType)(0),                    // 2: jarvis.security.ProtocolType
	(*AuthenticateRequest)(nil),          // 3: jarvis.security.AuthenticateRequest
	(*AuthenticateResponse)(nil),         // 4: jarvis.security.AuthenticateResponse
	(*AssessThreatRequest)(nil),          // 5: jarvis.security.AssessThreatRequest
	(*AssessThreatResponse)(nil),         // 6: jarvis.security.AssessThreatResponse
	(*ExecuteProtocolRequest)(nil),       // 7: jarvis.security.ExecuteProtocolRequest
	(*ExecuteProtocolResponse)(nil),      // 8: jarvis.security.ExecuteProtocolResponse
	(*GetAuditLogRequest)(nil),           // 9: jarvis.security.GetAuditLogRequest
	(*AuditEntry)(nil),                   // 10: jarvis.security.AuditEntry
	(*GetAuditLogResponse)(nil),          // 11: jarvis.security.GetAuditLogResponse
	(*SecurityAlert)(nil),                // 12: jarvis.security.SecurityAlert
	(*StreamSecurityAlertsRequest)(nil),  // 13: jarvis.security.StreamSecurityAlertsRequest
	(*StreamSecurityAlertsResponse)(nil), // 14: jarvis.security.StreamSecurityAlertsResponse
	(*common.RequestMeta)(nil),           // 15: jarvis.common.RequestMeta
	(*common.ResponseMeta)(nil),          // 16: jarvis.common.ResponseMeta
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
}
var file_security_security_proto_depIdxs = []int32{
	15, // 0: jarvis.security.AuthenticateRequest.meta:type_name -> jarvis.common.RequestMeta
	0,  // 1: jarvis.security.AuthenticateRequest.method:type_name -> jarvis.security.AuthMethod
	16, // 2: jarvis.security.AuthenticateResponse.meta:type_name -> jarvis.common.ResponseMeta
	17, // 3: jarvis.security.AuthenticateResponse.expires_at:type_name -> google.protobuf.Timestamp
	15, // 4: jarvis.security.AssessThreatRequest.meta:type_name -> jarvis.common.RequestMeta
	16, // 5: jarvis.security.AssessThreatResponse.meta:type_name -> jarvis.common.ResponseMeta
	1,  // 6: jarvis.security.AssessThreatResponse.level:type_name -> jarvis.security.ThreatLevel
	15, // 7: jarvis.security.ExecuteProtocolRequest.meta:type_name -> jarvis.common.RequestMeta
	2,  // 8: jarvis.security.ExecuteProtocolRequest.protocol:type_name -> jarvis.security.ProtocolType
	16, // 9: jarvis.security.ExecuteProtocolResponse.meta:type_name -> jarvis.common.ResponseMeta
	2,  // 10: jarvis.security.ExecuteProtocolResponse.protocol_executed:type_name -> jarvis.security.ProtocolType
	15, // 11: jarvis.security.GetAuditLogRequest.meta:type_name -> jarvis.common.RequestMeta
	17, // 12: jarvis.security.GetAuditLogRequest.from:type_name -> google.protobuf.Timestamp
	17, // 13: jarvis.security.GetAuditLogRequest.to:type_name -> google.protobuf.Timestamp
	17, // 14: jarvis.security.AuditEntry.timestamp:type_name -> google.protobuf.Timestamp
	16, // 15: jarvis.security.GetAuditLogResponse.meta:type_name -> jarvis.common.ResponseMeta
	10, // 16: jarvis.security.GetAuditLogResponse.entries:type_name -> jarvis.security.AuditEntry
	1,  // 17: jarvis.security.SecurityAlert.level:type_name -> jarvis.security.ThreatLevel
	17, // 18: jarvis.security.SecurityAlert.timestamp:type_name -> google.protobuf.Timestamp
	15, // 19: jarvis.security.StreamSecurityAlertsRequest.meta:type_name -> jarvis.common.RequestMeta
	16, // 20: jarvis.security.StreamSecurityAlertsResponse.meta:type_name -> jarvis.common.ResponseMeta
	12, // 21: jarvis.security.StreamSecurityAlertsResponse.alert:type_name -> jarvis.security.SecurityAlert
	3,  // 22: jarvis.security.SecurityService.Authenticate:input_type -> jarvis.security.AuthenticateRequest
	5,  // 23: jarvis.security.SecurityService.AssessThreat:input_type -> jarvis.security.AssessThreatRequest
	7,  // 24: jarvis.security.SecurityService.ExecuteProtocol:input_type -> jarvis.security.ExecuteProtocolRequest
	9,  // 25: jarvis.security.SecurityService.GetAuditLog:input_type -> jarvis.security.GetAuditLogRequest
	13, // 26: jarvis.security.SecurityService.StreamSecurityAlerts:input_type -> jarvis.security.StreamSecurityAlertsRequest
	4,  // 27: jarvis.security.SecurityService.Authenticate:output_type -> jarvis.security.AuthenticateResponse
	6,  // 28: jarvis.security.SecurityService.AssessThreat:output_type -> jarvis.security.AssessThreatResponse
	8,  // 29: jarvis.security.SecurityService.ExecuteProtocol:output_type -> jarvis.security.ExecuteProtocolResponse
	11, // 30: jarvis.security.SecurityService.GetAuditLog:output_type -> jarvis.security.GetAuditLogResponse
	14, // 31: jarvis.security.SecurityService.StreamSecurityAlerts:output_type -> jarvis.security.StreamSecurityAlertsResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_security_security_proto_init() }
func file_security_security_proto_init() {
	if File_security_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_security_proto_goTypes,
		DependencyIndexes: file_security_security_proto_depIdxs,
		EnumInfos:         file_security_security_proto_enumTypes,
		MessageInfos:      file_security_security_proto_msgTypes,
	}.Build()
	File_security_security_proto = out.File
	file_security_security_proto_goTypes = nil
	file_security_security_proto_depIdxs = nil
}
