// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pb/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentCoordinatorService_DispatchTask_FullMethodName             = "/jarvis.agent.AgentCoordinatorService/DispatchTask"
	AgentCoordinatorService_GetAgentStatus_FullMethodName           = "/jarvis.agent.AgentCoordinatorService/GetAgentStatus"
	AgentCoordinatorService_Broadcast_FullMethodName                = "/jarvis.agent.AgentCoordinatorService/Broadcast"
	AgentCoordinatorService_StreamCoordinationEvents_FullMethodName = "/jarvis.agent.AgentCoordinatorService/StreamCoordinationEvents"
	AgentCoordinatorService_AgentHeartbeat_FullMethodName           = "/jarvis.agent.AgentCoordinatorService/AgentHeartbeat"
)

// AgentCoordinatorServiceClient is the client API for AgentCoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentCoordinatorServiceClient interface {
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error)
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
	StreamCoordinationEvents(ctx context.Context, in *StreamCoordinationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCoordinationEventsResponse], error)
	AgentHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse], error)
}

type agentCoordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentCoordinatorServiceClient(cc grpc.ClientConnInterface) AgentCoordinatorServiceClient {
	return &agentCoordinatorServiceClient{cc}
}

func (c *agentCoordinatorServiceClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, AgentCoordinatorService_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoordinatorServiceClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentCoordinatorService_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoordinatorServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, AgentCoordinatorService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoordinatorServiceClient) StreamCoordinationEvents(ctx context.Context, in *StreamCoordinationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCoordinationEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentCoordinatorService_ServiceDesc.Streams[0], AgentCoordinatorService_StreamCoordinationEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCoordinationEventsRequest, StreamCoordinationEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoordinatorService_StreamCoordinationEventsClient = grpc.ServerStreamingClient[StreamCoordinationEventsResponse]

func (c *agentCoordinatorServiceClient) AgentHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentCoordinatorService_ServiceDesc.Streams[1], AgentCoordinatorService_AgentHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentHeartbeatRequest, AgentHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoordinatorService_AgentHeartbeatClient = grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse]

// AgentCoordinatorServiceServer is the server API for AgentCoordinatorService service.
// All implementations must embed UnimplementedAgentCoordinatorServiceServer
// for forward compatibility.
type AgentCoordinatorServiceServer interface {
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error)
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	StreamCoordinationEvents(*StreamCoordinationEventsRequest, grpc.ServerStreamingServer[StreamCoordinationEventsResponse]) error
	AgentHeartbeat(grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]) error
	mustEmbedUnimplementedAgentCoordinatorServiceServer()
}

// UnimplementedAgentCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentCoordinatorServiceServer struct{}

func (UnimplementedAgentCoordinatorServiceServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedAgentCoordinatorServiceServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedAgentCoordinatorServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedAgentCoordinatorServiceServer) StreamCoordinationEvents(*StreamCoordinationEventsRequest, grpc.ServerStreamingServer[StreamCoordinationEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCoordinationEvents not implemented")
}
func (UnimplementedAgentCoordinatorServiceServer) AgentHeartbeat(grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method AgentHeartbeat not implemented")
}
func (UnimplementedAgentCoordinatorServiceServer) mustEmbedUnimplementedAgentCoordinatorServiceServer() {
}
func (UnimplementedAgentCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeAgentCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentCoordinatorServiceServer will
// result in compilation errors.
type UnsafeAgentCoordinatorServiceServer interface {
	mustEmbedUnimplementedAgentCoordinatorServiceServer()
}

func RegisterAgentCoordinatorServiceServer(s grpc.ServiceRegistrar, srv AgentCoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentCoordinatorService_ServiceDesc, srv)
}

func _AgentCoordinatorService_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoordinatorServiceServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoordinatorService_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoordinatorServiceServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoordinatorService_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoordinatorServiceServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoordinatorService_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoordinatorServiceServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoordinatorService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoordinatorServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoordinatorService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoordinatorServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoordinatorService_StreamCoordinationEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCoordinationEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentCoordinatorServiceServer).StreamCoordinationEvents(m, &grpc.GenericServerStream[StreamCoordinationEventsRequest, StreamCoordinationEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoordinatorService_StreamCoordinationEventsServer = grpc.ServerStreamingServer[StreamCoordinationEventsResponse]

func _AgentCoordinatorService_AgentHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentCoordinatorServiceServer).AgentHeartbeat(&grpc.GenericServerStream[AgentHeartbeatRequest, AgentHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoordinatorService_AgentHeartbeatServer = grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]

// AgentCoordinatorService_ServiceDesc is the grpc.ServiceDesc for AgentCoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentCoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.agent.AgentCoordinatorService",
	HandlerType: (*AgentCoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _AgentCoordinatorService_DispatchTask_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _AgentCoordinatorService_GetAgentStatus_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _AgentCoordinatorService_Broadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCoordinationEvents",
			Handler:       _AgentCoordinatorService_StreamCoordinationEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AgentHeartbeat",
			Handler:       _AgentCoordinatorService_AgentHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/agent/agent.proto",
}
