// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: intelligence/intelligence.proto

package intelligence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntelligenceService_QueryIntel_FullMethodName         = "/jarvis.intelligence.IntelligenceService/QueryIntel"
	IntelligenceService_AnalyzeArtifact_FullMethodName    = "/jarvis.intelligence.IntelligenceService/AnalyzeArtifact"
	IntelligenceService_CrossReference_FullMethodName     = "/jarvis.intelligence.IntelligenceService/CrossReference"
	IntelligenceService_StreamIntelUpdates_FullMethodName = "/jarvis.intelligence.IntelligenceService/StreamIntelUpdates"
)

// IntelligenceServiceClient is the client API for IntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntelligenceServiceClient interface {
	QueryIntel(ctx context.Context, in *QueryIntelRequest, opts ...grpc.CallOption) (*QueryIntelResponse, error)
	AnalyzeArtifact(ctx context.Context, in *AnalyzeArtifactRequest, opts ...grpc.CallOption) (*AnalyzeArtifactResponse, error)
	CrossReference(ctx context.Context, in *CrossReferenceRequest, opts ...grpc.CallOption) (*CrossReferenceResponse, error)
	StreamIntelUpdates(ctx context.Context, in *StreamIntelUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamIntelUpdatesResponse], error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) QueryIntel(ctx context.Context, in *QueryIntelRequest, opts ...grpc.CallOption) (*QueryIntelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIntelResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_QueryIntel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) AnalyzeArtifact(ctx context.Context, in *AnalyzeArtifactRequest, opts ...grpc.CallOption) (*AnalyzeArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeArtifactResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_AnalyzeArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) CrossReference(ctx context.Context, in *CrossReferenceRequest, opts ...grpc.CallOption) (*CrossReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrossReferenceResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_CrossReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) StreamIntelUpdates(ctx context.Context, in *StreamIntelUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamIntelUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntelligenceService_ServiceDesc.Streams[0], IntelligenceService_StreamIntelUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamIntelUpdatesRequest, StreamIntelUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_StreamIntelUpdatesClient = grpc.ServerStreamingClient[StreamIntelUpdatesResponse]

// IntelligenceServiceServer is the server API for IntelligenceService service.
// All implementations must embed UnimplementedIntelligenceServiceServer
// for forward compatibility.
type IntelligenceServiceServer interface {
	QueryIntel(context.Context, *QueryIntelRequest) (*QueryIntelResponse, error)
	AnalyzeArtifact(context.Context, *AnalyzeArtifactRequest) (*AnalyzeArtifactResponse, error)
	CrossReference(context.Context, *CrossReferenceRequest) (*CrossReferenceResponse, error)
	StreamIntelUpdates(*StreamIntelUpdatesRequest, grpc.ServerStreamingServer[StreamIntelUpdatesResponse]) error
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelligenceServiceServer struct{}

func (UnimplementedIntelligenceServiceServer) QueryIntel(context.Context, *QueryIntelRequest) (*QueryIntelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryIntel not implemented")
}
func (UnimplementedIntelligenceServiceServer) AnalyzeArtifact(context.Context, *AnalyzeArtifactRequest) (*AnalyzeArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeArtifact not implemented")
}
func (UnimplementedIntelligenceServiceServer) CrossReference(context.Context, *CrossReferenceRequest) (*CrossReferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrossReference not implemented")
}
func (UnimplementedIntelligenceServiceServer) StreamIntelUpdates(*StreamIntelUpdatesRequest, grpc.ServerStreamingServer[StreamIntelUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamIntelUpdates not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}
func (UnimplementedIntelligenceServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServiceServer will
// result in compilation errors.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	// If the following call panics, it indicates UnimplementedIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_QueryIntel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIntelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).QueryIntel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_QueryIntel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).QueryIntel(ctx, req.(*QueryIntelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_AnalyzeArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).AnalyzeArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_AnalyzeArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).AnalyzeArtifact(ctx, req.(*AnalyzeArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_CrossReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).CrossReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_CrossReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).CrossReference(ctx, req.(*CrossReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_StreamIntelUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamIntelUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntelligenceServiceServer).StreamIntelUpdates(m, &grpc.GenericServerStream[StreamIntelUpdatesRequest, StreamIntelUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_StreamIntelUpdatesServer = grpc.ServerStreamingServer[StreamIntelUpdatesResponse]

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.intelligence.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryIntel",
			Handler:    _IntelligenceService_QueryIntel_Handler,
		},
		{
			MethodName: "AnalyzeArtifact",
			Handler:    _IntelligenceService_AnalyzeArtifact_Handler,
		},
		{
			MethodName: "CrossReference",
			Handler:    _IntelligenceService_CrossReference_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIntelUpdates",
			Handler:       _IntelligenceService_StreamIntelUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "intelligence/intelligence.proto",
}
