// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/intelligence/intelligence.proto

package intelligence

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubjectType int32

const (
	SubjectType_SUBJECT_TYPE_UNSPECIFIED  SubjectType = 0
	SubjectType_SUBJECT_TYPE_PERSON       SubjectType = 1
	SubjectType_SUBJECT_TYPE_ORGANIZATION SubjectType = 2
	SubjectType_SUBJECT_TYPE_TECHNOLOGY   SubjectType = 3
	SubjectType_SUBJECT_TYPE_LOCATION     SubjectType = 4
	SubjectType_SUBJECT_TYPE_ARTIFACT     SubjectType = 5
)

// Enum value maps for SubjectType.
var (
	SubjectType_name = map[int32]string{
		0: "SUBJECT_TYPE_UNSPECIFIED",
		1: "SUBJECT_TYPE_PERSON",
		2: "SUBJECT_TYPE_ORGANIZATION",
		3: "SUBJECT_TYPE_TECHNOLOGY",
		4: "SUBJECT_TYPE_LOCATION",
		5: "SUBJECT_TYPE_ARTIFACT",
	}
	SubjectType_value = map[string]int32{
		"SUBJECT_TYPE_UNSPECIFIED":  0,
		"SUBJECT_TYPE_PERSON":       1,
		"SUBJECT_TYPE_ORGANIZATION": 2,
		"SUBJECT_TYPE_TECHNOLOGY":   3,
		"SUBJECT_TYPE_LOCATION":     4,
		"SUBJECT_TYPE_ARTIFACT":     5,
	}
)

func (x SubjectType) Enum() *SubjectType {
	p := new(SubjectType)
	*p = x
	return p
}

func (x SubjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intelligence_intelligence_proto_enumTypes[0].Descriptor()
}

func (SubjectType) Type() protoreflect.EnumType {
	return &file_pb_intelligence_intelligence_proto_enumTypes[0]
}

func (x SubjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectType.Descriptor instead.
func (SubjectType) EnumDescriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{0}
}

type AnalysisDepth int32

const (
	AnalysisDepth_ANALYSIS_DEPTH_UNSPECIFIED AnalysisDepth = 0
	AnalysisDepth_ANALYSIS_DEPTH_STANDARD    AnalysisDepth = 1
	AnalysisDepth_ANALYSIS_DEPTH_DEEP        AnalysisDepth = 2
)

// Enum value maps for AnalysisDepth.
var (
	AnalysisDepth_name = map[int32]string{
		0: "ANALYSIS_DEPTH_UNSPECIFIED",
		1: "ANALYSIS_DEPTH_STANDARD",
		2: "ANALYSIS_DEPTH_DEEP",
	}
	AnalysisDepth_value = map[string]int32{
		"ANALYSIS_DEPTH_UNSPECIFIED": 0,
		"ANALYSIS_DEPTH_STANDARD":    1,
		"ANALYSIS_DEPTH_DEEP":        2,
	}
)

func (x AnalysisDepth) Enum() *AnalysisDepth {
	p := new(AnalysisDepth)
	*p = x
	return p
}

func (x AnalysisDepth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisDepth) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intelligence_intelligence_proto_enumTypes[1].Descriptor()
}

func (AnalysisDepth) Type() protoreflect.EnumType {
	return &file_pb_intelligence_intelligence_proto_enumTypes[1]
}

func (x AnalysisDepth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisDepth.Descriptor instead.
func (AnalysisDepth) EnumDescriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{1}
}

type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNSPECIFIED SourceType = 0
	SourceType_SOURCE_TYPE_MANUAL      SourceType = 1
	SourceType_SOURCE_TYPE_RSS         SourceType = 2
	SourceType_SOURCE_TYPE_FILE_UPLOAD SourceType = 3
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_MANUAL",
		2: "SOURCE_TYPE_RSS",
		3: "SOURCE_TYPE_FILE_UPLOAD",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_MANUAL":      1,
		"SOURCE_TYPE_RSS":         2,
		"SOURCE_TYPE_FILE_UPLOAD": 3,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intelligence_intelligence_proto_enumTypes[2].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_pb_intelligence_intelligence_proto_enumTypes[2]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{2}
}

type OpportunityType int32

const (
	OpportunityType_OPPORTUNITY_TYPE_UNSPECIFIED       OpportunityType = 0
	OpportunityType_OPPORTUNITY_TYPE_TACTICAL          OpportunityType = 1
	OpportunityType_OPPORTUNITY_TYPE_STRATEGIC         OpportunityType = 2
	OpportunityType_OPPORTUNITY_TYPE_RESOURCE          OpportunityType = 3
	OpportunityType_OPPORTUNITY_TYPE_THREAT_MITIGATION OpportunityType = 4
)

// Enum value maps for OpportunityType.
var (
	OpportunityType_name = map[int32]string{
		0: "OPPORTUNITY_TYPE_UNSPECIFIED",
		1: "OPPORTUNITY_TYPE_TACTICAL",
		2: "OPPORTUNITY_TYPE_STRATEGIC",
		3: "OPPORTUNITY_TYPE_RESOURCE",
		4: "OPPORTUNITY_TYPE_THREAT_MITIGATION",
	}
	OpportunityType_value = map[string]int32{
		"OPPORTUNITY_TYPE_UNSPECIFIED":       0,
		"OPPORTUNITY_TYPE_TACTICAL":          1,
		"OPPORTUNITY_TYPE_STRATEGIC":         2,
		"OPPORTUNITY_TYPE_RESOURCE":          3,
		"OPPORTUNITY_TYPE_THREAT_MITIGATION": 4,
	}
)

func (x OpportunityType) Enum() *OpportunityType {
	p := new(OpportunityType)
	*p = x
	return p
}

func (x OpportunityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpportunityType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intelligence_intelligence_proto_enumTypes[3].Descriptor()
}

func (OpportunityType) Type() protoreflect.EnumType {
	return &file_pb_intelligence_intelligence_proto_enumTypes[3]
}

func (x OpportunityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpportunityType.Descriptor instead.
func (OpportunityType) EnumDescriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{3}
}

type IntelCardStatus int32

const (
	IntelCardStatus_INTEL_CARD_STATUS_UNSPECIFIED    IntelCardStatus = 0
	IntelCardStatus_INTEL_CARD_STATUS_PENDING_REVIEW IntelCardStatus = 1
	IntelCardStatus_INTEL_CARD_STATUS_CONFIRMED      IntelCardStatus = 2
	IntelCardStatus_INTEL_CARD_STATUS_DISMISSED      IntelCardStatus = 3
)

// Enum value maps for IntelCardStatus.
var (
	IntelCardStatus_name = map[int32]string{
		0: "INTEL_CARD_STATUS_UNSPECIFIED",
		1: "INTEL_CARD_STATUS_PENDING_REVIEW",
		2: "INTEL_CARD_STATUS_CONFIRMED",
		3: "INTEL_CARD_STATUS_DISMISSED",
	}
	IntelCardStatus_value = map[string]int32{
		"INTEL_CARD_STATUS_UNSPECIFIED":    0,
		"INTEL_CARD_STATUS_PENDING_REVIEW": 1,
		"INTEL_CARD_STATUS_CONFIRMED":      2,
		"INTEL_CARD_STATUS_DISMISSED":      3,
	}
)

func (x IntelCardStatus) Enum() *IntelCardStatus {
	p := new(IntelCardStatus)
	*p = x
	return p
}

func (x IntelCardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntelCardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_intelligence_intelligence_proto_enumTypes[4].Descriptor()
}

func (IntelCardStatus) Type() protoreflect.EnumType {
	return &file_pb_intelligence_intelligence_proto_enumTypes[4]
}

func (x IntelCardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntelCardStatus.Descriptor instead.
func (IntelCardStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{4}
}

type QueryIntelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectType   SubjectType            `protobuf:"varint,2,opt,name=subject_type,json=subjectType,proto3,enum=jarvis.intelligence.SubjectType" json:"subject_type,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Depth         AnalysisDepth          `protobuf:"varint,4,opt,name=depth,proto3,enum=jarvis.intelligence.AnalysisDepth" json:"depth,omitempty"`
	DataSources   []string               `protobuf:"bytes,5,rep,name=data_sources,json=dataSources,proto3" json:"data_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIntelRequest) Reset() {
	*x = QueryIntelRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIntelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIntelRequest) ProtoMessage() {}

func (x *QueryIntelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIntelRequest.ProtoReflect.Descriptor instead.
func (*QueryIntelRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *QueryIntelRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *QueryIntelRequest) GetSubjectType() SubjectType {
	if x != nil {
		return x.SubjectType
	}
	return SubjectType_SUBJECT_TYPE_UNSPECIFIED
}

func (x *QueryIntelRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryIntelRequest) GetDepth() AnalysisDepth {
	if x != nil {
		return x.Depth
	}
	return AnalysisDepth_ANALYSIS_DEPTH_UNSPECIFIED
}

func (x *QueryIntelRequest) GetDataSources() []string {
	if x != nil {
		return x.DataSources
	}
	return nil
}

type IntelFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Fact          string                 `protobuf:"bytes,2,opt,name=fact,proto3" json:"fact,omitempty"`
	Reliability   float32                `protobuf:"fixed32,3,opt,name=reliability,proto3" json:"reliability,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntelFact) Reset() {
	*x = IntelFact{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelFact) ProtoMessage() {}

func (x *IntelFact) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelFact.ProtoReflect.Descriptor instead.
func (*IntelFact) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *IntelFact) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IntelFact) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

func (x *IntelFact) GetReliability() float32 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *IntelFact) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type QueryIntelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Facts           []*IntelFact           `protobuf:"bytes,4,rep,name=facts,proto3" json:"facts,omitempty"`
	RelatedSubjects []string               `protobuf:"bytes,5,rep,name=related_subjects,json=relatedSubjects,proto3" json:"related_subjects,omitempty"`
	Confidence      float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryIntelResponse) Reset() {
	*x = QueryIntelResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIntelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIntelResponse) ProtoMessage() {}

func (x *QueryIntelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIntelResponse.ProtoReflect.Descriptor instead.
func (*QueryIntelResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *QueryIntelResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *QueryIntelResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *QueryIntelResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *QueryIntelResponse) GetFacts() []*IntelFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *QueryIntelResponse) GetRelatedSubjects() []string {
	if x != nil {
		return x.RelatedSubjects
	}
	return nil
}

func (x *QueryIntelResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type AnalyzeArtifactRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ArtifactId          string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ScanData            []byte                 `protobuf:"bytes,3,opt,name=scan_data,json=scanData,proto3" json:"scan_data,omitempty"`
	ArtifactDescription string                 `protobuf:"bytes,4,opt,name=artifact_description,json=artifactDescription,proto3" json:"artifact_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyzeArtifactRequest) Reset() {
	*x = AnalyzeArtifactRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArtifactRequest) ProtoMessage() {}

func (x *AnalyzeArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArtifactRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeArtifactRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeArtifactRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyzeArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AnalyzeArtifactRequest) GetScanData() []byte {
	if x != nil {
		return x.ScanData
	}
	return nil
}

func (x *AnalyzeArtifactRequest) GetArtifactDescription() string {
	if x != nil {
		return x.ArtifactDescription
	}
	return ""
}

type AnalyzeArtifactResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ArtifactId           string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	CompositionSummary   string                 `protobuf:"bytes,3,opt,name=composition_summary,json=compositionSummary,proto3" json:"composition_summary,omitempty"`
	IsKnownTechnology    bool                   `protobuf:"varint,4,opt,name=is_known_technology,json=isKnownTechnology,proto3" json:"is_known_technology,omitempty"`
	IsPotentiallyHostile bool                   `protobuf:"varint,5,opt,name=is_potentially_hostile,json=isPotentiallyHostile,proto3" json:"is_potentially_hostile,omitempty"`
	Anomalies            []string               `protobuf:"bytes,6,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	ElementBreakdown     map[string]float64     `protobuf:"bytes,7,rep,name=element_breakdown,json=elementBreakdown,proto3" json:"element_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalyzeArtifactResponse) Reset() {
	*x = AnalyzeArtifactResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArtifactResponse) ProtoMessage() {}

func (x *AnalyzeArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArtifactResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeArtifactResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeArtifactResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyzeArtifactResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AnalyzeArtifactResponse) GetCompositionSummary() string {
	if x != nil {
		return x.CompositionSummary
	}
	return ""
}

func (x *AnalyzeArtifactResponse) GetIsKnownTechnology() bool {
	if x != nil {
		return x.IsKnownTechnology
	}
	return false
}

func (x *AnalyzeArtifactResponse) GetIsPotentiallyHostile() bool {
	if x != nil {
		return x.IsPotentiallyHostile
	}
	return false
}

func (x *AnalyzeArtifactResponse) GetAnomalies() []string {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

func (x *AnalyzeArtifactResponse) GetElementBreakdown() map[string]float64 {
	if x != nil {
		return x.ElementBreakdown
	}
	return nil
}

type CrossReferenceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectIds       []string               `protobuf:"bytes,2,rep,name=subject_ids,json=subjectIds,proto3" json:"subject_ids,omitempty"`
	RelationshipHint string                 `protobuf:"bytes,3,opt,name=relationship_hint,json=relationshipHint,proto3" json:"relationship_hint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CrossReferenceRequest) Reset() {
	*x = CrossReferenceRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossReferenceRequest) ProtoMessage() {}

func (x *CrossReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossReferenceRequest.ProtoReflect.Descriptor instead.
func (*CrossReferenceRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *CrossReferenceRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CrossReferenceRequest) GetSubjectIds() []string {
	if x != nil {
		return x.SubjectIds
	}
	return nil
}

func (x *CrossReferenceRequest) GetRelationshipHint() string {
	if x != nil {
		return x.RelationshipHint
	}
	return ""
}

type Relationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectA      string                 `protobuf:"bytes,1,opt,name=subject_a,json=subjectA,proto3" json:"subject_a,omitempty"`
	SubjectB      string                 `protobuf:"bytes,2,opt,name=subject_b,json=subjectB,proto3" json:"subject_b,omitempty"`
	RelType       string                 `protobuf:"bytes,3,opt,name=rel_type,json=relType,proto3" json:"rel_type,omitempty"`
	Strength      float32                `protobuf:"fixed32,4,opt,name=strength,proto3" json:"strength,omitempty"`
	Evidence      string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *Relationship) GetSubjectA() string {
	if x != nil {
		return x.SubjectA
	}
	return ""
}

func (x *Relationship) GetSubjectB() string {
	if x != nil {
		return x.SubjectB
	}
	return ""
}

func (x *Relationship) GetRelType() string {
	if x != nil {
		return x.RelType
	}
	return ""
}

func (x *Relationship) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Relationship) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type CrossReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Relationships []*Relationship        `protobuf:"bytes,2,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossReferenceResponse) Reset() {
	*x = CrossReferenceResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossReferenceResponse) ProtoMessage() {}

func (x *CrossReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossReferenceResponse.ProtoReflect.Descriptor instead.
func (*CrossReferenceResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *CrossReferenceResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CrossReferenceResponse) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type StreamIntelUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIntelUpdatesRequest) Reset() {
	*x = StreamIntelUpdatesRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIntelUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIntelUpdatesRequest) ProtoMessage() {}

func (x *StreamIntelUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIntelUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamIntelUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{8}
}

func (x *StreamIntelUpdatesRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StreamIntelUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Update        *QueryIntelResponse    `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIntelUpdatesResponse) Reset() {
	*x = StreamIntelUpdatesResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIntelUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIntelUpdatesResponse) ProtoMessage() {}

func (x *StreamIntelUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIntelUpdatesResponse.ProtoReflect.Descriptor instead.
func (*StreamIntelUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{9}
}

func (x *StreamIntelUpdatesResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamIntelUpdatesResponse) GetUpdate() *QueryIntelResponse {
	if x != nil {
		return x.Update
	}
	return nil
}

// RawSignal is an unprocessed piece of intelligence from any source.
type RawSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceType    SourceType             `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=jarvis.intelligence.SourceType" json:"source_type,omitempty"`
	RawContent    string                 `protobuf:"bytes,3,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	SourceUri     string                 `protobuf:"bytes,4,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"` // feed URL, filename, or empty for manual
	IngestedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawSignal) Reset() {
	*x = RawSignal{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawSignal) ProtoMessage() {}

func (x *RawSignal) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawSignal.ProtoReflect.Descriptor instead.
func (*RawSignal) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{10}
}

func (x *RawSignal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawSignal) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *RawSignal) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *RawSignal) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *RawSignal) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

// IntelCard is a structured intelligence opportunity produced by the FusionEngine.
type IntelCard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	OpportunityType OpportunityType        `protobuf:"varint,4,opt,name=opportunity_type,json=opportunityType,proto3,enum=jarvis.intelligence.OpportunityType" json:"opportunity_type,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	SuggestedAction string                 `protobuf:"bytes,6,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	Status          IntelCardStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=jarvis.intelligence.IntelCardStatus" json:"status,omitempty"`
	RawSignalIds    []string               `protobuf:"bytes,8,rep,name=raw_signal_ids,json=rawSignalIds,proto3" json:"raw_signal_ids,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IntelCard) Reset() {
	*x = IntelCard{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelCard) ProtoMessage() {}

func (x *IntelCard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelCard.ProtoReflect.Descriptor instead.
func (*IntelCard) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{11}
}

func (x *IntelCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IntelCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IntelCard) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *IntelCard) GetOpportunityType() OpportunityType {
	if x != nil {
		return x.OpportunityType
	}
	return OpportunityType_OPPORTUNITY_TYPE_UNSPECIFIED
}

func (x *IntelCard) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *IntelCard) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

func (x *IntelCard) GetStatus() IntelCardStatus {
	if x != nil {
		return x.Status
	}
	return IntelCardStatus_INTEL_CARD_STATUS_UNSPECIFIED
}

func (x *IntelCard) GetRawSignalIds() []string {
	if x != nil {
		return x.RawSignalIds
	}
	return nil
}

func (x *IntelCard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IntelCard) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type IngestSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SourceType    SourceType             `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=jarvis.intelligence.SourceType" json:"source_type,omitempty"`
	RawContent    string                 `protobuf:"bytes,3,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	SourceUri     string                 `protobuf:"bytes,4,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"` // optional — feed URL or filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSignalRequest) Reset() {
	*x = IngestSignalRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSignalRequest) ProtoMessage() {}

func (x *IngestSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSignalRequest.ProtoReflect.Descriptor instead.
func (*IngestSignalRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{12}
}

func (x *IngestSignalRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IngestSignalRequest) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *IngestSignalRequest) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *IngestSignalRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

type IngestSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Signal        *RawSignal             `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	Card          *IntelCard             `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"` // generated card; status PENDING_REVIEW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSignalResponse) Reset() {
	*x = IngestSignalResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSignalResponse) ProtoMessage() {}

func (x *IngestSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSignalResponse.ProtoReflect.Descriptor instead.
func (*IngestSignalResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{13}
}

func (x *IngestSignalResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IngestSignalResponse) GetSignal() *RawSignal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *IngestSignalResponse) GetCard() *IntelCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListIntelCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	StatusFilter  IntelCardStatus        `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=jarvis.intelligence.IntelCardStatus" json:"status_filter,omitempty"` // UNSPECIFIED = return all statuses
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntelCardsRequest) Reset() {
	*x = ListIntelCardsRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntelCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntelCardsRequest) ProtoMessage() {}

func (x *ListIntelCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntelCardsRequest.ProtoReflect.Descriptor instead.
func (*ListIntelCardsRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{14}
}

func (x *ListIntelCardsRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListIntelCardsRequest) GetStatusFilter() IntelCardStatus {
	if x != nil {
		return x.StatusFilter
	}
	return IntelCardStatus_INTEL_CARD_STATUS_UNSPECIFIED
}

func (x *ListIntelCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIntelCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListIntelCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Cards         []*IntelCard           `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntelCardsResponse) Reset() {
	*x = ListIntelCardsResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntelCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntelCardsResponse) ProtoMessage() {}

func (x *ListIntelCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntelCardsResponse.ProtoReflect.Descriptor instead.
func (*ListIntelCardsResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{15}
}

func (x *ListIntelCardsResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListIntelCardsResponse) GetCards() []*IntelCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListIntelCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListIntelCardsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ConfirmActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	NewStatus     IntelCardStatus        `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3,enum=jarvis.intelligence.IntelCardStatus" json:"new_status,omitempty"` // CONFIRMED or DISMISSED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmActionRequest) Reset() {
	*x = ConfirmActionRequest{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionRequest) ProtoMessage() {}

func (x *ConfirmActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionRequest.ProtoReflect.Descriptor instead.
func (*ConfirmActionRequest) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{16}
}

func (x *ConfirmActionRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ConfirmActionRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ConfirmActionRequest) GetNewStatus() IntelCardStatus {
	if x != nil {
		return x.NewStatus
	}
	return IntelCardStatus_INTEL_CARD_STATUS_UNSPECIFIED
}

type ConfirmActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Card          *IntelCard             `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmActionResponse) Reset() {
	*x = ConfirmActionResponse{}
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionResponse) ProtoMessage() {}

func (x *ConfirmActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_intelligence_intelligence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmActionResponse) Descriptor() ([]byte, []int) {
	return file_pb_intelligence_intelligence_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmActionResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ConfirmActionResponse) GetCard() *IntelCard {
	if x != nil {
		return x.Card
	}
	return nil
}

var File_pb_intelligence_intelligence_proto protoreflect.FileDescriptor

const file_pb_intelligence_intelligence_proto_rawDesc = "" +
	"\n" +
	"\"pb/intelligence/intelligence.proto\x12\x13jarvis.intelligence\x1a\x16pb/common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xfb\x01\n" +
	"\x11QueryIntelRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12C\n" +
	"\fsubject_type\x18\x02 \x01(\x0e2 .jarvis.intelligence.SubjectTypeR\vsubjectType\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x128\n" +
	"\x05depth\x18\x04 \x01(\x0e2\".jarvis.intelligence.AnalysisDepthR\x05depth\x12!\n" +
	"\fdata_sources\x18\x05 \x03(\tR\vdataSources\"\x96\x01\n" +
	"\tIntelFact\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04fact\x18\x02 \x01(\tR\x04fact\x12 \n" +
	"\vreliability\x18\x03 \x01(\x02R\vreliability\x12;\n" +
	"\vrecorded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"\xff\x01\n" +
	"\x12QueryIntelResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x124\n" +
	"\x05facts\x18\x04 \x03(\v2\x1e.jarvis.intelligence.IntelFactR\x05facts\x12)\n" +
	"\x10related_subjects\x18\x05 \x03(\tR\x0frelatedSubjects\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\"\xb9\x01\n" +
	"\x16AnalyzeArtifactRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x1b\n" +
	"\tscan_data\x18\x03 \x01(\fR\bscanData\x121\n" +
	"\x14artifact_description\x18\x04 \x01(\tR\x13artifactDescription\"\xd6\x03\n" +
	"\x17AnalyzeArtifactResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12/\n" +
	"\x13composition_summary\x18\x03 \x01(\tR\x12compositionSummary\x12.\n" +
	"\x13is_known_technology\x18\x04 \x01(\bR\x11isKnownTechnology\x124\n" +
	"\x16is_potentially_hostile\x18\x05 \x01(\bR\x14isPotentiallyHostile\x12\x1c\n" +
	"\tanomalies\x18\x06 \x03(\tR\tanomalies\x12o\n" +
	"\x11element_breakdown\x18\a \x03(\v2B.jarvis.intelligence.AnalyzeArtifactResponse.ElementBreakdownEntryR\x10elementBreakdown\x1aC\n" +
	"\x15ElementBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x95\x01\n" +
	"\x15CrossReferenceRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1f\n" +
	"\vsubject_ids\x18\x02 \x03(\tR\n" +
	"subjectIds\x12+\n" +
	"\x11relationship_hint\x18\x03 \x01(\tR\x10relationshipHint\"\x9b\x01\n" +
	"\fRelationship\x12\x1b\n" +
	"\tsubject_a\x18\x01 \x01(\tR\bsubjectA\x12\x1b\n" +
	"\tsubject_b\x18\x02 \x01(\tR\bsubjectB\x12\x19\n" +
	"\brel_type\x18\x03 \x01(\tR\arelType\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x02R\bstrength\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\"\x92\x01\n" +
	"\x16CrossReferenceResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12G\n" +
	"\rrelationships\x18\x02 \x03(\v2!.jarvis.intelligence.RelationshipR\rrelationships\"K\n" +
	"\x19StreamIntelUpdatesRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\"\x8e\x01\n" +
	"\x1aStreamIntelUpdatesResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12?\n" +
	"\x06update\x18\x02 \x01(\v2'.jarvis.intelligence.QueryIntelResponseR\x06update\"\xda\x01\n" +
	"\tRawSignal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x1f.jarvis.intelligence.SourceTypeR\n" +
	"sourceType\x12\x1f\n" +
	"\vraw_content\x18\x03 \x01(\tR\n" +
	"rawContent\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x04 \x01(\tR\tsourceUri\x12;\n" +
	"\vingested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt\"\xcc\x03\n" +
	"\tIntelCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12O\n" +
	"\x10opportunity_type\x18\x04 \x01(\x0e2$.jarvis.intelligence.OpportunityTypeR\x0fopportunityType\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x12)\n" +
	"\x10suggested_action\x18\x06 \x01(\tR\x0fsuggestedAction\x12<\n" +
	"\x06status\x18\a \x01(\x0e2$.jarvis.intelligence.IntelCardStatusR\x06status\x12$\n" +
	"\x0eraw_signal_ids\x18\b \x03(\tR\frawSignalIds\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc7\x01\n" +
	"\x13IngestSignalRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12@\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x1f.jarvis.intelligence.SourceTypeR\n" +
	"sourceType\x12\x1f\n" +
	"\vraw_content\x18\x03 \x01(\tR\n" +
	"rawContent\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x04 \x01(\tR\tsourceUri\"\xb3\x01\n" +
	"\x14IngestSignalResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x126\n" +
	"\x06signal\x18\x02 \x01(\v2\x1e.jarvis.intelligence.RawSignalR\x06signal\x122\n" +
	"\x04card\x18\x03 \x01(\v2\x1e.jarvis.intelligence.IntelCardR\x04card\"\xce\x01\n" +
	"\x15ListIntelCardsRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12I\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2$.jarvis.intelligence.IntelCardStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xc8\x01\n" +
	"\x16ListIntelCardsResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x124\n" +
	"\x05cards\x18\x02 \x03(\v2\x1e.jarvis.intelligence.IntelCardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\xa4\x01\n" +
	"\x14ConfirmActionRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12C\n" +
	"\n" +
	"new_status\x18\x03 \x01(\x0e2$.jarvis.intelligence.IntelCardStatusR\tnewStatus\"|\n" +
	"\x15ConfirmActionResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x122\n" +
	"\x04card\x18\x02 \x01(\v2\x1e.jarvis.intelligence.IntelCardR\x04card*\xb6\x01\n" +
	"\vSubjectType\x12\x1c\n" +
	"\x18SUBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SUBJECT_TYPE_PERSON\x10\x01\x12\x1d\n" +
	"\x19SUBJECT_TYPE_ORGANIZATION\x10\x02\x12\x1b\n" +
	"\x17SUBJECT_TYPE_TECHNOLOGY\x10\x03\x12\x19\n" +
	"\x15SUBJECT_TYPE_LOCATION\x10\x04\x12\x19\n" +
	"\x15SUBJECT_TYPE_ARTIFACT\x10\x05*e\n" +
	"\rAnalysisDepth\x12\x1e\n" +
	"\x1aANALYSIS_DEPTH_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ANALYSIS_DEPTH_STANDARD\x10\x01\x12\x17\n" +
	"\x13ANALYSIS_DEPTH_DEEP\x10\x02*s\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SOURCE_TYPE_MANUAL\x10\x01\x12\x13\n" +
	"\x0fSOURCE_TYPE_RSS\x10\x02\x12\x1b\n" +
	"\x17SOURCE_TYPE_FILE_UPLOAD\x10\x03*\xb9\x01\n" +
	"\x0fOpportunityType\x12 \n" +
	"\x1cOPPORTUNITY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OPPORTUNITY_TYPE_TACTICAL\x10\x01\x12\x1e\n" +
	"\x1aOPPORTUNITY_TYPE_STRATEGIC\x10\x02\x12\x1d\n" +
	"\x19OPPORTUNITY_TYPE_RESOURCE\x10\x03\x12&\n" +
	"\"OPPORTUNITY_TYPE_THREAT_MITIGATION\x10\x04*\x9c\x01\n" +
	"\x0fIntelCardStatus\x12!\n" +
	"\x1dINTEL_CARD_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" INTEL_CARD_STATUS_PENDING_REVIEW\x10\x01\x12\x1f\n" +
	"\x1bINTEL_CARD_STATUS_CONFIRMED\x10\x02\x12\x1f\n" +
	"\x1bINTEL_CARD_STATUS_DISMISSED\x10\x032\xc2\a\n" +
	"\x13IntelligenceService\x12y\n" +
	"\n" +
	"QueryIntel\x12&.jarvis.intelligence.QueryIntelRequest\x1a'.jarvis.intelligence.QueryIntelResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/intel/query\x12\x8b\x01\n" +
	"\x0fAnalyzeArtifact\x12+.jarvis.intelligence.AnalyzeArtifactRequest\x1a,.jarvis.intelligence.AnalyzeArtifactResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/intel/artifact\x12\x88\x01\n" +
	"\x0eCrossReference\x12*.jarvis.intelligence.CrossReferenceRequest\x1a+.jarvis.intelligence.CrossReferenceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/intel/crossref\x12w\n" +
	"\x12StreamIntelUpdates\x12..jarvis.intelligence.StreamIntelUpdatesRequest\x1a/.jarvis.intelligence.StreamIntelUpdatesResponse0\x01\x12\x81\x01\n" +
	"\fIngestSignal\x12(.jarvis.intelligence.IngestSignalRequest\x1a).jarvis.intelligence.IngestSignalResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/intel/signals\x12\x82\x01\n" +
	"\x0eListIntelCards\x12*.jarvis.intelligence.ListIntelCardsRequest\x1a+.jarvis.intelligence.ListIntelCardsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/intel/cards\x12\x94\x01\n" +
	"\rConfirmAction\x12).jarvis.intelligence.ConfirmActionRequest\x1a*.jarvis.intelligence.ConfirmActionResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/intel/cards/{card_id}/confirmB\xca\x01\n" +
	"\x17com.jarvis.intelligenceB\x11IntelligenceProtoP\x01Z/github.com/rkrimper1/jarvis/api/pb/intelligence\xa2\x02\x03JIX\xaa\x02\x13Jarvis.Intelligence\xca\x02\x13Jarvis\\Intelligence\xe2\x02\x1fJarvis\\Intelligence\\GPBMetadata\xea\x02\x14Jarvis::Intelligenceb\x06proto3"

var (
	file_pb_intelligence_intelligence_proto_rawDescOnce sync.Once
	file_pb_intelligence_intelligence_proto_rawDescData []byte
)

func file_pb_intelligence_intelligence_proto_rawDescGZIP() []byte {
	file_pb_intelligence_intelligence_proto_rawDescOnce.Do(func() {
		file_pb_intelligence_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_intelligence_intelligence_proto_rawDesc), len(file_pb_intelligence_intelligence_proto_rawDesc)))
	})
	return file_pb_intelligence_intelligence_proto_rawDescData
}

var file_pb_intelligence_intelligence_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_intelligence_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pb_intelligence_intelligence_proto_goTypes = []any{
	(SubjectType)(0),                   // 0: jarvis.intelligence.SubjectType
	(AnalysisDepth)(0),                 // 1: jarvis.intelligence.AnalysisDepth
	(SourceType)(0),                    // 2: jarvis.intelligence.SourceType
	(OpportunityType)(0),               // 3: jarvis.intelligence.OpportunityType
	(IntelCardStatus)(0),               // 4: jarvis.intelligence.IntelCardStatus
	(*QueryIntelRequest)(nil),          // 5: jarvis.intelligence.QueryIntelRequest
	(*IntelFact)(nil),                  // 6: jarvis.intelligence.IntelFact
	(*QueryIntelResponse)(nil),         // 7: jarvis.intelligence.QueryIntelResponse
	(*AnalyzeArtifactRequest)(nil),     // 8: jarvis.intelligence.AnalyzeArtifactRequest
	(*AnalyzeArtifactResponse)(nil),    // 9: jarvis.intelligence.AnalyzeArtifactResponse
	(*CrossReferenceRequest)(nil),      // 10: jarvis.intelligence.CrossReferenceRequest
	(*Relationship)(nil),               // 11: jarvis.intelligence.Relationship
	(*CrossReferenceResponse)(nil),     // 12: jarvis.intelligence.CrossReferenceResponse
	(*StreamIntelUpdatesRequest)(nil),  // 13: jarvis.intelligence.StreamIntelUpdatesRequest
	(*StreamIntelUpdatesResponse)(nil), // 14: jarvis.intelligence.StreamIntelUpdatesResponse
	(*RawSignal)(nil),                  // 15: jarvis.intelligence.RawSignal
	(*IntelCard)(nil),                  // 16: jarvis.intelligence.IntelCard
	(*IngestSignalRequest)(nil),        // 17: jarvis.intelligence.IngestSignalRequest
	(*IngestSignalResponse)(nil),       // 18: jarvis.intelligence.IngestSignalResponse
	(*ListIntelCardsRequest)(nil),      // 19: jarvis.intelligence.ListIntelCardsRequest
	(*ListIntelCardsResponse)(nil),     // 20: jarvis.intelligence.ListIntelCardsResponse
	(*ConfirmActionRequest)(nil),       // 21: jarvis.intelligence.ConfirmActionRequest
	(*ConfirmActionResponse)(nil),      // 22: jarvis.intelligence.ConfirmActionResponse
	nil,                                // 23: jarvis.intelligence.AnalyzeArtifactResponse.ElementBreakdownEntry
	(*common.RequestMeta)(nil),         // 24: jarvis.common.RequestMeta
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
	(*common.ResponseMeta)(nil),        // 26: jarvis.common.ResponseMeta
}
var file_pb_intelligence_intelligence_proto_depIdxs = []int32{
	24, // 0: jarvis.intelligence.QueryIntelRequest.meta:type_name -> jarvis.common.RequestMeta
	0,  // 1: jarvis.intelligence.QueryIntelRequest.subject_type:type_name -> jarvis.intelligence.SubjectType
	1,  // 2: jarvis.intelligence.QueryIntelRequest.depth:type_name -> jarvis.intelligence.AnalysisDepth
	25, // 3: jarvis.intelligence.IntelFact.recorded_at:type_name -> google.protobuf.Timestamp
	26, // 4: jarvis.intelligence.QueryIntelResponse.meta:type_name -> jarvis.common.ResponseMeta
	6,  // 5: jarvis.intelligence.QueryIntelResponse.facts:type_name -> jarvis.intelligence.IntelFact
	24, // 6: jarvis.intelligence.AnalyzeArtifactRequest.meta:type_name -> jarvis.common.RequestMeta
	26, // 7: jarvis.intelligence.AnalyzeArtifactResponse.meta:type_name -> jarvis.common.ResponseMeta
	23, // 8: jarvis.intelligence.AnalyzeArtifactResponse.element_breakdown:type_name -> jarvis.intelligence.AnalyzeArtifactResponse.ElementBreakdownEntry
	24, // 9: jarvis.intelligence.CrossReferenceRequest.meta:type_name -> jarvis.common.RequestMeta
	26, // 10: jarvis.intelligence.CrossReferenceResponse.meta:type_name -> jarvis.common.ResponseMeta
	11, // 11: jarvis.intelligence.CrossReferenceResponse.relationships:type_name -> jarvis.intelligence.Relationship
	24, // 12: jarvis.intelligence.StreamIntelUpdatesRequest.meta:type_name -> jarvis.common.RequestMeta
	26, // 13: jarvis.intelligence.StreamIntelUpdatesResponse.meta:type_name -> jarvis.common.ResponseMeta
	7,  // 14: jarvis.intelligence.StreamIntelUpdatesResponse.update:type_name -> jarvis.intelligence.QueryIntelResponse
	2,  // 15: jarvis.intelligence.RawSignal.source_type:type_name -> jarvis.intelligence.SourceType
	25, // 16: jarvis.intelligence.RawSignal.ingested_at:type_name -> google.protobuf.Timestamp
	3,  // 17: jarvis.intelligence.IntelCard.opportunity_type:type_name -> jarvis.intelligence.OpportunityType
	4,  // 18: jarvis.intelligence.IntelCard.status:type_name -> jarvis.intelligence.IntelCardStatus
	25, // 19: jarvis.intelligence.IntelCard.created_at:type_name -> google.protobuf.Timestamp
	25, // 20: jarvis.intelligence.IntelCard.updated_at:type_name -> google.protobuf.Timestamp
	24, // 21: jarvis.intelligence.IngestSignalRequest.meta:type_name -> jarvis.common.RequestMeta
	2,  // 22: jarvis.intelligence.IngestSignalRequest.source_type:type_name -> jarvis.intelligence.SourceType
	26, // 23: jarvis.intelligence.IngestSignalResponse.meta:type_name -> jarvis.common.ResponseMeta
	15, // 24: jarvis.intelligence.IngestSignalResponse.signal:type_name -> jarvis.intelligence.RawSignal
	16, // 25: jarvis.intelligence.IngestSignalResponse.card:type_name -> jarvis.intelligence.IntelCard
	24, // 26: jarvis.intelligence.ListIntelCardsRequest.meta:type_name -> jarvis.common.RequestMeta
	4,  // 27: jarvis.intelligence.ListIntelCardsRequest.status_filter:type_name -> jarvis.intelligence.IntelCardStatus
	26, // 28: jarvis.intelligence.ListIntelCardsResponse.meta:type_name -> jarvis.common.ResponseMeta
	16, // 29: jarvis.intelligence.ListIntelCardsResponse.cards:type_name -> jarvis.intelligence.IntelCard
	24, // 30: jarvis.intelligence.ConfirmActionRequest.meta:type_name -> jarvis.common.RequestMeta
	4,  // 31: jarvis.intelligence.ConfirmActionRequest.new_status:type_name -> jarvis.intelligence.IntelCardStatus
	26, // 32: jarvis.intelligence.ConfirmActionResponse.meta:type_name -> jarvis.common.ResponseMeta
	16, // 33: jarvis.intelligence.ConfirmActionResponse.card:type_name -> jarvis.intelligence.IntelCard
	5,  // 34: jarvis.intelligence.IntelligenceService.QueryIntel:input_type -> jarvis.intelligence.QueryIntelRequest
	8,  // 35: jarvis.intelligence.IntelligenceService.AnalyzeArtifact:input_type -> jarvis.intelligence.AnalyzeArtifactRequest
	10, // 36: jarvis.intelligence.IntelligenceService.CrossReference:input_type -> jarvis.intelligence.CrossReferenceRequest
	13, // 37: jarvis.intelligence.IntelligenceService.StreamIntelUpdates:input_type -> jarvis.intelligence.StreamIntelUpdatesRequest
	17, // 38: jarvis.intelligence.IntelligenceService.IngestSignal:input_type -> jarvis.intelligence.IngestSignalRequest
	19, // 39: jarvis.intelligence.IntelligenceService.ListIntelCards:input_type -> jarvis.intelligence.ListIntelCardsRequest
	21, // 40: jarvis.intelligence.IntelligenceService.ConfirmAction:input_type -> jarvis.intelligence.ConfirmActionRequest
	7,  // 41: jarvis.intelligence.IntelligenceService.QueryIntel:output_type -> jarvis.intelligence.QueryIntelResponse
	9,  // 42: jarvis.intelligence.IntelligenceService.AnalyzeArtifact:output_type -> jarvis.intelligence.AnalyzeArtifactResponse
	12, // 43: jarvis.intelligence.IntelligenceService.CrossReference:output_type -> jarvis.intelligence.CrossReferenceResponse
	14, // 44: jarvis.intelligence.IntelligenceService.StreamIntelUpdates:output_type -> jarvis.intelligence.StreamIntelUpdatesResponse
	18, // 45: jarvis.intelligence.IntelligenceService.IngestSignal:output_type -> jarvis.intelligence.IngestSignalResponse
	20, // 46: jarvis.intelligence.IntelligenceService.ListIntelCards:output_type -> jarvis.intelligence.ListIntelCardsResponse
	22, // 47: jarvis.intelligence.IntelligenceService.ConfirmAction:output_type -> jarvis.intelligence.ConfirmActionResponse
	41, // [41:48] is the sub-list for method output_type
	34, // [34:41] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pb_intelligence_intelligence_proto_init() }
func file_pb_intelligence_intelligence_proto_init() {
	if File_pb_intelligence_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_intelligence_intelligence_proto_rawDesc), len(file_pb_intelligence_intelligence_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_intelligence_intelligence_proto_goTypes,
		DependencyIndexes: file_pb_intelligence_intelligence_proto_depIdxs,
		EnumInfos:         file_pb_intelligence_intelligence_proto_enumTypes,
		MessageInfos:      file_pb_intelligence_intelligence_proto_msgTypes,
	}.Build()
	File_pb_intelligence_intelligence_proto = out.File
	file_pb_intelligence_intelligence_proto_goTypes = nil
	file_pb_intelligence_intelligence_proto_depIdxs = nil
}
