// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/business/business.proto

package business

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 3
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_DONE",
		4: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_DONE":        3,
		"TASK_STATUS_CANCELLED":   4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_business_business_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pb_business_business_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{0}
}

type MessageChannel int32

const (
	MessageChannel_MESSAGE_CHANNEL_UNSPECIFIED MessageChannel = 0
	MessageChannel_MESSAGE_CHANNEL_EMAIL       MessageChannel = 1
	MessageChannel_MESSAGE_CHANNEL_SMS         MessageChannel = 2
	MessageChannel_MESSAGE_CHANNEL_SLACK       MessageChannel = 3
	MessageChannel_MESSAGE_CHANNEL_SECURE      MessageChannel = 4
)

// Enum value maps for MessageChannel.
var (
	MessageChannel_name = map[int32]string{
		0: "MESSAGE_CHANNEL_UNSPECIFIED",
		1: "MESSAGE_CHANNEL_EMAIL",
		2: "MESSAGE_CHANNEL_SMS",
		3: "MESSAGE_CHANNEL_SLACK",
		4: "MESSAGE_CHANNEL_SECURE",
	}
	MessageChannel_value = map[string]int32{
		"MESSAGE_CHANNEL_UNSPECIFIED": 0,
		"MESSAGE_CHANNEL_EMAIL":       1,
		"MESSAGE_CHANNEL_SMS":         2,
		"MESSAGE_CHANNEL_SLACK":       3,
		"MESSAGE_CHANNEL_SECURE":      4,
	}
)

func (x MessageChannel) Enum() *MessageChannel {
	p := new(MessageChannel)
	*p = x
	return p
}

func (x MessageChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_business_business_proto_enumTypes[1].Descriptor()
}

func (MessageChannel) Type() protoreflect.EnumType {
	return &file_pb_business_business_proto_enumTypes[1]
}

func (x MessageChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageChannel.Descriptor instead.
func (MessageChannel) EnumDescriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{1}
}

type ScheduledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,4,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	Status        TaskStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=jarvis.business.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledEvent) Reset() {
	*x = ScheduledEvent{}
	mi := &file_pb_business_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledEvent) ProtoMessage() {}

func (x *ScheduledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledEvent.ProtoReflect.Descriptor instead.
func (*ScheduledEvent) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ScheduledEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduledEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ScheduledEvent) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *ScheduledEvent) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScheduledEvent) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScheduledEvent) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type ScheduleEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,5,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	HighPriority  bool                   `protobuf:"varint,8,opt,name=high_priority,json=highPriority,proto3" json:"high_priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEventRequest) Reset() {
	*x = ScheduleEventRequest{}
	mi := &file_pb_business_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEventRequest) ProtoMessage() {}

func (x *ScheduleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEventRequest.ProtoReflect.Descriptor instead.
func (*ScheduleEventRequest) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleEventRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScheduleEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduleEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduleEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ScheduleEventRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *ScheduleEventRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScheduleEventRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScheduleEventRequest) GetHighPriority() bool {
	if x != nil {
		return x.HighPriority
	}
	return false
}

type ScheduleEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Conflicts     []string               `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	AutoResolved  bool                   `protobuf:"varint,4,opt,name=auto_resolved,json=autoResolved,proto3" json:"auto_resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEventResponse) Reset() {
	*x = ScheduleEventResponse{}
	mi := &file_pb_business_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEventResponse) ProtoMessage() {}

func (x *ScheduleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEventResponse.ProtoReflect.Descriptor instead.
func (*ScheduleEventResponse) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleEventResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScheduleEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ScheduleEventResponse) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *ScheduleEventResponse) GetAutoResolved() bool {
	if x != nil {
		return x.AutoResolved
	}
	return false
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_pb_business_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{3}
}

func (x *GetScheduleRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetScheduleRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetScheduleRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetScheduleRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Events        []*ScheduledEvent      `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_pb_business_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{4}
}

func (x *GetScheduleResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetScheduleResponse) GetEvents() []*ScheduledEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,4,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Due           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due,proto3" json:"due,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_pb_business_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetDue() *timestamppb.Timestamp {
	if x != nil {
		return x.Due
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=jarvis.business.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_pb_business_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Recipients    []string               `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Channel       MessageChannel         `protobuf:"varint,5,opt,name=channel,proto3,enum=jarvis.business.MessageChannel" json:"channel,omitempty"`
	Encrypt       bool                   `protobuf:"varint,6,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pb_business_business_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SendMessageRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendMessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendMessageRequest) GetChannel() MessageChannel {
	if x != nil {
		return x.Channel
	}
	return MessageChannel_MESSAGE_CHANNEL_UNSPECIFIED
}

func (x *SendMessageRequest) GetEncrypt() bool {
	if x != nil {
		return x.Encrypt
	}
	return false
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeliveredTo   []string               `protobuf:"bytes,3,rep,name=delivered_to,json=deliveredTo,proto3" json:"delivered_to,omitempty"`
	FailedTo      []string               `protobuf:"bytes,4,rep,name=failed_to,json=failedTo,proto3" json:"failed_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_pb_business_business_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetDeliveredTo() []string {
	if x != nil {
		return x.DeliveredTo
	}
	return nil
}

func (x *SendMessageResponse) GetFailedTo() []string {
	if x != nil {
		return x.FailedTo
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReportType    string                 `protobuf:"bytes,2,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Filters       []string               `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_pb_business_business_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateReportRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GenerateReportRequest) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *GenerateReportRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GenerateReportRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GenerateReportRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	ReportData    []byte                 `protobuf:"bytes,4,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_pb_business_business_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_business_business_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_pb_business_business_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateReportResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GenerateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *GenerateReportResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GenerateReportResponse) GetReportData() []byte {
	if x != nil {
		return x.ReportData
	}
	return nil
}

func (x *GenerateReportResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_pb_business_business_proto protoreflect.FileDescriptor

const file_pb_business_business_proto_rawDesc = "" +
	"\n" +
	"\x1apb/business/business.proto\x12\x0fjarvis.business\x1a\x16pb/common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x90\x02\n" +
	"\x0eScheduledEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\x04 \x03(\tR\tattendees\x120\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.jarvis.business.TaskStatusR\x06status\"\xbd\x02\n" +
	"\x14ScheduleEventRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\x05 \x03(\tR\tattendees\x120\n" +
	"\x05start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12#\n" +
	"\rhigh_priority\x18\b \x01(\bR\fhighPriority\"\xa6\x01\n" +
	"\x15ScheduleEventResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1c\n" +
	"\tconflicts\x18\x03 \x03(\tR\tconflicts\x12#\n" +
	"\rauto_resolved\x18\x04 \x01(\bR\fautoResolved\"\xbf\x01\n" +
	"\x12GetScheduleRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\x7f\n" +
	"\x13GetScheduleResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x127\n" +
	"\x06events\x18\x02 \x03(\v2\x1f.jarvis.business.ScheduledEventR\x06events\"\xe6\x01\n" +
	"\x11CreateTaskRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassignee_id\x18\x04 \x01(\tR\n" +
	"assigneeId\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12,\n" +
	"\x03due\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03due\"\x93\x01\n" +
	"\x12CreateTaskResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.jarvis.business.TaskStatusR\x06status\"\xe7\x01\n" +
	"\x12SendMessageRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1e\n" +
	"\n" +
	"recipients\x18\x02 \x03(\tR\n" +
	"recipients\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x129\n" +
	"\achannel\x18\x05 \x01(\x0e2\x1f.jarvis.business.MessageChannelR\achannel\x12\x18\n" +
	"\aencrypt\x18\x06 \x01(\bR\aencrypt\"\xa5\x01\n" +
	"\x13SendMessageResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fdelivered_to\x18\x03 \x03(\tR\vdeliveredTo\x12\x1b\n" +
	"\tfailed_to\x18\x04 \x03(\tR\bfailedTo\"\xde\x01\n" +
	"\x15GenerateReportRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1f\n" +
	"\vreport_type\x18\x02 \x01(\tR\n" +
	"reportType\x12\x18\n" +
	"\afilters\x18\x03 \x03(\tR\afilters\x12.\n" +
	"\x04from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xb9\x01\n" +
	"\x16GenerateReportResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1f\n" +
	"\vreport_data\x18\x04 \x01(\fR\n" +
	"reportData\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format*\x90\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x04*\x9c\x01\n" +
	"\x0eMessageChannel\x12\x1f\n" +
	"\x1bMESSAGE_CHANNEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MESSAGE_CHANNEL_EMAIL\x10\x01\x12\x17\n" +
	"\x13MESSAGE_CHANNEL_SMS\x10\x02\x12\x19\n" +
	"\x15MESSAGE_CHANNEL_SLACK\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_CHANNEL_SECURE\x10\x042\x95\x05\n" +
	"\x12BusinessOpsService\x12\x80\x01\n" +
	"\rScheduleEvent\x12%.jarvis.business.ScheduleEventRequest\x1a&.jarvis.business.ScheduleEventResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/business/schedule\x12\x84\x01\n" +
	"\vGetSchedule\x12#.jarvis.business.GetScheduleRequest\x1a$.jarvis.business.GetScheduleResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/business/schedule/{subject_id}\x12t\n" +
	"\n" +
	"CreateTask\x12\".jarvis.business.CreateTaskRequest\x1a#.jarvis.business.CreateTaskResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/business/tasks\x12z\n" +
	"\vSendMessage\x12#.jarvis.business.SendMessageRequest\x1a$.jarvis.business.SendMessageResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/business/messages\x12\x82\x01\n" +
	"\x0eGenerateReport\x12&.jarvis.business.GenerateReportRequest\x1a'.jarvis.business.GenerateReportResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/business/reportsB\xae\x01\n" +
	"\x13com.jarvis.businessB\rBusinessProtoP\x01Z+github.com/rkrimper1/jarvis/api/pb/business\xa2\x02\x03JBX\xaa\x02\x0fJarvis.Business\xca\x02\x0fJarvis\\Business\xe2\x02\x1bJarvis\\Business\\GPBMetadata\xea\x02\x10Jarvis::Businessb\x06proto3"

var (
	file_pb_business_business_proto_rawDescOnce sync.Once
	file_pb_business_business_proto_rawDescData []byte
)

func file_pb_business_business_proto_rawDescGZIP() []byte {
	file_pb_business_business_proto_rawDescOnce.Do(func() {
		file_pb_business_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_business_business_proto_rawDesc), len(file_pb_business_business_proto_rawDesc)))
	})
	return file_pb_business_business_proto_rawDescData
}

var file_pb_business_business_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_business_business_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_business_business_proto_goTypes = []any{
	(TaskStatus)(0),                // 0: jarvis.business.TaskStatus
	(MessageChannel)(0),            // 1: jarvis.business.MessageChannel
	(*ScheduledEvent)(nil),         // 2: jarvis.business.ScheduledEvent
	(*ScheduleEventRequest)(nil),   // 3: jarvis.business.ScheduleEventRequest
	(*ScheduleEventResponse)(nil),  // 4: jarvis.business.ScheduleEventResponse
	(*GetScheduleRequest)(nil),     // 5: jarvis.business.GetScheduleRequest
	(*GetScheduleResponse)(nil),    // 6: jarvis.business.GetScheduleResponse
	(*CreateTaskRequest)(nil),      // 7: jarvis.business.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 8: jarvis.business.CreateTaskResponse
	(*SendMessageRequest)(nil),     // 9: jarvis.business.SendMessageRequest
	(*SendMessageResponse)(nil),    // 10: jarvis.business.SendMessageResponse
	(*GenerateReportRequest)(nil),  // 11: jarvis.business.GenerateReportRequest
	(*GenerateReportResponse)(nil), // 12: jarvis.business.GenerateReportResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*common.RequestMeta)(nil),     // 14: jarvis.common.RequestMeta
	(*common.ResponseMeta)(nil),    // 15: jarvis.common.ResponseMeta
}
var file_pb_business_business_proto_depIdxs = []int32{
	13, // 0: jarvis.business.ScheduledEvent.start:type_name -> google.protobuf.Timestamp
	13, // 1: jarvis.business.ScheduledEvent.end:type_name -> google.protobuf.Timestamp
	0,  // 2: jarvis.business.ScheduledEvent.status:type_name -> jarvis.business.TaskStatus
	14, // 3: jarvis.business.ScheduleEventRequest.meta:type_name -> jarvis.common.RequestMeta
	13, // 4: jarvis.business.ScheduleEventRequest.start:type_name -> google.protobuf.Timestamp
	13, // 5: jarvis.business.ScheduleEventRequest.end:type_name -> google.protobuf.Timestamp
	15, // 6: jarvis.business.ScheduleEventResponse.meta:type_name -> jarvis.common.ResponseMeta
	14, // 7: jarvis.business.GetScheduleRequest.meta:type_name -> jarvis.common.RequestMeta
	13, // 8: jarvis.business.GetScheduleRequest.from:type_name -> google.protobuf.Timestamp
	13, // 9: jarvis.business.GetScheduleRequest.to:type_name -> google.protobuf.Timestamp
	15, // 10: jarvis.business.GetScheduleResponse.meta:type_name -> jarvis.common.ResponseMeta
	2,  // 11: jarvis.business.GetScheduleResponse.events:type_name -> jarvis.business.ScheduledEvent
	14, // 12: jarvis.business.CreateTaskRequest.meta:type_name -> jarvis.common.RequestMeta
	13, // 13: jarvis.business.CreateTaskRequest.due:type_name -> google.protobuf.Timestamp
	15, // 14: jarvis.business.CreateTaskResponse.meta:type_name -> jarvis.common.ResponseMeta
	0,  // 15: jarvis.business.CreateTaskResponse.status:type_name -> jarvis.business.TaskStatus
	14, // 16: jarvis.business.SendMessageRequest.meta:type_name -> jarvis.common.RequestMeta
	1,  // 17: jarvis.business.SendMessageRequest.channel:type_name -> jarvis.business.MessageChannel
	15, // 18: jarvis.business.SendMessageResponse.meta:type_name -> jarvis.common.ResponseMeta
	14, // 19: jarvis.business.GenerateReportRequest.meta:type_name -> jarvis.common.RequestMeta
	13, // 20: jarvis.business.GenerateReportRequest.from:type_name -> google.protobuf.Timestamp
	13, // 21: jarvis.business.GenerateReportRequest.to:type_name -> google.protobuf.Timestamp
	15, // 22: jarvis.business.GenerateReportResponse.meta:type_name -> jarvis.common.ResponseMeta
	3,  // 23: jarvis.business.BusinessOpsService.ScheduleEvent:input_type -> jarvis.business.ScheduleEventRequest
	5,  // 24: jarvis.business.BusinessOpsService.GetSchedule:input_type -> jarvis.business.GetScheduleRequest
	7,  // 25: jarvis.business.BusinessOpsService.CreateTask:input_type -> jarvis.business.CreateTaskRequest
	9,  // 26: jarvis.business.BusinessOpsService.SendMessage:input_type -> jarvis.business.SendMessageRequest
	11, // 27: jarvis.business.BusinessOpsService.GenerateReport:input_type -> jarvis.business.GenerateReportRequest
	4,  // 28: jarvis.business.BusinessOpsService.ScheduleEvent:output_type -> jarvis.business.ScheduleEventResponse
	6,  // 29: jarvis.business.BusinessOpsService.GetSchedule:output_type -> jarvis.business.GetScheduleResponse
	8,  // 30: jarvis.business.BusinessOpsService.CreateTask:output_type -> jarvis.business.CreateTaskResponse
	10, // 31: jarvis.business.BusinessOpsService.SendMessage:output_type -> jarvis.business.SendMessageResponse
	12, // 32: jarvis.business.BusinessOpsService.GenerateReport:output_type -> jarvis.business.GenerateReportResponse
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pb_business_business_proto_init() }
func file_pb_business_business_proto_init() {
	if File_pb_business_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_business_business_proto_rawDesc), len(file_pb_business_business_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_business_business_proto_goTypes,
		DependencyIndexes: file_pb_business_business_proto_depIdxs,
		EnumInfos:         file_pb_business_business_proto_enumTypes,
		MessageInfos:      file_pb_business_business_proto_msgTypes,
	}.Build()
	File_pb_business_business_proto = out.File
	file_pb_business_business_proto_goTypes = nil
	file_pb_business_business_proto_depIdxs = nil
}
