// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: business/business.proto

package business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusinessOpsService_ScheduleEvent_FullMethodName  = "/jarvis.business.BusinessOpsService/ScheduleEvent"
	BusinessOpsService_GetSchedule_FullMethodName    = "/jarvis.business.BusinessOpsService/GetSchedule"
	BusinessOpsService_CreateTask_FullMethodName     = "/jarvis.business.BusinessOpsService/CreateTask"
	BusinessOpsService_SendMessage_FullMethodName    = "/jarvis.business.BusinessOpsService/SendMessage"
	BusinessOpsService_GenerateReport_FullMethodName = "/jarvis.business.BusinessOpsService/GenerateReport"
)

// BusinessOpsServiceClient is the client API for BusinessOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessOpsServiceClient interface {
	ScheduleEvent(ctx context.Context, in *ScheduleEventRequest, opts ...grpc.CallOption) (*ScheduleEventResponse, error)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error)
}

type businessOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessOpsServiceClient(cc grpc.ClientConnInterface) BusinessOpsServiceClient {
	return &businessOpsServiceClient{cc}
}

func (c *businessOpsServiceClient) ScheduleEvent(ctx context.Context, in *ScheduleEventRequest, opts ...grpc.CallOption) (*ScheduleEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleEventResponse)
	err := c.cc.Invoke(ctx, BusinessOpsService_ScheduleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessOpsServiceClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, BusinessOpsService_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessOpsServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, BusinessOpsService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessOpsServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, BusinessOpsService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessOpsServiceClient) GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateReportResponse)
	err := c.cc.Invoke(ctx, BusinessOpsService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessOpsServiceServer is the server API for BusinessOpsService service.
// All implementations must embed UnimplementedBusinessOpsServiceServer
// for forward compatibility.
type BusinessOpsServiceServer interface {
	ScheduleEvent(context.Context, *ScheduleEventRequest) (*ScheduleEventResponse, error)
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error)
	mustEmbedUnimplementedBusinessOpsServiceServer()
}

// UnimplementedBusinessOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessOpsServiceServer struct{}

func (UnimplementedBusinessOpsServiceServer) ScheduleEvent(context.Context, *ScheduleEventRequest) (*ScheduleEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleEvent not implemented")
}
func (UnimplementedBusinessOpsServiceServer) GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedBusinessOpsServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedBusinessOpsServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedBusinessOpsServiceServer) GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedBusinessOpsServiceServer) mustEmbedUnimplementedBusinessOpsServiceServer() {}
func (UnimplementedBusinessOpsServiceServer) testEmbeddedByValue()                            {}

// UnsafeBusinessOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessOpsServiceServer will
// result in compilation errors.
type UnsafeBusinessOpsServiceServer interface {
	mustEmbedUnimplementedBusinessOpsServiceServer()
}

func RegisterBusinessOpsServiceServer(s grpc.ServiceRegistrar, srv BusinessOpsServiceServer) {
	// If the following call panics, it indicates UnimplementedBusinessOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusinessOpsService_ServiceDesc, srv)
}

func _BusinessOpsService_ScheduleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOpsServiceServer).ScheduleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessOpsService_ScheduleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOpsServiceServer).ScheduleEvent(ctx, req.(*ScheduleEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessOpsService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOpsServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessOpsService_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOpsServiceServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessOpsService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOpsServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessOpsService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOpsServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessOpsService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOpsServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessOpsService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOpsServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessOpsService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOpsServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessOpsService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOpsServiceServer).GenerateReport(ctx, req.(*GenerateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessOpsService_ServiceDesc is the grpc.ServiceDesc for BusinessOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.business.BusinessOpsService",
	HandlerType: (*BusinessOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleEvent",
			Handler:    _BusinessOpsService_ScheduleEvent_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _BusinessOpsService_GetSchedule_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _BusinessOpsService_CreateTask_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _BusinessOpsService_SendMessage_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _BusinessOpsService_GenerateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/business.proto",
}
