// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: voice/voice.proto

package voice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceService_Converse_FullMethodName     = "/jarvis.voice.VoiceService/Converse"
	VoiceService_GetSession_FullMethodName   = "/jarvis.voice.VoiceService/GetSession"
	VoiceService_ListSessions_FullMethodName = "/jarvis.voice.VoiceService/ListSessions"
)

// VoiceServiceClient is the client API for VoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// VoiceService
//
// Real-time voice interface between Jarvis iOS clients and the backend.
// Sits alongside NLPService — the voice stream handles raw audio upstream
// and pipes through STT → NLP (ParseIntent / ProcessDialogueTurn) → TTS
// on the server side. Clients receive transcripts, replies, TTS audio,
// and HUD actions over a single bidirectional stream.
// ─────────────────────────────────────────────────────────────────────────────
type VoiceServiceClient interface {
	// Converse opens a full-duplex voice session.
	// First message must be a StreamConfig. Subsequent messages are AudioChunks
	// and ControlEvents. Server streams back StatusEvents, Transcripts, Replies,
	// AudioReplies, and HUD Actions.
	Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConverseRequest, ConverseResponse], error)
	// GetSession retrieves metadata for a session — used after reconnect.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	// ListSessions returns recent sessions for a user (HUD history / replay).
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
}

type voiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceServiceClient(cc grpc.ClientConnInterface) VoiceServiceClient {
	return &voiceServiceClient{cc}
}

func (c *voiceServiceClient) Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConverseRequest, ConverseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceService_ServiceDesc.Streams[0], VoiceService_Converse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConverseRequest, ConverseResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceService_ConverseClient = grpc.BidiStreamingClient[ConverseRequest, ConverseResponse]

func (c *voiceServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, VoiceService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServiceServer is the server API for VoiceService service.
// All implementations must embed UnimplementedVoiceServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// VoiceService
//
// Real-time voice interface between Jarvis iOS clients and the backend.
// Sits alongside NLPService — the voice stream handles raw audio upstream
// and pipes through STT → NLP (ParseIntent / ProcessDialogueTurn) → TTS
// on the server side. Clients receive transcripts, replies, TTS audio,
// and HUD actions over a single bidirectional stream.
// ─────────────────────────────────────────────────────────────────────────────
type VoiceServiceServer interface {
	// Converse opens a full-duplex voice session.
	// First message must be a StreamConfig. Subsequent messages are AudioChunks
	// and ControlEvents. Server streams back StatusEvents, Transcripts, Replies,
	// AudioReplies, and HUD Actions.
	Converse(grpc.BidiStreamingServer[ConverseRequest, ConverseResponse]) error
	// GetSession retrieves metadata for a session — used after reconnect.
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	// ListSessions returns recent sessions for a user (HUD history / replay).
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	mustEmbedUnimplementedVoiceServiceServer()
}

// UnimplementedVoiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceServiceServer struct{}

func (UnimplementedVoiceServiceServer) Converse(grpc.BidiStreamingServer[ConverseRequest, ConverseResponse]) error {
	return status.Error(codes.Unimplemented, "method Converse not implemented")
}
func (UnimplementedVoiceServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedVoiceServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedVoiceServiceServer) mustEmbedUnimplementedVoiceServiceServer() {}
func (UnimplementedVoiceServiceServer) testEmbeddedByValue()                      {}

// UnsafeVoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServiceServer will
// result in compilation errors.
type UnsafeVoiceServiceServer interface {
	mustEmbedUnimplementedVoiceServiceServer()
}

func RegisterVoiceServiceServer(s grpc.ServiceRegistrar, srv VoiceServiceServer) {
	// If the following call panics, it indicates UnimplementedVoiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceService_ServiceDesc, srv)
}

func _VoiceService_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceServiceServer).Converse(&grpc.GenericServerStream[ConverseRequest, ConverseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceService_ConverseServer = grpc.BidiStreamingServer[ConverseRequest, ConverseResponse]

func _VoiceService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceService_ServiceDesc is the grpc.ServiceDesc for VoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jarvis.voice.VoiceService",
	HandlerType: (*VoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _VoiceService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _VoiceService_ListSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converse",
			Handler:       _VoiceService_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voice/voice.proto",
}
