// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: voice/voice.proto

package voice

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioEncoding int32

const (
	AudioEncoding_AUDIO_ENCODING_UNSPECIFIED AudioEncoding = 0
	// Linear PCM, 16-bit signed little-endian.
	AudioEncoding_AUDIO_ENCODING_PCM_16BIT AudioEncoding = 1
	// Opus in OGG container.
	AudioEncoding_AUDIO_ENCODING_OPUS AudioEncoding = 2
	// AAC-LC.
	AudioEncoding_AUDIO_ENCODING_AAC AudioEncoding = 3
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0: "AUDIO_ENCODING_UNSPECIFIED",
		1: "AUDIO_ENCODING_PCM_16BIT",
		2: "AUDIO_ENCODING_OPUS",
		3: "AUDIO_ENCODING_AAC",
	}
	AudioEncoding_value = map[string]int32{
		"AUDIO_ENCODING_UNSPECIFIED": 0,
		"AUDIO_ENCODING_PCM_16BIT":   1,
		"AUDIO_ENCODING_OPUS":        2,
		"AUDIO_ENCODING_AAC":         3,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_voice_proto_enumTypes[0].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_voice_voice_proto_enumTypes[0]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{0}
}

// Mirrors ErrorCode style from other Jarvis services.
type VoiceErrorCode int32

const (
	VoiceErrorCode_VOICE_ERROR_CODE_UNSPECIFIED            VoiceErrorCode = 0
	VoiceErrorCode_VOICE_ERROR_CODE_STT_FAILURE            VoiceErrorCode = 1
	VoiceErrorCode_VOICE_ERROR_CODE_NLP_TIMEOUT            VoiceErrorCode = 2
	VoiceErrorCode_VOICE_ERROR_CODE_TTS_FAILURE            VoiceErrorCode = 3
	VoiceErrorCode_VOICE_ERROR_CODE_AUTH_EXPIRED           VoiceErrorCode = 4
	VoiceErrorCode_VOICE_ERROR_CODE_RATE_LIMITED           VoiceErrorCode = 5
	VoiceErrorCode_VOICE_ERROR_CODE_WAKE_WORD_NOT_DETECTED VoiceErrorCode = 6
)

// Enum value maps for VoiceErrorCode.
var (
	VoiceErrorCode_name = map[int32]string{
		0: "VOICE_ERROR_CODE_UNSPECIFIED",
		1: "VOICE_ERROR_CODE_STT_FAILURE",
		2: "VOICE_ERROR_CODE_NLP_TIMEOUT",
		3: "VOICE_ERROR_CODE_TTS_FAILURE",
		4: "VOICE_ERROR_CODE_AUTH_EXPIRED",
		5: "VOICE_ERROR_CODE_RATE_LIMITED",
		6: "VOICE_ERROR_CODE_WAKE_WORD_NOT_DETECTED",
	}
	VoiceErrorCode_value = map[string]int32{
		"VOICE_ERROR_CODE_UNSPECIFIED":            0,
		"VOICE_ERROR_CODE_STT_FAILURE":            1,
		"VOICE_ERROR_CODE_NLP_TIMEOUT":            2,
		"VOICE_ERROR_CODE_TTS_FAILURE":            3,
		"VOICE_ERROR_CODE_AUTH_EXPIRED":           4,
		"VOICE_ERROR_CODE_RATE_LIMITED":           5,
		"VOICE_ERROR_CODE_WAKE_WORD_NOT_DETECTED": 6,
	}
)

func (x VoiceErrorCode) Enum() *VoiceErrorCode {
	p := new(VoiceErrorCode)
	*p = x
	return p
}

func (x VoiceErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_voice_proto_enumTypes[1].Descriptor()
}

func (VoiceErrorCode) Type() protoreflect.EnumType {
	return &file_voice_voice_proto_enumTypes[1]
}

func (x VoiceErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceErrorCode.Descriptor instead.
func (VoiceErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{1}
}

type ControlEvent_Type int32

const (
	ControlEvent_TYPE_UNSPECIFIED ControlEvent_Type = 0
	// On-device VAD detected end-of-speech.
	ControlEvent_TYPE_END_OF_SPEECH ControlEvent_Type = 1
	// Cancel the current in-flight STT/NLP/TTS pipeline.
	ControlEvent_TYPE_CANCEL ControlEvent_Type = 2
	// Keep-alive ping — prevents stream timeout during silence.
	ControlEvent_TYPE_KEEP_ALIVE ControlEvent_Type = 3
	// Client explicitly started a new turn (e.g. PTT re-press).
	ControlEvent_TYPE_NEW_TURN ControlEvent_Type = 4
)

// Enum value maps for ControlEvent_Type.
var (
	ControlEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_END_OF_SPEECH",
		2: "TYPE_CANCEL",
		3: "TYPE_KEEP_ALIVE",
		4: "TYPE_NEW_TURN",
	}
	ControlEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":   0,
		"TYPE_END_OF_SPEECH": 1,
		"TYPE_CANCEL":        2,
		"TYPE_KEEP_ALIVE":    3,
		"TYPE_NEW_TURN":      4,
	}
)

func (x ControlEvent_Type) Enum() *ControlEvent_Type {
	p := new(ControlEvent_Type)
	*p = x
	return p
}

func (x ControlEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_voice_proto_enumTypes[2].Descriptor()
}

func (ControlEvent_Type) Type() protoreflect.EnumType {
	return &file_voice_voice_proto_enumTypes[2]
}

func (x ControlEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlEvent_Type.Descriptor instead.
func (ControlEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{5, 0}
}

type StatusEvent_State int32

const (
	StatusEvent_STATE_UNSPECIFIED StatusEvent_State = 0
	// Stream open, awaiting wake word or first audio chunk.
	StatusEvent_STATE_IDLE StatusEvent_State = 1
	// Actively capturing + streaming user speech.
	StatusEvent_STATE_LISTENING StatusEvent_State = 2
	// STT committed, running NLP pipeline.
	StatusEvent_STATE_PROCESSING StatusEvent_State = 3
	// Streaming TTS audio reply to the client.
	StatusEvent_STATE_SPEAKING StatusEvent_State = 4
	// Non-fatal error — stream stays open.
	StatusEvent_STATE_ERROR StatusEvent_State = 5
	// Session ended (server-initiated).
	StatusEvent_STATE_ENDED StatusEvent_State = 6
)

// Enum value maps for StatusEvent_State.
var (
	StatusEvent_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_LISTENING",
		3: "STATE_PROCESSING",
		4: "STATE_SPEAKING",
		5: "STATE_ERROR",
		6: "STATE_ENDED",
	}
	StatusEvent_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_IDLE":        1,
		"STATE_LISTENING":   2,
		"STATE_PROCESSING":  3,
		"STATE_SPEAKING":    4,
		"STATE_ERROR":       5,
		"STATE_ENDED":       6,
	}
)

func (x StatusEvent_State) Enum() *StatusEvent_State {
	p := new(StatusEvent_State)
	*p = x
	return p
}

func (x StatusEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_voice_proto_enumTypes[3].Descriptor()
}

func (StatusEvent_State) Type() protoreflect.EnumType {
	return &file_voice_voice_proto_enumTypes[3]
}

func (x StatusEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEvent_State.Descriptor instead.
func (StatusEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{7, 0}
}

type HUDAction_Type int32

const (
	HUDAction_TYPE_UNSPECIFIED HUDAction_Type = 0
	// Launch an iOS app or deep-link URL.
	HUDAction_TYPE_OPEN_APP HUDAction_Type = 1
	// Render an information card in the HUD overlay.
	HUDAction_TYPE_SHOW_CARD HUDAction_Type = 2
	// Set a countdown timer visible in the HUD.
	HUDAction_TYPE_SET_TIMER HUDAction_Type = 3
	// Navigate to a map location or facility zone.
	HUDAction_TYPE_NAVIGATE HUDAction_Type = 4
	// Dismiss the HUD overlay.
	HUDAction_TYPE_DISMISS_HUD HUDAction_Type = 5
	// Dispatch an agent task (wraps AgentCoordinatorService.DispatchTask).
	HUDAction_TYPE_DISPATCH_AGENT HUDAction_Type = 6
	// Execute a hardware command (wraps HardwareService.SendCommand).
	HUDAction_TYPE_HARDWARE_CMD HUDAction_Type = 7
	// Trigger a security protocol (wraps SecurityService.ExecuteProtocol).
	HUDAction_TYPE_SECURITY_PROTOCOL HUDAction_Type = 8
)

// Enum value maps for HUDAction_Type.
var (
	HUDAction_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_OPEN_APP",
		2: "TYPE_SHOW_CARD",
		3: "TYPE_SET_TIMER",
		4: "TYPE_NAVIGATE",
		5: "TYPE_DISMISS_HUD",
		6: "TYPE_DISPATCH_AGENT",
		7: "TYPE_HARDWARE_CMD",
		8: "TYPE_SECURITY_PROTOCOL",
	}
	HUDAction_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":       0,
		"TYPE_OPEN_APP":          1,
		"TYPE_SHOW_CARD":         2,
		"TYPE_SET_TIMER":         3,
		"TYPE_NAVIGATE":          4,
		"TYPE_DISMISS_HUD":       5,
		"TYPE_DISPATCH_AGENT":    6,
		"TYPE_HARDWARE_CMD":      7,
		"TYPE_SECURITY_PROTOCOL": 8,
	}
)

func (x HUDAction_Type) Enum() *HUDAction_Type {
	p := new(HUDAction_Type)
	*p = x
	return p
}

func (x HUDAction_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HUDAction_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_voice_proto_enumTypes[4].Descriptor()
}

func (HUDAction_Type) Type() protoreflect.EnumType {
	return &file_voice_voice_proto_enumTypes[4]
}

func (x HUDAction_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HUDAction_Type.Descriptor instead.
func (HUDAction_Type) EnumDescriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{12, 0}
}

type ConverseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConverseRequest_Config
	//	*ConverseRequest_Audio
	//	*ConverseRequest_Event
	Payload       isConverseRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConverseRequest) Reset() {
	*x = ConverseRequest{}
	mi := &file_voice_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverseRequest) ProtoMessage() {}

func (x *ConverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverseRequest.ProtoReflect.Descriptor instead.
func (*ConverseRequest) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{0}
}

func (x *ConverseRequest) GetPayload() isConverseRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConverseRequest) GetConfig() *StreamConfig {
	if x != nil {
		if x, ok := x.Payload.(*ConverseRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ConverseRequest) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*ConverseRequest_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ConverseRequest) GetEvent() *ControlEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConverseRequest_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isConverseRequest_Payload interface {
	isConverseRequest_Payload()
}

type ConverseRequest_Config struct {
	// Sent exactly once as the very first message to configure the stream.
	Config *StreamConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ConverseRequest_Audio struct {
	// Continuous raw audio frames.
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ConverseRequest_Event struct {
	// Control signals: end-of-speech, cancel, keep-alive, new-turn.
	Event *ControlEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*ConverseRequest_Config) isConverseRequest_Payload() {}

func (*ConverseRequest_Audio) isConverseRequest_Payload() {}

func (*ConverseRequest_Event) isConverseRequest_Payload() {}

type StreamConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard Jarvis request metadata (request_id, user_id, session_id, source).
	Meta *common.RequestMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Device / client context.
	ClientInfo *ClientInfo `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	// Audio encoding and capture parameters.
	AudioConfig *AudioConfig `protobuf:"bytes,3,opt,name=audio_config,json=audioConfig,proto3" json:"audio_config,omitempty"`
	// Optional BCP-47 language hint, e.g. "en-US". Defaults to "en-US".
	LanguageCode string `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// Optional voice ID for TTS reply synthesis.
	VoiceId string `protobuf:"bytes,5,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	// NLP context tags forwarded to ParseIntent on each recognised utterance.
	// Maps to ParseRequest.context_tags in nlp.proto.
	ContextTags   []string `protobuf:"bytes,6,rep,name=context_tags,json=contextTags,proto3" json:"context_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_voice_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{1}
}

func (x *StreamConfig) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamConfig) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *StreamConfig) GetAudioConfig() *AudioConfig {
	if x != nil {
		return x.AudioConfig
	}
	return nil
}

func (x *StreamConfig) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *StreamConfig) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *StreamConfig) GetContextTags() []string {
	if x != nil {
		return x.ContextTags
	}
	return nil
}

type ClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "ios", "android", "web"
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// e.g. "1.4.2"
	AppVersion string `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// e.g. "iPhone 15 Pro"
	DeviceModel string `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	// e.g. "17.4"
	OsVersion     string `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_voice_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ClientInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *ClientInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

type AudioConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Encoding AudioEncoding          `protobuf:"varint,1,opt,name=encoding,proto3,enum=jarvis.voice.AudioEncoding" json:"encoding,omitempty"`
	// Samples per second. Recommended: 16000.
	SampleRateHz int32 `protobuf:"varint,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	// Number of channels. Recommended: 1 (mono).
	ChannelCount int32 `protobuf:"varint,3,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	// For OPUS: frame duration in ms (10 | 20 | 40 | 60). Default: 20.
	FrameDurationMs int32 `protobuf:"varint,4,opt,name=frame_duration_ms,json=frameDurationMs,proto3" json:"frame_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioConfig) Reset() {
	*x = AudioConfig{}
	mi := &file_voice_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioConfig) ProtoMessage() {}

func (x *AudioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioConfig.ProtoReflect.Descriptor instead.
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{3}
}

func (x *AudioConfig) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_AUDIO_ENCODING_UNSPECIFIED
}

func (x *AudioConfig) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *AudioConfig) GetChannelCount() int32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

func (x *AudioConfig) GetFrameDurationMs() int32 {
	if x != nil {
		return x.FrameDurationMs
	}
	return 0
}

type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded audio bytes (format declared in StreamConfig.audio_config).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Monotonically increasing frame counter for ordering / loss detection.
	SequenceNum int64 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Client-side capture timestamp (Unix ms).
	CapturedAtMs int64 `protobuf:"varint,3,opt,name=captured_at_ms,json=capturedAtMs,proto3" json:"captured_at_ms,omitempty"`
	// True when the on-device wake word detector flagged this frame as the
	// "Hey Jarvis" trigger — lets the server skip VAD buffering overhead.
	IsWakeWordFrame bool `protobuf:"varint,4,opt,name=is_wake_word_frame,json=isWakeWordFrame,proto3" json:"is_wake_word_frame,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_voice_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{4}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AudioChunk) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

func (x *AudioChunk) GetIsWakeWordFrame() bool {
	if x != nil {
		return x.IsWakeWordFrame
	}
	return false
}

type ControlEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlEvent_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=jarvis.voice.ControlEvent_Type" json:"type,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEvent) Reset() {
	*x = ControlEvent{}
	mi := &file_voice_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEvent) ProtoMessage() {}

func (x *ControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEvent.ProtoReflect.Descriptor instead.
func (*ControlEvent) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{5}
}

func (x *ControlEvent) GetType() ControlEvent_Type {
	if x != nil {
		return x.Type
	}
	return ControlEvent_TYPE_UNSPECIFIED
}

func (x *ControlEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConverseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mirrors StreamConfig.meta.session_id for client-side correlation.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Server-assigned monotonic index for ordering concurrent messages.
	SequenceNum int64 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConverseResponse_Status
	//	*ConverseResponse_Transcript
	//	*ConverseResponse_Reply
	//	*ConverseResponse_AudioReply
	//	*ConverseResponse_Action
	Payload       isConverseResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConverseResponse) Reset() {
	*x = ConverseResponse{}
	mi := &file_voice_voice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverseResponse) ProtoMessage() {}

func (x *ConverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverseResponse.ProtoReflect.Descriptor instead.
func (*ConverseResponse) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{6}
}

func (x *ConverseResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConverseResponse) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ConverseResponse) GetPayload() isConverseResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConverseResponse) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConverseResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ConverseResponse) GetTranscript() *Transcript {
	if x != nil {
		if x, ok := x.Payload.(*ConverseResponse_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *ConverseResponse) GetReply() *Reply {
	if x != nil {
		if x, ok := x.Payload.(*ConverseResponse_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *ConverseResponse) GetAudioReply() *AudioReply {
	if x != nil {
		if x, ok := x.Payload.(*ConverseResponse_AudioReply); ok {
			return x.AudioReply
		}
	}
	return nil
}

func (x *ConverseResponse) GetAction() *HUDAction {
	if x != nil {
		if x, ok := x.Payload.(*ConverseResponse_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isConverseResponse_Payload interface {
	isConverseResponse_Payload()
}

type ConverseResponse_Status struct {
	// Session lifecycle + state machine transitions.
	Status *StatusEvent `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type ConverseResponse_Transcript struct {
	// Real-time STT output (partial and final).
	Transcript *Transcript `protobuf:"bytes,4,opt,name=transcript,proto3,oneof"`
}

type ConverseResponse_Reply struct {
	// Jarvis natural-language reply + intent (mirrors NLP DialogueTurnResponse).
	Reply *Reply `protobuf:"bytes,5,opt,name=reply,proto3,oneof"`
}

type ConverseResponse_AudioReply struct {
	// TTS audio for Jarvis's spoken response.
	AudioReply *AudioReply `protobuf:"bytes,6,opt,name=audio_reply,json=audioReply,proto3,oneof"`
}

type ConverseResponse_Action struct {
	// Structured HUD action (open app, show card, dispatch agent, etc.).
	Action *HUDAction `protobuf:"bytes,7,opt,name=action,proto3,oneof"`
}

func (*ConverseResponse_Status) isConverseResponse_Payload() {}

func (*ConverseResponse_Transcript) isConverseResponse_Payload() {}

func (*ConverseResponse_Reply) isConverseResponse_Payload() {}

func (*ConverseResponse_AudioReply) isConverseResponse_Payload() {}

func (*ConverseResponse_Action) isConverseResponse_Payload() {}

type StatusEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State StatusEvent_State      `protobuf:"varint,1,opt,name=state,proto3,enum=jarvis.voice.StatusEvent_State" json:"state,omitempty"`
	// Human-readable detail. Required when state == STATE_ERROR.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Structured error code for the client to handle programmatically.
	ErrorCode     VoiceErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=jarvis.voice.VoiceErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_voice_voice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{7}
}

func (x *StatusEvent) GetState() StatusEvent_State {
	if x != nil {
		return x.State
	}
	return StatusEvent_STATE_UNSPECIFIED
}

func (x *StatusEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusEvent) GetErrorCode() VoiceErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return VoiceErrorCode_VOICE_ERROR_CODE_UNSPECIFIED
}

type Transcript struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recognised text (may be partial when is_final == false).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// False = interim / partial. True = committed, will not be revised.
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Model confidence [0.0, 1.0]. Meaningful only when is_final == true.
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Word-level timing populated when is_final == true (for HUD subtitle sync).
	Words []*WordInfo `protobuf:"bytes,4,rep,name=words,proto3" json:"words,omitempty"`
	// BCP-47 language detected (may differ from requested language_code).
	DetectedLanguage string `protobuf:"bytes,5,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_voice_voice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{8}
}

func (x *Transcript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcript) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Transcript) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Transcript) GetWords() []*WordInfo {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *Transcript) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

type WordInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	StartMs       int64                  `protobuf:"varint,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int64                  `protobuf:"varint,3,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordInfo) Reset() {
	*x = WordInfo{}
	mi := &file_voice_voice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordInfo) ProtoMessage() {}

func (x *WordInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordInfo.ProtoReflect.Descriptor instead.
func (*WordInfo) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{9}
}

func (x *WordInfo) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordInfo) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *WordInfo) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *WordInfo) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Reply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural-language response text (maps to DialogueTurnResponse.reply_text).
	ReplyText string `protobuf:"bytes,1,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	// Resolved intent label (maps to DialogueTurnResponse.resolved_intent).
	// Uses the same Intent enum values as nlp.proto.
	Intent string `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	// Whether this reply needs user confirmation before acting.
	// Maps to DialogueTurnResponse.requires_confirmation.
	RequiresConfirmation bool `protobuf:"varint,3,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	// Arbitrary metadata: trace IDs, intent slots, etc.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_voice_voice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{10}
}

func (x *Reply) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

func (x *Reply) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *Reply) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

func (x *Reply) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AudioReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded TTS audio bytes.
	Data     []byte        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Encoding AudioEncoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=jarvis.voice.AudioEncoding" json:"encoding,omitempty"`
	// Spoken text — rendered as HUD subtitle during playback.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// True on the last chunk of a complete TTS utterance.
	IsFinalChunk bool `protobuf:"varint,4,opt,name=is_final_chunk,json=isFinalChunk,proto3" json:"is_final_chunk,omitempty"`
	// Monotonic chunk index within this reply.
	ChunkIndex    int32 `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioReply) Reset() {
	*x = AudioReply{}
	mi := &file_voice_voice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioReply) ProtoMessage() {}

func (x *AudioReply) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioReply.ProtoReflect.Descriptor instead.
func (*AudioReply) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{11}
}

func (x *AudioReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioReply) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_AUDIO_ENCODING_UNSPECIFIED
}

func (x *AudioReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AudioReply) GetIsFinalChunk() bool {
	if x != nil {
		return x.IsFinalChunk
	}
	return false
}

func (x *AudioReply) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type HUDAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  HUDAction_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=jarvis.voice.HUDAction_Type" json:"type,omitempty"`
	// JSON payload specific to the action type.
	// Schemas are documented in gateway/docs/api-reference.md.
	PayloadJson string `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// Severity hint for HUD rendering — reuses common.Severity.
	Severity      common.Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=jarvis.common.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HUDAction) Reset() {
	*x = HUDAction{}
	mi := &file_voice_voice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HUDAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HUDAction) ProtoMessage() {}

func (x *HUDAction) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HUDAction.ProtoReflect.Descriptor instead.
func (*HUDAction) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{12}
}

func (x *HUDAction) GetType() HUDAction_Type {
	if x != nil {
		return x.Type
	}
	return HUDAction_TYPE_UNSPECIFIED
}

func (x *HUDAction) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *HUDAction) GetSeverity() common.Severity {
	if x != nil {
		return x.Severity
	}
	return common.Severity(0)
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_voice_voice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Session       *VoiceSession          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_voice_voice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSessionResponse) GetSession() *VoiceSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_voice_voice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{15}
}

func (x *ListSessionsRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Sessions      []*VoiceSession        `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_voice_voice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{16}
}

func (x *ListSessionsResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListSessionsResponse) GetSessions() []*VoiceSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type VoiceSession struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// Final STT transcript turns for this session.
	Turns         []*Transcript     `protobuf:"bytes,5,rep,name=turns,proto3" json:"turns,omitempty"`
	TerminalState StatusEvent_State `protobuf:"varint,6,opt,name=terminal_state,json=terminalState,proto3,enum=jarvis.voice.StatusEvent_State" json:"terminal_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceSession) Reset() {
	*x = VoiceSession{}
	mi := &file_voice_voice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSession) ProtoMessage() {}

func (x *VoiceSession) ProtoReflect() protoreflect.Message {
	mi := &file_voice_voice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSession.ProtoReflect.Descriptor instead.
func (*VoiceSession) Descriptor() ([]byte, []int) {
	return file_voice_voice_proto_rawDescGZIP(), []int{17}
}

func (x *VoiceSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VoiceSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoiceSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *VoiceSession) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *VoiceSession) GetTurns() []*Transcript {
	if x != nil {
		return x.Turns
	}
	return nil
}

func (x *VoiceSession) GetTerminalState() StatusEvent_State {
	if x != nil {
		return x.TerminalState
	}
	return StatusEvent_STATE_UNSPECIFIED
}

var File_voice_voice_proto protoreflect.FileDescriptor

const file_voice_voice_proto_rawDesc = "" +
	"\n" +
	"\x11voice/voice.proto\x12\fjarvis.voice\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xb8\x01\n" +
	"\x0fConverseRequest\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1a.jarvis.voice.StreamConfigH\x00R\x06config\x120\n" +
	"\x05audio\x18\x02 \x01(\v2\x18.jarvis.voice.AudioChunkH\x00R\x05audio\x122\n" +
	"\x05event\x18\x03 \x01(\v2\x1a.jarvis.voice.ControlEventH\x00R\x05eventB\t\n" +
	"\apayload\"\x9a\x02\n" +
	"\fStreamConfig\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x129\n" +
	"\vclient_info\x18\x02 \x01(\v2\x18.jarvis.voice.ClientInfoR\n" +
	"clientInfo\x12<\n" +
	"\faudio_config\x18\x03 \x01(\v2\x19.jarvis.voice.AudioConfigR\vaudioConfig\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\x12\x19\n" +
	"\bvoice_id\x18\x05 \x01(\tR\avoiceId\x12!\n" +
	"\fcontext_tags\x18\x06 \x03(\tR\vcontextTags\"\x8b\x01\n" +
	"\n" +
	"ClientInfo\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x02 \x01(\tR\n" +
	"appVersion\x12!\n" +
	"\fdevice_model\x18\x03 \x01(\tR\vdeviceModel\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\"\xbd\x01\n" +
	"\vAudioConfig\x127\n" +
	"\bencoding\x18\x01 \x01(\x0e2\x1b.jarvis.voice.AudioEncodingR\bencoding\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\x05R\fsampleRateHz\x12#\n" +
	"\rchannel_count\x18\x03 \x01(\x05R\fchannelCount\x12*\n" +
	"\x11frame_duration_ms\x18\x04 \x01(\x05R\x0fframeDurationMs\"\x96\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x03R\vsequenceNum\x12$\n" +
	"\x0ecaptured_at_ms\x18\x03 \x01(\x03R\fcapturedAtMs\x12+\n" +
	"\x12is_wake_word_frame\x18\x04 \x01(\bR\x0fisWakeWordFrame\"\xca\x01\n" +
	"\fControlEvent\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.jarvis.voice.ControlEvent.TypeR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"m\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TYPE_END_OF_SPEECH\x10\x01\x12\x0f\n" +
	"\vTYPE_CANCEL\x10\x02\x12\x13\n" +
	"\x0fTYPE_KEEP_ALIVE\x10\x03\x12\x11\n" +
	"\rTYPE_NEW_TURN\x10\x04\"\xed\x02\n" +
	"\x10ConverseResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x03R\vsequenceNum\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x19.jarvis.voice.StatusEventH\x00R\x06status\x12:\n" +
	"\n" +
	"transcript\x18\x04 \x01(\v2\x18.jarvis.voice.TranscriptH\x00R\n" +
	"transcript\x12+\n" +
	"\x05reply\x18\x05 \x01(\v2\x13.jarvis.voice.ReplyH\x00R\x05reply\x12;\n" +
	"\vaudio_reply\x18\x06 \x01(\v2\x18.jarvis.voice.AudioReplyH\x00R\n" +
	"audioReply\x121\n" +
	"\x06action\x18\a \x01(\v2\x17.jarvis.voice.HUDActionH\x00R\x06actionB\t\n" +
	"\apayload\"\xad\x02\n" +
	"\vStatusEvent\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.jarvis.voice.StatusEvent.StateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1c.jarvis.voice.VoiceErrorCodeR\terrorCode\"\x8f\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x13\n" +
	"\x0fSTATE_LISTENING\x10\x02\x12\x14\n" +
	"\x10STATE_PROCESSING\x10\x03\x12\x12\n" +
	"\x0eSTATE_SPEAKING\x10\x04\x12\x0f\n" +
	"\vSTATE_ERROR\x10\x05\x12\x0f\n" +
	"\vSTATE_ENDED\x10\x06\"\xb6\x01\n" +
	"\n" +
	"Transcript\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12,\n" +
	"\x05words\x18\x04 \x03(\v2\x16.jarvis.voice.WordInfoR\x05words\x12+\n" +
	"\x11detected_language\x18\x05 \x01(\tR\x10detectedLanguage\"p\n" +
	"\bWordInfo\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x19\n" +
	"\bstart_ms\x18\x02 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x03 \x01(\x03R\x05endMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\xef\x01\n" +
	"\x05Reply\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x01 \x01(\tR\treplyText\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x123\n" +
	"\x15requires_confirmation\x18\x03 \x01(\bR\x14requiresConfirmation\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.jarvis.voice.Reply.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\n" +
	"AudioReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x127\n" +
	"\bencoding\x18\x02 \x01(\x0e2\x1b.jarvis.voice.AudioEncodingR\bencoding\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12$\n" +
	"\x0eis_final_chunk\x18\x04 \x01(\bR\fisFinalChunk\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\"\xe4\x02\n" +
	"\tHUDAction\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.jarvis.voice.HUDAction.TypeR\x04type\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\x123\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x17.jarvis.common.SeverityR\bseverity\"\xcc\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_OPEN_APP\x10\x01\x12\x12\n" +
	"\x0eTYPE_SHOW_CARD\x10\x02\x12\x12\n" +
	"\x0eTYPE_SET_TIMER\x10\x03\x12\x11\n" +
	"\rTYPE_NAVIGATE\x10\x04\x12\x14\n" +
	"\x10TYPE_DISMISS_HUD\x10\x05\x12\x17\n" +
	"\x13TYPE_DISPATCH_AGENT\x10\x06\x12\x15\n" +
	"\x11TYPE_HARDWARE_CMD\x10\a\x12\x1a\n" +
	"\x16TYPE_SECURITY_PROTOCOL\x10\b\"b\n" +
	"\x11GetSessionRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"{\n" +
	"\x12GetSessionResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x124\n" +
	"\asession\x18\x02 \x01(\v2\x1a.jarvis.voice.VoiceSessionR\asession\"\x81\x01\n" +
	"\x13ListSessionsRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xa7\x01\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x126\n" +
	"\bsessions\x18\x02 \x03(\v2\x1a.jarvis.voice.VoiceSessionR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xb0\x02\n" +
	"\fVoiceSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12.\n" +
	"\x05turns\x18\x05 \x03(\v2\x18.jarvis.voice.TranscriptR\x05turns\x12F\n" +
	"\x0eterminal_state\x18\x06 \x01(\x0e2\x1f.jarvis.voice.StatusEvent.StateR\rterminalState*~\n" +
	"\rAudioEncoding\x12\x1e\n" +
	"\x1aAUDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUDIO_ENCODING_PCM_16BIT\x10\x01\x12\x17\n" +
	"\x13AUDIO_ENCODING_OPUS\x10\x02\x12\x16\n" +
	"\x12AUDIO_ENCODING_AAC\x10\x03*\x8b\x02\n" +
	"\x0eVoiceErrorCode\x12 \n" +
	"\x1cVOICE_ERROR_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVOICE_ERROR_CODE_STT_FAILURE\x10\x01\x12 \n" +
	"\x1cVOICE_ERROR_CODE_NLP_TIMEOUT\x10\x02\x12 \n" +
	"\x1cVOICE_ERROR_CODE_TTS_FAILURE\x10\x03\x12!\n" +
	"\x1dVOICE_ERROR_CODE_AUTH_EXPIRED\x10\x04\x12!\n" +
	"\x1dVOICE_ERROR_CODE_RATE_LIMITED\x10\x05\x12+\n" +
	"'VOICE_ERROR_CODE_WAKE_WORD_NOT_DETECTED\x10\x062\xca\x02\n" +
	"\fVoiceService\x12M\n" +
	"\bConverse\x12\x1d.jarvis.voice.ConverseRequest\x1a\x1e.jarvis.voice.ConverseResponse(\x010\x01\x12x\n" +
	"\n" +
	"GetSession\x12\x1f.jarvis.voice.GetSessionRequest\x1a .jarvis.voice.GetSessionResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/voice/sessions/{session_id}\x12q\n" +
	"\fListSessions\x12!.jarvis.voice.ListSessionsRequest\x1a\".jarvis.voice.ListSessionsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/voice/sessionsB\x96\x01\n" +
	"\x10com.jarvis.voiceB\n" +
	"VoiceProtoP\x01Z%github.com/rkrimper1/jarvis/api/pb/voice\xa2\x02\x03JVX\xaa\x02\fJarvis.Voice\xca\x02\fJarvis\\Voice\xe2\x02\x18Jarvis\\Voice\\GPBMetadata\xea\x02\rJarvis::Voiceb\x06proto3"

var (
	file_voice_voice_proto_rawDescOnce sync.Once
	file_voice_voice_proto_rawDescData []byte
)

func file_voice_voice_proto_rawDescGZIP() []byte {
	file_voice_voice_proto_rawDescOnce.Do(func() {
		file_voice_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_voice_proto_rawDesc), len(file_voice_voice_proto_rawDesc)))
	})
	return file_voice_voice_proto_rawDescData
}

var file_voice_voice_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_voice_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_voice_voice_proto_goTypes = []any{
	(AudioEncoding)(0),            // 0: jarvis.voice.AudioEncoding
	(VoiceErrorCode)(0),           // 1: jarvis.voice.VoiceErrorCode
	(ControlEvent_Type)(0),        // 2: jarvis.voice.ControlEvent.Type
	(StatusEvent_State)(0),        // 3: jarvis.voice.StatusEvent.State
	(HUDAction_Type)(0),           // 4: jarvis.voice.HUDAction.Type
	(*ConverseRequest)(nil),       // 5: jarvis.voice.ConverseRequest
	(*StreamConfig)(nil),          // 6: jarvis.voice.StreamConfig
	(*ClientInfo)(nil),            // 7: jarvis.voice.ClientInfo
	(*AudioConfig)(nil),           // 8: jarvis.voice.AudioConfig
	(*AudioChunk)(nil),            // 9: jarvis.voice.AudioChunk
	(*ControlEvent)(nil),          // 10: jarvis.voice.ControlEvent
	(*ConverseResponse)(nil),      // 11: jarvis.voice.ConverseResponse
	(*StatusEvent)(nil),           // 12: jarvis.voice.StatusEvent
	(*Transcript)(nil),            // 13: jarvis.voice.Transcript
	(*WordInfo)(nil),              // 14: jarvis.voice.WordInfo
	(*Reply)(nil),                 // 15: jarvis.voice.Reply
	(*AudioReply)(nil),            // 16: jarvis.voice.AudioReply
	(*HUDAction)(nil),             // 17: jarvis.voice.HUDAction
	(*GetSessionRequest)(nil),     // 18: jarvis.voice.GetSessionRequest
	(*GetSessionResponse)(nil),    // 19: jarvis.voice.GetSessionResponse
	(*ListSessionsRequest)(nil),   // 20: jarvis.voice.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 21: jarvis.voice.ListSessionsResponse
	(*VoiceSession)(nil),          // 22: jarvis.voice.VoiceSession
	nil,                           // 23: jarvis.voice.Reply.MetadataEntry
	(*common.RequestMeta)(nil),    // 24: jarvis.common.RequestMeta
	(common.Severity)(0),          // 25: jarvis.common.Severity
	(*common.ResponseMeta)(nil),   // 26: jarvis.common.ResponseMeta
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_voice_voice_proto_depIdxs = []int32{
	6,  // 0: jarvis.voice.ConverseRequest.config:type_name -> jarvis.voice.StreamConfig
	9,  // 1: jarvis.voice.ConverseRequest.audio:type_name -> jarvis.voice.AudioChunk
	10, // 2: jarvis.voice.ConverseRequest.event:type_name -> jarvis.voice.ControlEvent
	24, // 3: jarvis.voice.StreamConfig.meta:type_name -> jarvis.common.RequestMeta
	7,  // 4: jarvis.voice.StreamConfig.client_info:type_name -> jarvis.voice.ClientInfo
	8,  // 5: jarvis.voice.StreamConfig.audio_config:type_name -> jarvis.voice.AudioConfig
	0,  // 6: jarvis.voice.AudioConfig.encoding:type_name -> jarvis.voice.AudioEncoding
	2,  // 7: jarvis.voice.ControlEvent.type:type_name -> jarvis.voice.ControlEvent.Type
	12, // 8: jarvis.voice.ConverseResponse.status:type_name -> jarvis.voice.StatusEvent
	13, // 9: jarvis.voice.ConverseResponse.transcript:type_name -> jarvis.voice.Transcript
	15, // 10: jarvis.voice.ConverseResponse.reply:type_name -> jarvis.voice.Reply
	16, // 11: jarvis.voice.ConverseResponse.audio_reply:type_name -> jarvis.voice.AudioReply
	17, // 12: jarvis.voice.ConverseResponse.action:type_name -> jarvis.voice.HUDAction
	3,  // 13: jarvis.voice.StatusEvent.state:type_name -> jarvis.voice.StatusEvent.State
	1,  // 14: jarvis.voice.StatusEvent.error_code:type_name -> jarvis.voice.VoiceErrorCode
	14, // 15: jarvis.voice.Transcript.words:type_name -> jarvis.voice.WordInfo
	23, // 16: jarvis.voice.Reply.metadata:type_name -> jarvis.voice.Reply.MetadataEntry
	0,  // 17: jarvis.voice.AudioReply.encoding:type_name -> jarvis.voice.AudioEncoding
	4,  // 18: jarvis.voice.HUDAction.type:type_name -> jarvis.voice.HUDAction.Type
	25, // 19: jarvis.voice.HUDAction.severity:type_name -> jarvis.common.Severity
	24, // 20: jarvis.voice.GetSessionRequest.meta:type_name -> jarvis.common.RequestMeta
	26, // 21: jarvis.voice.GetSessionResponse.meta:type_name -> jarvis.common.ResponseMeta
	22, // 22: jarvis.voice.GetSessionResponse.session:type_name -> jarvis.voice.VoiceSession
	24, // 23: jarvis.voice.ListSessionsRequest.meta:type_name -> jarvis.common.RequestMeta
	26, // 24: jarvis.voice.ListSessionsResponse.meta:type_name -> jarvis.common.ResponseMeta
	22, // 25: jarvis.voice.ListSessionsResponse.sessions:type_name -> jarvis.voice.VoiceSession
	27, // 26: jarvis.voice.VoiceSession.started_at:type_name -> google.protobuf.Timestamp
	27, // 27: jarvis.voice.VoiceSession.ended_at:type_name -> google.protobuf.Timestamp
	13, // 28: jarvis.voice.VoiceSession.turns:type_name -> jarvis.voice.Transcript
	3,  // 29: jarvis.voice.VoiceSession.terminal_state:type_name -> jarvis.voice.StatusEvent.State
	5,  // 30: jarvis.voice.VoiceService.Converse:input_type -> jarvis.voice.ConverseRequest
	18, // 31: jarvis.voice.VoiceService.GetSession:input_type -> jarvis.voice.GetSessionRequest
	20, // 32: jarvis.voice.VoiceService.ListSessions:input_type -> jarvis.voice.ListSessionsRequest
	11, // 33: jarvis.voice.VoiceService.Converse:output_type -> jarvis.voice.ConverseResponse
	19, // 34: jarvis.voice.VoiceService.GetSession:output_type -> jarvis.voice.GetSessionResponse
	21, // 35: jarvis.voice.VoiceService.ListSessions:output_type -> jarvis.voice.ListSessionsResponse
	33, // [33:36] is the sub-list for method output_type
	30, // [30:33] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_voice_voice_proto_init() }
func file_voice_voice_proto_init() {
	if File_voice_voice_proto != nil {
		return
	}
	file_voice_voice_proto_msgTypes[0].OneofWrappers = []any{
		(*ConverseRequest_Config)(nil),
		(*ConverseRequest_Audio)(nil),
		(*ConverseRequest_Event)(nil),
	}
	file_voice_voice_proto_msgTypes[6].OneofWrappers = []any{
		(*ConverseResponse_Status)(nil),
		(*ConverseResponse_Transcript)(nil),
		(*ConverseResponse_Reply)(nil),
		(*ConverseResponse_AudioReply)(nil),
		(*ConverseResponse_Action)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_voice_proto_rawDesc), len(file_voice_voice_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_voice_proto_goTypes,
		DependencyIndexes: file_voice_voice_proto_depIdxs,
		EnumInfos:         file_voice_voice_proto_enumTypes,
		MessageInfos:      file_voice_voice_proto_msgTypes,
	}.Build()
	File_voice_voice_proto = out.File
	file_voice_voice_proto_goTypes = nil
	file_voice_voice_proto_depIdxs = nil
}
