// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nlp/nlp.proto

package nlp

import (
	common "github.com/rkrimper1/jarvis/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intent int32

const (
	Intent_INTENT_UNSPECIFIED      Intent = 0
	Intent_INTENT_QUERY            Intent = 1
	Intent_INTENT_COMMAND          Intent = 2
	Intent_INTENT_STATUS_CHECK     Intent = 3
	Intent_INTENT_SYSTEM_CONTROL   Intent = 4
	Intent_INTENT_THREAT_ALERT     Intent = 5
	Intent_INTENT_SCHEDULE         Intent = 6
	Intent_INTENT_RESEARCH         Intent = 7
	Intent_INTENT_EMERGENCY        Intent = 8
	Intent_INTENT_ANALYSIS_REQUEST Intent = 9
	Intent_INTENT_SMALL_TALK       Intent = 10
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0:  "INTENT_UNSPECIFIED",
		1:  "INTENT_QUERY",
		2:  "INTENT_COMMAND",
		3:  "INTENT_STATUS_CHECK",
		4:  "INTENT_SYSTEM_CONTROL",
		5:  "INTENT_THREAT_ALERT",
		6:  "INTENT_SCHEDULE",
		7:  "INTENT_RESEARCH",
		8:  "INTENT_EMERGENCY",
		9:  "INTENT_ANALYSIS_REQUEST",
		10: "INTENT_SMALL_TALK",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED":      0,
		"INTENT_QUERY":            1,
		"INTENT_COMMAND":          2,
		"INTENT_STATUS_CHECK":     3,
		"INTENT_SYSTEM_CONTROL":   4,
		"INTENT_THREAT_ALERT":     5,
		"INTENT_SCHEDULE":         6,
		"INTENT_RESEARCH":         7,
		"INTENT_EMERGENCY":        8,
		"INTENT_ANALYSIS_REQUEST": 9,
		"INTENT_SMALL_TALK":       10,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_nlp_nlp_proto_enumTypes[0].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_nlp_nlp_proto_enumTypes[0]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{0}
}

// Entity field names match Go service code exactly
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_nlp_nlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Entity) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ParseIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	ContextTags   []string               `protobuf:"bytes,3,rep,name=context_tags,json=contextTags,proto3" json:"context_tags,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseIntentRequest) Reset() {
	*x = ParseIntentRequest{}
	mi := &file_nlp_nlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIntentRequest) ProtoMessage() {}

func (x *ParseIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIntentRequest.ProtoReflect.Descriptor instead.
func (*ParseIntentRequest) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *ParseIntentRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ParseIntentRequest) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *ParseIntentRequest) GetContextTags() []string {
	if x != nil {
		return x.ContextTags
	}
	return nil
}

func (x *ParseIntentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParseIntentRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type ParseIntentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Intent           Intent                 `protobuf:"varint,2,opt,name=intent,proto3,enum=jarvis.nlp.Intent" json:"intent,omitempty"`
	Confidence       float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CanonicalCommand string                 `protobuf:"bytes,4,opt,name=canonical_command,json=canonicalCommand,proto3" json:"canonical_command,omitempty"`
	Entities         []*Entity              `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	SuggestedActions []string               `protobuf:"bytes,6,rep,name=suggested_actions,json=suggestedActions,proto3" json:"suggested_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParseIntentResponse) Reset() {
	*x = ParseIntentResponse{}
	mi := &file_nlp_nlp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIntentResponse) ProtoMessage() {}

func (x *ParseIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIntentResponse.ProtoReflect.Descriptor instead.
func (*ParseIntentResponse) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{2}
}

func (x *ParseIntentResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ParseIntentResponse) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *ParseIntentResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ParseIntentResponse) GetCanonicalCommand() string {
	if x != nil {
		return x.CanonicalCommand
	}
	return ""
}

func (x *ParseIntentResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ParseIntentResponse) GetSuggestedActions() []string {
	if x != nil {
		return x.SuggestedActions
	}
	return nil
}

// DialogueTurnRequest — field is "utterance" not "user_input"
type ProcessDialogueTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Utterance     string                 `protobuf:"bytes,3,opt,name=utterance,proto3" json:"utterance,omitempty"`
	ContextHint   string                 `protobuf:"bytes,4,opt,name=context_hint,json=contextHint,proto3" json:"context_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDialogueTurnRequest) Reset() {
	*x = ProcessDialogueTurnRequest{}
	mi := &file_nlp_nlp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDialogueTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDialogueTurnRequest) ProtoMessage() {}

func (x *ProcessDialogueTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDialogueTurnRequest.ProtoReflect.Descriptor instead.
func (*ProcessDialogueTurnRequest) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessDialogueTurnRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProcessDialogueTurnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessDialogueTurnRequest) GetUtterance() string {
	if x != nil {
		return x.Utterance
	}
	return ""
}

func (x *ProcessDialogueTurnRequest) GetContextHint() string {
	if x != nil {
		return x.ContextHint
	}
	return ""
}

// ProcessDialogueTurnResponse — fields are reply_text and requires_confirmation
type ProcessDialogueTurnResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReplyText            string                 `protobuf:"bytes,3,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	ResolvedIntent       Intent                 `protobuf:"varint,4,opt,name=resolved_intent,json=resolvedIntent,proto3,enum=jarvis.nlp.Intent" json:"resolved_intent,omitempty"`
	RequiresConfirmation bool                   `protobuf:"varint,5,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessDialogueTurnResponse) Reset() {
	*x = ProcessDialogueTurnResponse{}
	mi := &file_nlp_nlp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDialogueTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDialogueTurnResponse) ProtoMessage() {}

func (x *ProcessDialogueTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDialogueTurnResponse.ProtoReflect.Descriptor instead.
func (*ProcessDialogueTurnResponse) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessDialogueTurnResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProcessDialogueTurnResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessDialogueTurnResponse) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

func (x *ProcessDialogueTurnResponse) GetResolvedIntent() Intent {
	if x != nil {
		return x.ResolvedIntent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *ProcessDialogueTurnResponse) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

// DialogueHistory tracks conversation turns per session
type DialogueHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogueHistory) Reset() {
	*x = DialogueHistory{}
	mi := &file_nlp_nlp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueHistory) ProtoMessage() {}

func (x *DialogueHistory) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueHistory.ProtoReflect.Descriptor instead.
func (*DialogueHistory) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{5}
}

func (x *DialogueHistory) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DialogueHistory) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DialogueHistory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamVoiceInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.RequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	ContextTags   []string               `protobuf:"bytes,3,rep,name=context_tags,json=contextTags,proto3" json:"context_tags,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVoiceInputRequest) Reset() {
	*x = StreamVoiceInputRequest{}
	mi := &file_nlp_nlp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVoiceInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVoiceInputRequest) ProtoMessage() {}

func (x *StreamVoiceInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVoiceInputRequest.ProtoReflect.Descriptor instead.
func (*StreamVoiceInputRequest) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{6}
}

func (x *StreamVoiceInputRequest) GetMeta() *common.RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamVoiceInputRequest) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *StreamVoiceInputRequest) GetContextTags() []string {
	if x != nil {
		return x.ContextTags
	}
	return nil
}

func (x *StreamVoiceInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamVoiceInputRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type StreamVoiceInputResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *common.ResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Intent           Intent                 `protobuf:"varint,2,opt,name=intent,proto3,enum=jarvis.nlp.Intent" json:"intent,omitempty"`
	Confidence       float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CanonicalCommand string                 `protobuf:"bytes,4,opt,name=canonical_command,json=canonicalCommand,proto3" json:"canonical_command,omitempty"`
	Entities         []*Entity              `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	SuggestedActions []string               `protobuf:"bytes,6,rep,name=suggested_actions,json=suggestedActions,proto3" json:"suggested_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamVoiceInputResponse) Reset() {
	*x = StreamVoiceInputResponse{}
	mi := &file_nlp_nlp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVoiceInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVoiceInputResponse) ProtoMessage() {}

func (x *StreamVoiceInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_nlp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVoiceInputResponse.ProtoReflect.Descriptor instead.
func (*StreamVoiceInputResponse) Descriptor() ([]byte, []int) {
	return file_nlp_nlp_proto_rawDescGZIP(), []int{7}
}

func (x *StreamVoiceInputResponse) GetMeta() *common.ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StreamVoiceInputResponse) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *StreamVoiceInputResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StreamVoiceInputResponse) GetCanonicalCommand() string {
	if x != nil {
		return x.CanonicalCommand
	}
	return ""
}

func (x *StreamVoiceInputResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *StreamVoiceInputResponse) GetSuggestedActions() []string {
	if x != nil {
		return x.SuggestedActions
	}
	return nil
}

var File_nlp_nlp_proto protoreflect.FileDescriptor

const file_nlp_nlp_proto_rawDesc = "" +
	"\n" +
	"\rnlp/nlp.proto\x12\n" +
	"jarvis.nlp\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\x06Entity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\xc6\x01\n" +
	"\x12ParseIntentRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12!\n" +
	"\fcontext_tags\x18\x03 \x03(\tR\vcontextTags\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\"\x9c\x02\n" +
	"\x13ParseIntentResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12*\n" +
	"\x06intent\x18\x02 \x01(\x0e2\x12.jarvis.nlp.IntentR\x06intent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x11canonical_command\x18\x04 \x01(\tR\x10canonicalCommand\x12.\n" +
	"\bentities\x18\x05 \x03(\v2\x12.jarvis.nlp.EntityR\bentities\x12+\n" +
	"\x11suggested_actions\x18\x06 \x03(\tR\x10suggestedActions\"\xac\x01\n" +
	"\x1aProcessDialogueTurnRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tutterance\x18\x03 \x01(\tR\tutterance\x12!\n" +
	"\fcontext_hint\x18\x04 \x01(\tR\vcontextHint\"\xfe\x01\n" +
	"\x1bProcessDialogueTurnResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x03 \x01(\tR\treplyText\x12;\n" +
	"\x0fresolved_intent\x18\x04 \x01(\x0e2\x12.jarvis.nlp.IntentR\x0eresolvedIntent\x123\n" +
	"\x15requires_confirmation\x18\x05 \x01(\bR\x14requiresConfirmation\"s\n" +
	"\x0fDialogueHistory\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcb\x01\n" +
	"\x17StreamVoiceInputRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.jarvis.common.RequestMetaR\x04meta\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12!\n" +
	"\fcontext_tags\x18\x03 \x03(\tR\vcontextTags\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\"\xa1\x02\n" +
	"\x18StreamVoiceInputResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.jarvis.common.ResponseMetaR\x04meta\x12*\n" +
	"\x06intent\x18\x02 \x01(\x0e2\x12.jarvis.nlp.IntentR\x06intent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x11canonical_command\x18\x04 \x01(\tR\x10canonicalCommand\x12.\n" +
	"\bentities\x18\x05 \x03(\v2\x12.jarvis.nlp.EntityR\bentities\x12+\n" +
	"\x11suggested_actions\x18\x06 \x03(\tR\x10suggestedActions*\x87\x02\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fINTENT_QUERY\x10\x01\x12\x12\n" +
	"\x0eINTENT_COMMAND\x10\x02\x12\x17\n" +
	"\x13INTENT_STATUS_CHECK\x10\x03\x12\x19\n" +
	"\x15INTENT_SYSTEM_CONTROL\x10\x04\x12\x17\n" +
	"\x13INTENT_THREAT_ALERT\x10\x05\x12\x13\n" +
	"\x0fINTENT_SCHEDULE\x10\x06\x12\x13\n" +
	"\x0fINTENT_RESEARCH\x10\a\x12\x14\n" +
	"\x10INTENT_EMERGENCY\x10\b\x12\x1b\n" +
	"\x17INTENT_ANALYSIS_REQUEST\x10\t\x12\x15\n" +
	"\x11INTENT_SMALL_TALK\x10\n" +
	"2\xdf\x02\n" +
	"\n" +
	"NLPService\x12h\n" +
	"\vParseIntent\x12\x1e.jarvis.nlp.ParseIntentRequest\x1a\x1f.jarvis.nlp.ParseIntentResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/nlp/parse\x12\x83\x01\n" +
	"\x13ProcessDialogueTurn\x12&.jarvis.nlp.ProcessDialogueTurnRequest\x1a'.jarvis.nlp.ProcessDialogueTurnResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/nlp/dialogue\x12a\n" +
	"\x10StreamVoiceInput\x12#.jarvis.nlp.StreamVoiceInputRequest\x1a$.jarvis.nlp.StreamVoiceInputResponse(\x010\x01B\x8b\x01\n" +
	"\x0ecom.jarvis.nlpB\bNlpProtoP\x01Z&github.com/rkrimper1/jarvis/api/pb/nlp\xa2\x02\x03JNX\xaa\x02\n" +
	"Jarvis.Nlp\xca\x02\n" +
	"Jarvis\\Nlp\xe2\x02\x16Jarvis\\Nlp\\GPBMetadata\xea\x02\vJarvis::Nlpb\x06proto3"

var (
	file_nlp_nlp_proto_rawDescOnce sync.Once
	file_nlp_nlp_proto_rawDescData []byte
)

func file_nlp_nlp_proto_rawDescGZIP() []byte {
	file_nlp_nlp_proto_rawDescOnce.Do(func() {
		file_nlp_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nlp_nlp_proto_rawDesc), len(file_nlp_nlp_proto_rawDesc)))
	})
	return file_nlp_nlp_proto_rawDescData
}

var file_nlp_nlp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nlp_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nlp_nlp_proto_goTypes = []any{
	(Intent)(0),                         // 0: jarvis.nlp.Intent
	(*Entity)(nil),                      // 1: jarvis.nlp.Entity
	(*ParseIntentRequest)(nil),          // 2: jarvis.nlp.ParseIntentRequest
	(*ParseIntentResponse)(nil),         // 3: jarvis.nlp.ParseIntentResponse
	(*ProcessDialogueTurnRequest)(nil),  // 4: jarvis.nlp.ProcessDialogueTurnRequest
	(*ProcessDialogueTurnResponse)(nil), // 5: jarvis.nlp.ProcessDialogueTurnResponse
	(*DialogueHistory)(nil),             // 6: jarvis.nlp.DialogueHistory
	(*StreamVoiceInputRequest)(nil),     // 7: jarvis.nlp.StreamVoiceInputRequest
	(*StreamVoiceInputResponse)(nil),    // 8: jarvis.nlp.StreamVoiceInputResponse
	(*common.RequestMeta)(nil),          // 9: jarvis.common.RequestMeta
	(*common.ResponseMeta)(nil),         // 10: jarvis.common.ResponseMeta
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_nlp_nlp_proto_depIdxs = []int32{
	9,  // 0: jarvis.nlp.ParseIntentRequest.meta:type_name -> jarvis.common.RequestMeta
	10, // 1: jarvis.nlp.ParseIntentResponse.meta:type_name -> jarvis.common.ResponseMeta
	0,  // 2: jarvis.nlp.ParseIntentResponse.intent:type_name -> jarvis.nlp.Intent
	1,  // 3: jarvis.nlp.ParseIntentResponse.entities:type_name -> jarvis.nlp.Entity
	9,  // 4: jarvis.nlp.ProcessDialogueTurnRequest.meta:type_name -> jarvis.common.RequestMeta
	10, // 5: jarvis.nlp.ProcessDialogueTurnResponse.meta:type_name -> jarvis.common.ResponseMeta
	0,  // 6: jarvis.nlp.ProcessDialogueTurnResponse.resolved_intent:type_name -> jarvis.nlp.Intent
	11, // 7: jarvis.nlp.DialogueHistory.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 8: jarvis.nlp.StreamVoiceInputRequest.meta:type_name -> jarvis.common.RequestMeta
	10, // 9: jarvis.nlp.StreamVoiceInputResponse.meta:type_name -> jarvis.common.ResponseMeta
	0,  // 10: jarvis.nlp.StreamVoiceInputResponse.intent:type_name -> jarvis.nlp.Intent
	1,  // 11: jarvis.nlp.StreamVoiceInputResponse.entities:type_name -> jarvis.nlp.Entity
	2,  // 12: jarvis.nlp.NLPService.ParseIntent:input_type -> jarvis.nlp.ParseIntentRequest
	4,  // 13: jarvis.nlp.NLPService.ProcessDialogueTurn:input_type -> jarvis.nlp.ProcessDialogueTurnRequest
	7,  // 14: jarvis.nlp.NLPService.StreamVoiceInput:input_type -> jarvis.nlp.StreamVoiceInputRequest
	3,  // 15: jarvis.nlp.NLPService.ParseIntent:output_type -> jarvis.nlp.ParseIntentResponse
	5,  // 16: jarvis.nlp.NLPService.ProcessDialogueTurn:output_type -> jarvis.nlp.ProcessDialogueTurnResponse
	8,  // 17: jarvis.nlp.NLPService.StreamVoiceInput:output_type -> jarvis.nlp.StreamVoiceInputResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_nlp_nlp_proto_init() }
func file_nlp_nlp_proto_init() {
	if File_nlp_nlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nlp_nlp_proto_rawDesc), len(file_nlp_nlp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nlp_nlp_proto_goTypes,
		DependencyIndexes: file_nlp_nlp_proto_depIdxs,
		EnumInfos:         file_nlp_nlp_proto_enumTypes,
		MessageInfos:      file_nlp_nlp_proto_msgTypes,
	}.Build()
	File_nlp_nlp_proto = out.File
	file_nlp_nlp_proto_goTypes = nil
	file_nlp_nlp_proto_depIdxs = nil
}
